[EPUB] Prevent multiple results match highlight
learningequality/kolibri pull request #10008
Opened 2023-01-17 12:51 UTC by AlexVelezLl

## Summary

…

## References

…

## Reviewer guidance

…

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2023-01-17 21:09 UTC, rtibbles submitted a review, later dismissed
Need to switch CFI parser implementation for licensing reasons.

2023-01-17 21:09 UTC, rtibbles commented on kolibri/plugins/epub_viewer/assets/src/views/SearchSideBar.vue
> +  import CFI from 'epub-cfi-resolver';
Unfortunately, `epub-cfi-resolver` is licensed under an AGPL license, which is not compatible with the MIT license that we use for Kolibri (MIT is more permissive, and so including AGPL software in our codebase would require us to adopt a similarly restrictive license to AGPL for compatibility).

If what you are doing works with the EPUBJS CFI parser: https://github.com/futurepress/epub.js/blob/master/src/epubcfi.js I would suggest just using that instead. I note that the author of this library says that the epubcfi parser is incomplete, but I assume it's also using it for other things, so at least the breakage will be consistent.

2023-01-30 14:55 UTC, pcenov commented
@radinamatic  I've tested this in both Windows and Ubuntu and it is functioning as described.

2023-01-30 17:45 UTC, rtibbles commented
This looks good - just needs a rebase on develop to resolve the merge conflict with #10048 - and can add the follow up from there to remove the `markjs` dependency there too.

2023-02-05 17:38 UTC, AlexVelezLl commented
Hi @rtibbles ! Sorry for the delay, the PR has already been updated, removing the markjs dependency, the results are still the same as the pr summary.

2023-02-07 17:56 UTC, rtibbles requested changes
Code looks correct to me - @pcenov can you reconfirm the fix now that the implementation has been updated?

One thing still needs to be done which is removing the markjs dependency:

```
yarn workspace kolibri-document-epub-render-plugin remove mark.js
```

The name of the workspace is given by the name given in this plugin's package.json:
https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/epub_viewer/package.json#L2

2023-02-07 18:01 UTC, AlexVelezLl commented
Oh @rtibbles we can not remove the markjs dependency because it is still used to mark the epub content. Which I think would take a bit longer to migrate

2023-02-07 18:03 UTC, rtibbles commented
Ah, ok - that makes sense - the EPUB content is significantly less under our control!

2023-02-07 18:03 UTC, rtibbles approved these changes

2023-02-07 18:03 UTC, merged

2023-02-08 11:34 UTC, pcenov commented
@rtibbles I've reconfirmed the fix - no issues observed. Thank you @AlexVelezLl!