Created network resource discovery cards
learningequality/kolibri pull request #10111
Opened 2023-02-13 15:50 UTC by AllanOXDi

## Summary

## References

## Reviewer guidance

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2023-02-27 12:04 UTC, akolson requested changes
Thanks @AllanOXDi! Generally, the code looks good. However, I do have some concerns regarding how the pinned and unpinned components are fetching content in isolation. These two components are essentially displaying the same content with the difference being whether they are pinned or not. The pinning and unpinning operation is one that will be handled by https://github.com/learningequality/kolibri/issues/9858. In light of this, my thinking is that the responsibility to fetch device and channel content should be left to the `LibraryPage` component and the data simply passed to the pinned and unpinned resource components. We can filter data to determine the pinned and unpinned devices in connection with the pinning and unpinning resources that will will be built with the above mentioned GH task.

2023-02-27 12:04 UTC, akolson commented on kolibri/plugins/learn/assets/src/views/LibraryPage/CardContent.vue
> +  import responsiveWindowMixin from 'kolibri.coreVue.mixins.responsiveWindowMixin';
There is a useKResponsiveWindow composable that should be used in place of this mixin. Please see https://github.com/learningequality/kolibri/blob/1b5898310a58ce6e788d1d48a109b02ff29a41bb/kolibri/plugins/learn/assets/src/views/LibraryPage/index.vue for a usage example

2023-02-27 12:04 UTC, akolson commented on kolibri/plugins/learn/assets/src/views/LibraryPage/MoreNetworkDevices.vue
> +  import responsiveWindowMixin from 'kolibri.coreVue.mixins.responsiveWindowMixin';
There is a useKResponsiveWindow composable that should be used in place of this mixin. Please see https://github.com/learningequality/kolibri/blob/1b5898310a58ce6e788d1d48a109b02ff29a41bb/kolibri/plugins/learn/assets/src/views/LibraryPage/index.vue for a usage example

2023-02-27 12:04 UTC, akolson commented on kolibri/plugins/learn/assets/src/views/LibraryPage/ResumableContentGrid.vue
> +      <PinnedNetworkResources />
I think the `PinnedNetworkResources` and `MoreNetworkDevices` components should be moved  to the `LibraryPage` component just below the `ResumableContentGrid` component for purposes of clarity but also because the `ResumableContentGrid ` component represents recently viewed content on the `LibraryPage` component

2023-03-01 20:04 UTC, rtibbles commented on kolibri/plugins/learn/assets/src/views/LibraryPage/index.vue
> +        message: 'View More',
Note that we already have this string in `commonCoreStrings` so we don't need to add this here!

2023-03-02 12:41 UTC, akolson commented on kolibri/plugins/learn/assets/src/views/LibraryPage/PinnedNetworkResources.vue
> +  import responsiveWindowMixin from 'kolibri.coreVue.mixins.responsiveWindowMixin';
There is a useKResponsiveWindow composable that should be used in place of this mixin. Please see https://github.com/learningequality/kolibri/blob/1b5898310a58ce6e788d1d48a109b02ff29a41bb/kolibri/plugins/learn/assets/src/views/LibraryPage/index.vue for a usage example

2023-03-02 12:41 UTC, akolson commented on kolibri/plugins/learn/assets/src/views/LibraryPage/UnPinnedDevices.vue
> +  import responsiveWindowMixin from 'kolibri.coreVue.mixins.responsiveWindowMixin';
There is a useKResponsiveWindow composable that should be used in place of this mixin. Please see https://github.com/learningequality/kolibri/blob/1b5898310a58ce6e788d1d48a109b02ff29a41bb/kolibri/plugins/learn/assets/src/views/LibraryPage/index.vue for a usage example

2023-03-02 21:55 UTC, akolson approved these changes
Thanks @AllanOXDi Pr is good to go! A note that this is a WIP but code is good enough to merge into develop to aid the string translation process cc @marcellamaki

2023-03-02 22:34 UTC, marcellamaki commented
Thank you @AllanOXDi and @akolson!

2023-03-02 22:34 UTC, merged