Download Request functionality for resource cards in remote libraries
learningequality/kolibri pull request #10129
Opened 2023-02-17 18:12 UTC by rtibbles

## Summary
* Updates the backend to add the admin_imported flag for ContentNodes (ref: #10079) and adds an upgrade task for that
* Updates the backend to return this data from the backend, and annotate this data onto remotely returned resources, so that we have a track of local state for the resources being browsed. Does this without adding additional bloat to the public ContentNode endpoint by creating an inherited mixin for internal usage.
* Creates a skeleton composable for exposing a map of current download requests, and fetching download requests. This will probably need to be embellished to allow for more selective fetches, in the case that the list needs to be paginated.
* Creates a separate HybridLearningFooter component to consolidate our footer information/actions. Includes the ProgressBar, coach content icons, and 'clear bookmark', 'show info' 'download resource', 'remove resource' actions.
* Does a small refactor of HybridLearningContentCard and CardList components to give them the same props API as ResourceCard. Adds a standard 'footer' slot to each card to allow injection of the new footer component.
* Adds a deviceId prop to LibraryPage and TopicsPage to flag whether we are on a remote device or not, uses this to propagate props down to enable or disable download request functionality.
* Also uses this deviceId prop to hide the Resume section on the remote device library page.

## References
Fixes https://github.com/learningequality/kolibri/issues/9857

Note: we will need a follow up issue for properly connecting the composable to the backend once it has been created.

## Reviewer guidance
Any regressions? Anything deleted that should not have been? Are all the footer action buttons working as intended?

Screencast of the new functionality:
[Screencast from 02-17-2023 10:03:58 AM.webm](https://user-images.githubusercontent.com/1680573/219741884-52de6484-4852-4690-bb8a-3f0585da9f0a.webm)

Screenshot of non-remote device:
![image](https://user-images.githubusercontent.com/1680573/219742216-74938c8f-dbd9-4e7d-a80b-1063cc9dec6c.png)

Screencast of bookmarking:
[Screencast from 02-17-2023 10:12:22 AM.webm](https://user-images.githubusercontent.com/1680573/219744838-1ac76d35-e472-4184-ba73-4d7617741a0a.webm)

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2023-02-17 20:33 UTC, marcellamaki requested changes, later dismissed
Overall the basic code changes and refactoring make sense to me, but there are a few places with card regressions: 
The list view is missing padding and also the height is off, I think even accounting for the padding.  
<img width="1433" alt="Screenshot 2023-02-17 at 3 06 23 PM" src="https://user-images.githubusercontent.com/17235236/219783620-307b900b-0f1d-4d58-aa6f-57c15dbb9856.png">

And bookmark cards on medium and mobile screens are also a bit wonky 
<img width="537" alt="Screenshot 2023-02-17 at 3 07 49 PM" src="https://user-images.githubusercontent.com/17235236/219783977-436aa758-3a16-4960-ad47-01469223d905.png">
<img width="272" alt="Screenshot 2023-02-17 at 3 07 19 PM" src="https://user-images.githubusercontent.com/17235236/219783998-13c274c5-cee3-4186-acdc-38a1e0da7af9.png">

vs. current 
<img width="256" alt="Screenshot 2023-02-17 at 3 18 35 PM" src="https://user-images.githubusercontent.com/17235236/219784995-626a4c2f-48cf-4366-8f2b-ffc85ee84d06.png">

<img width="829" alt="Screenshot 2023-02-17 at 3 18 25 PM" src="https://user-images.githubusercontent.com/17235236/219784983-bb5e5aa5-3d95-43d1-98e3-3c84ecb3ec41.png">


The last thing, which I'm not sure I'm testing accurately is, I don't actually see the download button when I'm browsing another library. Maybe I'm supposed to be mocking a setting for this PR for testing? This is what i see browsing Jacob's library (as an admin)

<img width="1435" alt="Screenshot 2023-02-17 at 3 32 51 PM" src="https://user-images.githubusercontent.com/17235236/219787435-081a132b-07c3-4347-9c50-d6807c6bb7a6.png">

2023-02-17 20:33 UTC, marcellamaki commented on kolibri/plugins/learn/assets/src/routes/index.js
> +    props: true,
I'm not totally clear on how the changes for this PR are related to this. Is it because the CardList is now using `:to` not `:link`?

2023-02-18 15:59 UTC, rtibbles commented on kolibri/plugins/learn/assets/src/routes/index.js
> +    props: true,
No, this is just to pass the deviceId URL parameter as a prop when it is active.

2023-02-22 18:26 UTC, rtibbles commented
This should now be updated with the card list component now presenting like this:
![Screenshot from 2023-02-22 08-55-49](https://user-images.githubusercontent.com/1680573/220721959-140f06ee-fb4f-483e-89a7-727e38dcead8.png)

2023-02-22 22:52 UTC, marcellamaki approved these changes
This looks better. I suspect we may still get some UI feedback from the design team, but that doesn't need to be blocking at this stage, since it's close and the core functionality is working

2023-02-22 22:52 UTC, merged