Remove cross component translator references
learningequality/kolibri pull request #10145
Opened 2023-02-27 13:39 UTC by marcellamaki

## Summary

- Removes use of cross-component translator
- Deletes unused components and moves the strings when appropriate (several refactored components existed only for the strings)
- Move some strings to common string files, to reduce the number of references and unnecessary multiple translations

## References
Fixes #9037 

## Reviewer guidance
There were a lot of moving parts here. Fresh eyes able to see anything I missed or dropped? 

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2023-02-27 19:55 UTC, rtibbles reviewed
Code changes seem to make sense to me. There are some failing frontend tests, that suggests maybe something isn't quite working as intended though?

2023-02-27 20:58 UTC, marcellamaki commented
Thanks for flagging - I did not check tests for dependent strings... that seems to be the issue. Will update. Hopefully a small fix.

2023-02-28 01:43 UTC, rtibbles requested changes
Still a little more cleanup needed!

2023-02-28 01:43 UTC, rtibbles commented on kolibri/plugins/learn/assets/src/views/CurrentlyViewedResourceMetadata.vue
> +    $tr: {
Seems like these strings are redundant, or if they aren't, we should be changing references to them to read from `learnString`?

2023-02-28 01:43 UTC, rtibbles commented on kolibri/plugins/learn/assets/src/views/CurrentlyViewedResourceMetadata.vue
> +        {{ coreString(forBeginners) }}
This appears to be missing `''`.

2023-02-28 01:43 UTC, rtibbles commented on kolibri/plugins/learn/assets/src/views/LibraryPage/index.vue
> -      clearAll: {
I think that we can remove the `results` and `moreThanXResults` strings above as well?

2023-02-28 01:43 UTC, rtibbles commented on kolibri/plugins/learn/assets/src/views/SidePanelModal/SidePanelResourcesList.vue
> -      noOtherLessonResources: {
According to the comment in the template, we can delete this file entirely, so we should do so!

2023-02-28 15:52 UTC, rtibbles approved these changes
Code changes look correct, and I couldn't find any related errors from a manual check through.

2023-02-28 15:52 UTC, merged