Fixed #10397.
learningequality/kolibri pull request #10422
Opened 2023-04-08 20:19 UTC by Wck-iipi

## Summary

Changed Language to LanguageLabel.

## References

Fixed #10397.

## Reviewer guidance

…

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2023-04-11 16:31 UTC, rtibbles commented
Hi @Wck-iipi - for future reference, please do make a comment on an issue when you are intending to pick it up, so that we can assign you, and avoid potentially duplicating effort.

2023-04-11 16:37 UTC, rtibbles requested changes
This fixes a seemingly unreported issue, so we should keep this change, but does not fix the reported issue, as it is still showing this:

![image](https://user-images.githubusercontent.com/1680573/231230059-229e1470-8dda-4d2e-ab26-c7e4af945c4f.png)

Need to update the string reference here as well: https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/learn/assets/src/views/BrowseResourceMetadata.vue#L86

2023-04-12 13:08 UTC, Wck-iipi commented
@rtibbles Sorry, I will comment on an issue before trying to solve it. Also, thanks for guiding me, I have made a commit doing what you told me to do.

2023-04-12 15:41 UTC, rtibbles approved these changes

2023-04-12 15:41 UTC, merged