Fixed Update #8532 Replace TextTruncator with TextTruncatorCss
learningequality/kolibri pull request #10518
Opened 2023-04-19 14:36 UTC by Pursottam6003

## Summary

From the Issue #8532  I have changed the `TextTruncator` with `TextTruncatorCss` in two files only ie `index.vue ` and `AlsoInThis.vue` 

## References

From the Issue discussion, i got the little clue to do this #8532 

## Reviewer guidance

I have been asked to do changes in [step by step](https://github.com/learningequality/kolibri/issues/8532#issuecomment-1508085573) so that it would be easy to be evaluated and make corrections

----

## Testing checklist

- [X] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [X] PR has the correct target branch and milestone
- [X] PR has 'needs review' or 'work-in-progress' label
- [X] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2023-04-21 06:10 UTC, Pursottam6003 commented
Hii @MisRob  Could you please review this PR does it meet the requirements if not kindly let me know where should i need modifications

2023-04-21 06:58 UTC, MisRob commented
Thank you, @Pursottam6003, I will review it. Thank you for proceeding in smaller chunks, this will also help me to follow up with you sooner.

2023-04-21 07:31 UTC, MisRob commented
@Pursottam6003 In your upcoming pull requests, could you please add the reviewer guidance in a way that communicates how to preview places that were updated from a user point of view (whenever it's relevant)?

This would help a reviewer and especially our QA team as they will know where to navigate as a user and what places to check to confirm fixes, test for regressions, etc. (QA team can't determine where to go in the app according to file names). It doesn't need to be extremely detailed, just a couple of bullet points to give direction will do. Often it's similar to the way you previewed updates on your dev server so as you're working next time, you could just note it down and then paste it to your PR)

2023-04-21 07:42 UTC, Pursottam6003 commented
> Hii @MisRob Could you please review this PR does it meet the requirements if not kindly let me know where should i need modifications

Sure mam I will definitely add Reviewer Guidelines in upcomming PRs

2023-04-26 10:58 UTC, MisRob requested changes
Thank you, @Pursottam6003. Some changes will be needed, please see the comment marked as blocking. Also, if you could reference places where you tested this as you're working on the update, that'd be helpful.

2023-04-26 10:58 UTC, MisRob commented on kolibri/plugins/coach/assets/src/views/plan/LessonResourceSelectionPage/LessonContentCard/index.vue
> +  import TextTruncatorCss from 'kolibri.coreVue.components.TextTruncatorCss'; //update
[minor] `//update` comment can be cleaned up. Same applies to the other updated component.

2023-04-26 10:58 UTC, MisRob commented on kolibri/plugins/coach/assets/src/views/plan/LessonResourceSelectionPage/LessonContentCard/index.vue
>          :maxHeight="80"
[blocking] `TextTruncatorCss` doesn't have `maxHeight` property. Instead, it has `maxLines` which expects a number of lines instead of height information. As we're moving to `TextTruncatorCss`, these places in the code will need to be updated to its interface too. I'd recommend briefly skimming through `TextTruncatorCss` file to understand it. The same applies to the other updated component.

2023-04-27 05:19 UTC, Pursottam6003 commented on kolibri/plugins/coach/assets/src/views/plan/LessonResourceSelectionPage/LessonContentCard/index.vue
> +  import TextTruncatorCss from 'kolibri.coreVue.components.TextTruncatorCss'; //update
ok mam

2023-04-27 05:22 UTC, Pursottam6003 commented on kolibri/plugins/coach/assets/src/views/plan/LessonResourceSelectionPage/LessonContentCard/index.vue
>          :maxHeight="80"
Sure mam, got it thanks for the review

2023-04-27 12:06 UTC, Pursottam6003 commented
> Thank you, @Pursottam6003. Some changes will be needed, please see the comment marked as blocking. Also, if you could reference places where you tested this as you're working on the update, that'd be helpful.

Hii @MisRob now I have resolved the invalid props reference error and tested the code both manually and by using the  `yarn run test ` and  `pre-commit run --all-files
`

![Screenshot from 2023-04-27 15-45-43](https://user-images.githubusercontent.com/81693090/234852860-81df87de-84dd-481a-9397-c8ced84cea92.png)


Now the TextTruncatorCss is successfully working inside the `kolibri/plugins/coach/assets/src/views/plan/LessonResourceSelectionPage/LessonContentCard/index.vue`

```   
<TextTruncatorCss
        v-if="!windowIsSmall"
        :text="description"
        :maxLines="3"
        class="description"
      />
    
 ```



![Screenshot from 2023-04-27 15-09-13](https://user-images.githubusercontent.com/81693090/234852589-06961a9d-12a3-4e96-b33a-964036c22339.png)

We can clearly see since the `maxLines` is set to 3  and if it exceeds the 3 lines  it will be truncated with `....`

2023-04-28 04:47 UTC, MisRob approved these changes
Thank you for your contribution and continuous cooperation, @Pursottam6003. It's looking good and I can confirm it works as expected in the other component as well.

![Screenshot from 2023-04-28 06-40-20](https://user-images.githubusercontent.com/13509191/235056261-fbc7e5ca-29d8-455d-b5a1-bd3a593eae4e.png)

 If you'd like to continue working on https://github.com/learningequality/kolibri/issues/8532, feel free to proceed. It should be more or less the same process - replacing the component, props, and then checking if it works as expected in places where updated components are used. As mentioned before if you could briefly note how to navigate to places you tested in your next PR description, it'd be welcome, so that we know what to test (no need to update screenshots for all of them unless there are some user-facing changes)

2023-04-28 04:50 UTC, merged