Block merge facility creating new account if target facility does not allow it
learningequality/kolibri pull request #10642
Opened 2023-05-04 17:12 UTC by jredrejo

## Summary
When merging an user from a facility to a target facility, in the case the latest does not allow users to create their own accounts, the process should be blocked, allowing only merging existing accounts.

In this screenshot, the Continue button is disabled because the target facility has the 'Allow learners to create accounts' option unchecked:
![image](https://user-images.githubusercontent.com/1008178/236276864-44bf67fc-7d69-4bab-92cb-91bd8cb61523.png)

## References
Closes: #10582

## Reviewer guidance

1. On Device 1 setup a full facility and disable the 'Allow learners to create accounts' option at Facility > Settings
2. On Device 2 create a facility by going through the 'On my own' flow
3. Create a learner account on Device 2 and sign in with that learner
4. Attempt to change the facility: Only the Merge accounts should be enabled, no chance to create a new account

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2023-05-04 21:57 UTC, rtibbles reviewed
This looks like the change I was expecting to see in terms of reading this setting from the target facility! If @pcenov concurs, let's merge this!

2023-05-05 11:00 UTC, pcenov requested changes
Hi @jredrejo this is implemented as specified in the description of the PR, the 'Continue' button is disabled. However if the user already exists on the target facility then after you click 'Merge accounts' you can see that at the next step there is an active 'Create new account' button which if selected will result in the incorrect flow. So in that case too the users should only be able to merge their accounts.

Video:

https://user-images.githubusercontent.com/79847249/236440773-c8e5633a-ea41-4a72-b329-7f49e350e00c.mp4

Logs:
[LogsAndDB.zip](https://github.com/learningequality/kolibri/files/11405555/LogsAndDB.zip)

2023-05-05 17:21 UTC, jredrejo commented
> Hi @jredrejo this is implemented as specified in the description of the PR, the 'Continue' button is disabled. However if the user already exists on the target facility then after you click 'Merge accounts' you can see that at the next step there is an active 'Create new account' button which if selected will result in the incorrect flow. So in that case too the users should only be able to merge their accounts.
> 
> Video:
> 
>  2023-05-05_13-40-13.mp4 
> Logs: [LogsAndDB.zip](https://github.com/learningequality/kolibri/files/11405555/LogsAndDB.zip)

Thanks @pcenov . I didn't remember that other place where accounts could be created. It should be fine now.

2023-05-09 10:22 UTC, pcenov approved these changes
Thanks @jredrejo this is working correctly now in both cases.
I have reported separately an unrelated issue which I was able to identify while regression testing this one: https://github.com/learningequality/kolibri/issues/10661

2023-05-09 14:54 UTC, merged