Gbsneto/viewport width epub
learningequality/kolibri pull request #10685
Opened 2023-05-11 16:16 UTC by GeorgesStavracas

## Summary

EpubRenderer currently injects custom CSS to the rendered ePub.js iFrame by using the theming helpers of ePub.js' Rendition class. The goal of the custom style is to improve table layouts on smaller screens, as per b16cbfff6 and dd467d0bfc62.

One of these custom styles is `max-width: 100%`, which on a first glance is absolutely fine, and on a second glance is fine too, but upon testing, it has proven to break some ePub files. Removing it is not an option, since it might regress on the small screen case.

Switch max-width styles to 100vw, instead of 100%, which works fine on the pathological ePub files, and doesn't regress on the small screen case. These CSS units are available on all browsers for almost a decade now, so they should be safe to use!

## References

https://github.com/learningequality/kolibri/issues/10684

## Reviewer guidance

* b16cbfff6 and dd467d0bfc62 should not regress
* ePub files with background images should render appropriately

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2023-05-11 21:08 UTC, bjester requested changes
Hi @GeorgesStavracas, thank you for your interest in contributing. I think dropping `!important` may be okay-- I'll let our QA team verify-- but the other change I don't think is appropriate and I left comments on the reasoning.

2023-05-11 21:08 UTC, bjester commented on kolibri/plugins/epub_viewer/assets/src/views/EpubRendererIndex.vue
> +          img: { 'max-width': '100vw' },
I don't believe this to work in all cases. Some epubs may have 2 page, book-like, layouts where pages show side-by-side. Having this go from `100%`, which would be 100% of the containing element's width, to `100vw` would change it to be the browser's full viewport/frame width. Therefore, I think this should remain as is.

2023-05-15 17:16 UTC, GeorgesStavracas commented
Because I don't think I'm allowed to share the ePub file that sparked this investigation, I've crafted a minimal reproducer and shared it on the [corresponding issue](https://github.com/learningequality/kolibri/issues/10684#issuecomment-1548235325). Please let me know if you have further suggestions, I'll apply it ASAP.

2023-05-17 12:52 UTC, pcenov commented
Hi @bjester and @GeorgesStavracas just wanted to mention briefly that I couldn't find any regressions while manually testing this and more importantly when comparing it to the previous version of the ePub viewer I do see significant improvements especially in the Arabic books which are now correctly aligned RTL.

2023-05-17 15:33 UTC, pcenov commented
Actually @GeorgesStavracas I am not able to see the image in the minimal reproducer file that you provided, could you check that and reupload it? It's not displayed neither in the build containing your code changes or in a previous build of Kolibri...

![2023-05-17_18-30-15](https://github.com/learningequality/kolibri/assets/79847249/bfee6aee-04d9-4090-9f5b-ea75f28d2466)

2023-05-17 16:26 UTC, GeorgesStavracas commented
> Hi @bjester and @GeorgesStavracas just wanted to mention briefly that I couldn't find any regressions while manually testing this and more importantly when comparing it to the previous version of the ePub viewer I do see significant improvements especially in the Arabic books which are now correctly aligned RTL.

Nice! Glad to learn RTL was improved with that.

> Actually @GeorgesStavracas I am not able to see the image in the minimal reproducer file that you provided, could you check that and reupload it? It's not displayed neither in the build containing your code changes or in a previous build of Kolibri...

Interesting. I definitely could see the ePub file rendered differently between `develop` and this branch. In any case, as per feedback from @bjester, I'm removing the commit that was supposed to fix that. We've contacted the publisher of the original ePub file to see how we can handle that, but at least for this pull request, this reproducer can be ignored. We'll figure it out separatedly.

2023-05-17 17:50 UTC, radinamatic approved these changes
Manual QA of the RTL alignment fix passes, great improvement! 👏🏽 💯 :shipit:

2023-05-22 21:23 UTC, bjester approved these changes

2023-05-23 14:06 UTC, merged