Lesson size functionality cleanup
learningequality/kolibri pull request #10720
Opened 2023-05-18 19:14 UTC by rtibbles

## Summary
* Cleans up lesson size fetching to always pass the `classId` as the collection get parameter.
* Adds `id` filter to be able to fetch just the size information for a single lesson
* Updates vuex state storing of lesson sizes to be parallel to quiz sizes by storing it directly on the lesson data in the vuex modules
* Does some fly by cleanup of `forEach` to `for... of`
* Removes hardcoded `--` string and uses `KEmptyPlaceholder` for cases where a blank should be shown.
* Cleans up some residual active/is_active issues

## References
Fixes #10500 
Closes #10501 

## Reviewer guidance
#10500:
[Screencast from 05-18-2023 12:12:09 PM.webm](https://github.com/learningequality/kolibri/assets/1680573/1b9663d6-2b81-4083-a75a-29b6d10cccbd)

#10501:
[Screencast from 05-18-2023 12:13:20 PM.webm](https://github.com/learningequality/kolibri/assets/1680573/8230796a-0613-4c99-b8d6-0d008d6ef747)

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2023-05-19 13:30 UTC, pcenov requested changes, later dismissed
Hi @rtibbles, looks line there is one more base to cover: in Coach > Plan > Lesson the Size value is always displayed as 'NaN B'. This is also valid for the modal window which is displayed when there's a LOD:

Video:

https://github.com/learningequality/kolibri/assets/79847249/81f6eb4d-21fc-4500-8c6f-96c2b4abb006



Screenshot:

![2023-05-19_16-11-40](https://github.com/learningequality/kolibri/assets/79847249/f5c3aeb2-5eb1-4357-bb46-e7b5f8761b37)

2023-05-19 14:32 UTC, marcellamaki reviewed
Code read through looks good - the cleanup makes it much, much easier to read. I can do one more pass after the code is updated for the code that Peter mentioned.

2023-05-19 14:32 UTC, marcellamaki commented on kolibri/plugins/coach/assets/src/modules/classSummary/index.js
> +      if (Object.keys(store.state.lessonMap).length > 0) {
this is a much better place to put this condition!

2023-05-19 14:32 UTC, marcellamaki commented on kolibri/plugins/coach/assets/src/views/plan/LessonsRootPage/index.vue
> +            }, 0);
this is a nice cleanup

2023-05-22 17:28 UTC, rtibbles commented
But `NaN B` is my favourite grandmother!

I'll clean this up - must be one more edge case lurking.

2023-05-22 23:36 UTC, rtibbles commented
@pcenov when you confirm the final fix here, can you also verify that it fixes this issue? #10617

2023-05-23 03:05 UTC, rtibbles commented
This should now be displaying properly, as shown here:
![image](https://github.com/learningequality/kolibri/assets/1680573/24c3d746-3c59-4a64-b349-a188f0af9d02)

2023-05-23 10:11 UTC, pcenov commented
Hi @rtibbles, I confirm the final fix here. I've reopened one [previously reported issue](https://github.com/learningequality/kolibri/issues/10236) which I was able to identify while regression testing everything.

2023-05-23 13:51 UTC, rtibbles commented
I will do the final fix for this issue within this PR too.

2023-05-23 21:01 UTC, rtibbles commented
This now also fixes #10236:
![image](https://github.com/learningequality/kolibri/assets/1680573/4e5b7d5c-74c2-4be6-a2b1-b212dd60a85c)

2023-05-24 16:35 UTC, radinamatic commented
Regression mentioned in #10236 is fixed, but if you look closely at the lesson sizes right after the modal is closed, you can still see a brief flash of NaN... 

https://github.com/learningequality/kolibri/assets/1457929/4a26e475-b496-4523-aa8e-d42e2846658a

![lesson-visibility2 mp4 - VLC media player_001](https://github.com/learningequality/kolibri/assets/1457929/5d76a276-6e75-41ad-a221-104985a2b0f7)

2023-05-24 16:36 UTC, rtibbles commented
I deliberately didn't fix these loading issues to avoid scope creep into this issue: https://github.com/learningequality/kolibri/issues/10729

2023-05-24 16:39 UTC, radinamatic approved these changes
Manual QA passed, good to go! 🎉 💯 :shipit:

2023-05-24 23:00 UTC, merged