Relax discovery permissions in SOuD devices
learningequality/kolibri pull request #10983
Opened 2023-07-14 18:26 UTC by jredrejo

## Summary
Unrestrict some of the Subset of Users Device permissions to discover network devices. 
After one device has one or more users merged to another facility, this is considered a SoUD. Any remaining FacilityUser must have the ability to explore the network to move to another facility.

## References
Closes: #10661

## Reviewer guidance
Any concern with this less restricted conditions to be able to explore the network in SoUD devices?
Check the issue described in #10661 is fixed now.

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2023-07-14 21:14 UTC, rtibbles commented
Note, that this is also required to allow remote browsing to happen as intended.

2023-07-14 21:14 UTC, rtibbles reviewed
Code changes look good - QA approval should be good to merge.

2023-07-17 14:20 UTC, pcenov requested changes
Hi @jredrejo for some reason I am always getting the following error when merging or creating a user: 'Locally integrating received data: MorangoError'. When I refresh the users page on the target facility I can see that a new account is created correctly though:

https://github.com/learningequality/kolibri/assets/79847249/570a9f86-b69e-44b6-bed8-f7c2ec9a872d

Logs and DB: [LogsAndDB.zip](https://github.com/learningequality/kolibri/files/12070247/LogsAndDB.zip)

2023-07-17 15:11 UTC, jredrejo commented
> Hi @jredrejo for some reason I am always getting the following error when merging or creating a user: 'Locally integrating received data: MorangoError'. When I refresh the users page on the target facility I can see that a new account is created correctly though:
> 
>  2023-07-17_17-08-15.mp4 
> Logs and DB: [LogsAndDB.zip](https://github.com/learningequality/kolibri/files/12070247/LogsAndDB.zip)

that's the problem https://github.com/learningequality/kolibri/pull/10982 fixed, if you can test it merging this PR in develop it should have the problem solved

2023-07-17 16:00 UTC, rtibbles commented
@pcenov @jredrejo has rebased this onto latest develop, so that issue should be resolved now.

2023-07-18 09:45 UTC, pcenov commented
Thanks @jredrejo this is working correctly and as described now. The issue reported in https://github.com/learningequality/kolibri/issues/10661 is also fixed.

2023-07-18 10:23 UTC, pcenov approved these changes

2023-07-18 10:25 UTC, merged