Fix mastery log after ending quiz
learningequality/kolibri pull request #11050
Opened 2023-08-02 18:29 UTC by jredrejo

## Summary
When the user clicks to send a finished quiz:

- complete the frontend PUT to add final progress
- avoid backend rejecting the PUT if a previous trackprogress has already marked the quiz as completed

## References
Closes: #11045

## Reviewer guidance
Do the steps described at #11045

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2023-08-02 18:34 UTC, rtibbles requested changes
We should not be removing the permissions check here. It seems that the issue here is that the frontend is sending a superfluous request, so we should address that.

2023-08-02 19:17 UTC, jredrejo commented
> We should not be removing the permissions check here. It seems that the issue here is that the frontend is sending a superfluous request, so we should address that.

Frontend is doing two requests:
- One when the resource/quiz is complete
- A second one when the user says to send the quiz

First one mark the quiz as completed, so keeping the permission that checks `_check_quiz_log_permissions` will return always `PermissionDenied`

Checking _check_quiz_log_permissions I don't see its sense for this second request. Permissions to check if the masterylog exists and the user has access are not been removed.
What would be the alternative?

2023-08-02 22:25 UTC, rtibbles commented
The issue here appears to be that the quiz is being marked as completed too early - rather than it requiring the second PUT to set progress equal to 1, this is happening in the prior request.

However, this is likely a result of debouncing in the saving of the first request - so by the time it has registered, the updated progress being set to 1 has already been saved into the composable and can be sent along with the first request.

There are two ways we can handle this. We can let the error continue to happen and instead catch it here: 
https://github.com/learningequality/kolibri/blob/release-v0.16.x/kolibri/plugins/learn/assets/src/views/ExamPage/index.vue#L456

Or... we can intercept when we are making the empty request you diagnosed, and just resolve the request immediately, so if we get to here: https://github.com/learningequality/kolibri/blob/release-v0.16.x/kolibri/plugins/learn/assets/src/composables/useProgressTracking.js#L356 and `Object.keys(data).length === 0` then we are not actually sending any data to the backend, in spite of us being at this point because we are trying to force a save. In this case, we can just return the current saving promise and not create a new one.

2023-08-03 17:31 UTC, jredrejo commented
Done this way

> Or... we can intercept when we are making the empty request you diagnosed, and just resolve the request immediately, so if we get to here: https://github.com/learningequality/kolibri/blob/release-v0.16.x/kolibri/plugins/learn/assets/src/composables/useProgressTracking.js#L356 and `Object.keys(data).length === 0` then we are not actually sending any data to the backend, in spite of us being at this point because we are trying to force a save. In this case, we can just return the current saving promise and not create a new one.

2023-08-03 18:09 UTC, rtibbles approved these changes

2023-08-03 18:09 UTC, merged