stopping a circular loader when there is no data
learningequality/kolibri pull request #11070
Opened 2023-08-08 06:12 UTC by AllanOXDi

## Summary

…

## References

…

## Reviewer guidance

…

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2023-08-14 15:55 UTC, nucleogenesis requested changes
I think we should make use of the existing loading pattern for tables here and be sure that whether we're loading or not is being determined wherever the API call that the user is waiting on is executed.

2023-08-14 15:55 UTC, nucleogenesis commented on kolibri/plugins/learn/assets/src/my_downloads/views/MyDownloads.vue
> +      </div>
One thing that might be simpler is to remove this altogether and to use the `emptyMessage` and `dataLoading` props on `CoreTable` inside of the `DownloadsList` component. You could then pass your `loading` property into `DownloadsList :loading` and then pass that on to `CoreTable`.

Also, you'll probably have to pass the string down as well in a separate prop in DownloadsList to pass to `emptyMessage`.

[Here is one example of this in use](https://github.com/learningequality/kolibri/blob/5a4c7c497d90b1d7e3772e0dfa05467228518316/kolibri/core/assets/src/views/UserTable/index.vue#L20)

2023-08-14 15:55 UTC, nucleogenesis commented on kolibri/plugins/learn/assets/src/my_downloads/views/MyDownloads.vue
> +      },
I think that if you pass the `loading` prop as I mentioned above, then you'll probably not need anything like this. 

In this case, we're just pretending to be loading something for 1 second which would probably not be particularly effective for slower connections as the second could pass, set isLoading to false, but still actually be loading data.

`isLoading` ultimately needs to be set/unset wherever the API request is being made to fetch the list of downloads -- possibly you could actually just use the `loading` function that is imported from the `useDownloadRequests` composable module and pass that straight into the downloads list component.

2023-08-15 14:32 UTC, akolson commented on kolibri/plugins/learn/assets/src/my_downloads/views/MyDownloads.vue
> +      </div>
I agree 💯

2023-08-15 14:34 UTC, akolson commented on kolibri/plugins/learn/assets/src/my_downloads/views/MyDownloads.vue
> +      },
True, the loading widget should be an actual representation of the loading state

2023-08-15 14:38 UTC, akolson requested changes
Hi @AllanOXDi, As already pointed out by Jacob during his review, there is need to align the loading code to match the actual loading state of the data being loaded.

2023-08-23 15:08 UTC, AllanOXDi commented
Closing this PR as the issue seems to be fix in a separate PR

2023-08-23 15:08 UTC, closed without merging