Garbage Collection Integration for Morango SyncSessions
learningequality/kolibri pull request #11101
Opened 2023-08-15 14:49 UTC by ozer550

## Summary
- Added CleanUpTaskOperation for queuing cleanupsync task passing relevant attributes.
- Cleanupsync Task to call cleanupsync command recently added in morango
- Override the command according to #8238  

## Reviewer guidance
- Run the command using KOLIBRI_HOME=$(mktemp -d) kolibri manage cleanupsyncs
- Create two devices and try syncing, post_transfer hook gets triggered.

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

closes #8238

2023-08-15 15:55 UTC, akolson commented on kolibri/core/auth/management/commands/cleanupsyncs.py
@ozer550 , I am not sure why this file appears as a newly added file as we already have it in morango

2023-08-15 15:58 UTC, bjester commented
Lets make sure to include the morango upgrade in this. We have yet to actually release it, so I will help get that sorted out later this week.

2023-08-15 18:54 UTC, ozer550 commented on kolibri/core/auth/management/commands/cleanupsyncs.py
Hi @akolson, We are creating this file to override the existing morango's cleanupsync command so that we can refactor the command according to Kolibri's requirement i.e we throw an error when the device is unprovisioned. Slight changes in the file I missed to call the handle method of the cleanupsync command from morango.

2023-08-15 19:25 UTC, akolson commented on kolibri/core/auth/management/commands/cleanupsyncs.py
Ahh, I see. Thanks for clarification

2023-09-28 19:17 UTC, bjester commented
@ozer550 when you have a chance, could you upgrade morango to 0.6.17 here? That will complete this and ready it for merge!

2023-10-18 23:02 UTC, rtibbles commented
Looks like this has been rebased to include the latest morango update - so I think this is ready to go?

2023-10-19 14:02 UTC, bjester commented
> Looks like this has been rebased to include the latest morango update - so I think this is ready to go?

It's pretty much there, but I didn't get a chance to talk to with Prathamesh about it during our sync yesterday. @ozer550 I think the instance ID filtering is the opposite of what it should be.

When we target sync sessions for clean up, if `is_server` is `True` on the completed sync, we would want to find all sync sessions with a matching instance `client_instance_id`. The `is_server` is in reference to the current device, so extracting the instance from `client_instance_id` would produce the other device's instance ID

2023-11-07 20:08 UTC, bjester commented on kolibri/core/auth/management/commands/cleanupsyncs.py
> +        return super().handle(*args, **options)
```suggestion
        return super(Command, self).handle(*args, **options)
```

2023-11-07 20:12 UTC, bjester requested changes
@ozer550 The logic for which instance ID to use is still incorrect. Please take a closer, careful look at it. Could you also update the `expiration` to `1`? I'm starting to think that `0` is a bad idea

2023-11-10 18:10 UTC, bjester approved these changes
:rocket:

2023-11-10 18:31 UTC, merged