Set full name when creating a remote learner account.
learningequality/kolibri pull request #11257
Opened 2023-09-15 23:29 UTC by rtibbles

## Summary
* Ensures that the full_name entered is actually passed through to the backend and then to the public sign up endpoint

## References
Fixes #11188

## Reviewer guidance
[Screencast from 09-15-2023 04:26:26 PM.webm](https://github.com/learningequality/kolibri/assets/1680573/b0adc436-e1f9-4ed2-8f83-439b7d2a5cbe)

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2023-09-19 16:29 UTC, jredrejo requested changes
I have tested it and it does not work for me. I think this PR is missing changes in the SignUpViewSet class, at https://github.com/learningequality/kolibri/blob/release-v0.16.x/kolibri/core/auth/api.py#L763-L766
These changes do send the information from the device that's being setup, but the remote server only accepts password/facility/username, not full_name

Could it be you forgot to commit that change?

2023-09-21 15:49 UTC, rtibbles commented
Odd - no, all my changes are committed. The line you are pointing to is just for logging in, and only used for the internal signup API, not the public one.

2023-09-21 15:57 UTC, jredrejo commented
> Odd - no, all my changes are committed. The line you are pointing to is just for logging in, and only used for the internal signup API, not the public one.

ah, I did a quick look to the code and saw that, I didn't check the `authenticated` function there. Being the superclass of the public class and seeing those fields looked suspicious :( 
 
So, is there any condition to be checked in the remote facility? In my tests the remote facility was running 0.16b5 in a RPi while the new facility that was being setup was running on this branch code in my laptop. The username was _manolo_  and the full name was not there after typing it when creating it.

![image](https://github.com/learningequality/kolibri/assets/1008178/4ef3a0f7-d240-4d50-815b-e788d3c340e9)

If there's nothing special needed in the setup I'll try to debug it.

2023-09-21 16:57 UTC, rtibbles commented
I guess the only difference is that the server that I was creating the user on was running the code from this PR as well - but it does seem like that should be unnecessary, given that I've not made any changes to the public API code.

2023-09-21 18:05 UTC, jredrejo approved these changes
Sorry for the noise, somehow pressing tab to checkout I had tested this in a branch called` lod-import-onboarding` instead of the one for this PR.  :blush: 
As you said, it was odd because this code is not complex at all and if the backend code for the remote server was ready to go, there were not any reason for this to fail

2023-09-21 23:40 UTC, merged