TextTruncator.vue is totally removed from the entire codebase
learningequality/kolibri pull request #11288
Opened 2023-09-22 15:50 UTC by yash1378

## Summary

…

## References

Closes https://github.com/learningequality/kolibri/issues/11287

## Reviewer guidance

…

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2023-09-22 15:56 UTC, MisRob commented
Hi @yash1378, thanks! Could you please follow PR guidelines and fill in the sections at least briefly? So that any team member can review and understand. Thank you.

2023-09-22 15:59 UTC, yash1378 commented
> Hi @yash1378, thanks! Could you please follow PR guidelines and fill in the sections at least briefly? So that any team member can review and understand. Thank you.

ok mam i will take care of that

2023-09-25 15:34 UTC, LianaHarris360 requested changes
Thanks for working on this! Besides one small correction, I can confirm that the `TextTruncator` component has been removed from the codebase.

2023-09-25 15:34 UTC, LianaHarris360 commented on kolibri/core/assets/src/core-app/apiSpec.js
> +      // TextTruncator,
All instances of `TextTruncater` in this file should be removed entirely, rather can commented out, since this component is deleted and will no longer be used :)

2023-09-25 16:02 UTC, yash1378 commented
> Thanks for working on this! Besides one small correction, I can confirm that the `TextTruncator` component has been removed from the codebase.

done the changes as required

2023-09-25 18:04 UTC, LianaHarris360 approved these changes

2023-09-25 18:04 UTC, merged