Replaced KResponsiveWindow mixin by useKResponsiveWindow composable - …
learningequality/kolibri pull request #11365
Opened 2023-10-07 09:19 UTC by FireSuperior482

…Media Player plugin

## Testing checklist

- [X] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added.
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2023-10-08 22:37 UTC, rtibbles requested changes
One property missed!

2023-10-08 22:37 UTC, rtibbles commented on kolibri/plugins/media_player/assets/src/views/MediaPlayerIndex.vue
> +      const { windowIsSmall } = useKResponsiveWindow();
The `windowIsPortrait` property is also used, so must be destructured here and returned from the setup method.

See here: https://github.com/learningequality/kolibri/blob/release-v0.16.x/kolibri/plugins/media_player/assets/src/views/MediaPlayerIndex.vue#L207

2023-10-09 13:51 UTC, FireSuperior482 commented on kolibri/plugins/media_player/assets/src/views/MediaPlayerIndex.vue
> +      const { windowIsSmall } = useKResponsiveWindow();
I have made the necessary changes; please check it once.

2023-10-09 17:40 UTC, rtibbles approved these changes
This doesn't cause any errors in manual testing, and is the change I expect.

2023-10-09 17:40 UTC, merged