Video transcripts flow based on windowBreakpoint
learningequality/kolibri pull request #11385
Opened 2023-10-11 07:10 UTC by nucleogenesis

## Summary

On smaller screens the video transcript would overlay the video player. This was because the position was set to `absolute` which works just fine on larger screens, but it didn't flow underneath the video player properly because of it. 

This introduces a `cssPosition` computed property to set the inline styles on the root tag so that the `position` is set to make things work properly.

BEFORE:

[before.webm](https://github.com/learningequality/kolibri/assets/6356129/9fb208cd-7577-4c62-9f38-294b20250344)

AFTER (devtools errors unrelated 😄 ):

[after.webm](https://github.com/learningequality/kolibri/assets/6356129/444395b9-fced-462c-a653-be13188ed7a0)

## References

Fixes #11375 

## Reviewer guidance

Watch a video that has a transcript and open the transcript. You should be able to see the video and the transcript at all screen sizes. When the screen shrinks, at one point it should smoothly transition to where the transcript is beneath the video player when smaller or to the side of it when larger.

2023-10-11 16:37 UTC, rtibbles reviewed
Code changes look good - would be good if @pcenov can test this across all breakpoints/screen orientations just to confirm the fix - but from the video it looks right.

2023-10-16 13:56 UTC, akolson reviewed
Changes look correct to me! Thanks @nucleogenesis

2023-10-16 15:29 UTC, pcenov requested changes
Hi @nucleogenesis  when going slowly from about 926 to 840 pixels I am still able to replicate the original issue (Chrome, Safari on Mac):

https://github.com/learningequality/kolibri/assets/79847249/4f253ba7-38c2-409d-9b36-db09d8f9ee97

It seems that this is observed when you are in portrait mode with more vertical space.

With less vertical space the transcript gets squished to the left side:

![2023-10-16_18-27-18](https://github.com/learningequality/kolibri/assets/79847249/e6583fec-7a3c-42cd-bb8b-e8ed0a53e64b)

2023-10-17 15:54 UTC, nucleogenesis commented
@pcenov thanks Peter -- I'll review again today and ping again when ready for re-review

2023-10-17 21:57 UTC, nucleogenesis commented
@pcenov please give it another look - I realized a simpler approach altogether that ensures consistency throughout

2023-10-23 14:51 UTC, pcenov approved these changes
Hi @nucleogenesis sorry for the late response - yes I confirm this is working perfectly fine now! Thank you!

2023-10-23 15:26 UTC, merged