Replaced KResponsiveWindow to useKResponsiveWindow
learningequality/kolibri pull request #11414
Opened 2023-10-14 07:37 UTC by ShivangRawat30

## Summary

This PR replaced the `KResponsiveWindow` to `useKResponsiveWindow` in (kolibri/plugins/perseus_viewer)

## References

#11329 

## Reviewer guidance

…

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2023-10-16 02:06 UTC, im-NL commented
@ShivangRawat30 For the failling linting check, run ``yarn run lint-frontend:format`` in your cli, and then push the file you've edited again, the changes will be reflected here automatically. The linting checks should then pass.

2023-10-17 15:15 UTC, LianaHarris360 requested changes
The changes look correct, once the `lint-frontend:format` command is ran in your cli and the linting checks pass, this PR can be approved.

2023-10-19 12:55 UTC, ShivangRawat30 commented
@LianaHarris360 done

2023-10-19 14:01 UTC, LianaHarris360 approved these changes

2023-10-19 14:02 UTC, merged