Replace KResponsiveWindow mixin by useKResponsiveWindow composable
learningequality/kolibri pull request #11474
Opened 2023-10-29 17:14 UTC by KshitijThareja

## Summary

This PR replaces `KResponsiveWindow` with `useKResponsiveWindow` in Setup Wizard plugin.

## References

This PR aims to resolve issue #11330 

## Reviewer guidance

…

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2023-11-05 07:28 UTC, KshitijThareja commented
@nucleogenesis @marcellamaki Is the updated code fine or are there any changes required in this PR?

2023-11-10 12:40 UTC, MisRob commented
Hi @KshitijThareja, thank you for your contribution! We will definitely follow-up, there's been lots of pull requests in our queue.

2023-11-10 16:52 UTC, marcellamaki requested changes
Hi @KshitijThareja - thanks so much for working on this PR. You're off to a good start. The removal of the responsiveWindowMixin and using the composable in the setup is right. However,  you're not quite there yet. 

1. You need to make sure you are importing the composable in both places 
2. You need to make sure that your `consts` that you are using in the setup match what is actually needed by the file. Take a look at the options in the composable (you can refer to the original issue for more details about the design system if you need it) and what is needed in the file. Then make sure they align. (For example, you have imported `windowIsPortrait` in both files. Is that used anywhere? Don't import things that are not used, and _do_ import everything that is needed). 

Let me know if you have further questions, and thanks again for your work on this.

2023-11-10 19:02 UTC, KshitijThareja commented
@marcellamaki thanks for your review. I understand I made some mistakes in the code. I've corrected everything and pushed the changes. 
Again, thanks for pointing it out :)

2023-11-11 04:24 UTC, KshitijThareja commented
@marcellamaki Is there any specific reason for the DMG build to fail?

2023-11-13 15:21 UTC, marcellamaki approved these changes
Hi @KshitijThareja - we recently updated the DMG github action on our end, so I re-ran the job and that resolved it. Thank you also for the updates you made! Looks good to me. We appreciate your contribution to Kolibri 🎉

2023-11-13 15:21 UTC, merged

2023-11-14 17:26 UTC, KshitijThareja commented
Thanks 😄 @marcellamaki