Changed KResponsiveWindow to useKResponsivewindow in Slidehow Viewer …
learningequality/kolibri pull request #11534
Opened 2023-11-15 16:34 UTC by moweiss

## Summary
This PR changes the KResponsiveWindow to useKResponsiveWindow in Slideshow Viewer Plugin
…

## References
https://github.com/learningequality/kolibri/issues/11328
…

## Reviewer guidance
...

…

----

## Testing checklist

- [X ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [X] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2023-11-17 18:40 UTC, LianaHarris360 requested changes
Thank you for working on this! The changes are as requested, but the failing test will need to be fixed before this pr can be approved. You can do this by manually running the auto-formatters with `yarn run lint-frontend:format`, as mentioned in the [Kolibri developer documentation](https://kolibri-dev.readthedocs.io/en/develop/getting_started.html#linting-and-auto-formatting:~:text=kolibri%20manage%20generateuserdata-,Linting%20and%20auto%2Dformatting,-Manual%20linting%20and), then updating this pull request with those changes. Additionally, this pr should reference and close issue `#11331` rather than `#11328`

2023-12-07 14:34 UTC, MisRob commented
Hi @moweiss, do you need any support with finishing the PR?

2023-12-15 08:04 UTC, MisRob commented
@moweiss @LianaHarris360 I run linter so we can proceed to merge. Also, this is the last sub-issue of https://github.com/learningequality/kolibri/pull/11534 so it will be closed too. Thanks both!

2023-12-15 15:18 UTC, LianaHarris360 approved these changes

2023-12-15 15:19 UTC, merged