Fix - Video player height
learningequality/kolibri pull request #11566
Opened 2023-11-29 14:35 UTC by iskipu

This PR fixes https://github.com/learningequality/kolibri/issues/9501 issue. 

Video player height scss corrected.

Before: 
![image](https://github.com/learningequality/kolibri/assets/143542192/d4c9db27-7f67-424a-bfc0-ba1088a54bfe)

After:
![image](https://github.com/learningequality/kolibri/assets/143542192/4036171c-f9b4-49b3-bce0-9e09d86a004e)

This is my first ever PR 😅

2023-11-29 15:33 UTC, MisRob commented
Oh great! This has been pretty troublesome issue.

2023-11-29 15:34 UTC, MisRob commented
@pcenov Could you please give it a try in Microsoft Edge?

2023-11-29 16:33 UTC, bjester commented
This needs tested with a transcript in mobile portrait view, or generally wherever `$video-player-max-vh` is used. For example: https://github.com/learningequality/kolibri/pull/11566/files#diff-a77e3ee024e78817accbb7d084a9848fae034962ad9a2c1d29d143ffee0b6199L24

2023-11-29 17:33 UTC, MisRob commented
@bjester Thanks, makes sense. @pcenov Thorough testing on various screen sizes would be appreciated.

2023-11-30 12:11 UTC, pcenov approved these changes
Thank you @iskipu - I confirm that the issue reported in https://github.com/learningequality/kolibri/issues/9501 is fixed now and I didn't observe any regressions in the supported browsers including in mobile view with transcript.

2023-11-30 15:47 UTC, MisRob requested changes, later dismissed
Thank you @pcenov. @iskipu congratulations on your first contribution! The change makes sense to me, in the previous version, the browser complains about unsupported value.

There's one problem now with `$transcript-wrap-height: $video-player-max-vh - #{$video-player-height-vw};` variable which is used as `padding-bottom` here:

![Screenshot from 2023-11-30 16-29-21](https://github.com/learningequality/kolibri/assets/13509191/ed947c96-dbae-440c-a480-e8333092ac52)

and as `height` here:

![Screenshot from 2023-11-30 16-37-47](https://github.com/learningequality/kolibri/assets/13509191/09c9e01b-e56e-4c34-a35a-5785ecc6de83)

See the invalid property value warnings.

This is causing the following regression with the transcript:

| Regression | Expected (notice that transcript has its own scrollbar) |
| --------------- | ---------------------------------------------------------------------- |
| ![regression](https://github.com/learningequality/kolibri/assets/13509191/47e5d860-27d1-4ad4-be9f-756b8b9d1ba4) | ![expected](https://github.com/learningequality/kolibri/assets/13509191/a902fffb-efd9-4402-8149-bbea145703b5) |

It is important to be able to see transcript and the video at the same time so we need to update `$transcript-wrap-height` too. I think you could use the same approach.

You can test it out on "Intro to addition" video in the "Kolibri QA channel" which you can import by going to Device > Channels > Import > Kolibri Studio > Import with token > `nakav-mafak` token

I think we can merge after this is fixed. Anyways, really good work! We've had this issue open for more than a year and it has quite a significant impact on user experience. I appreciate you took time to dig into what was the problem.

2023-11-30 15:53 UTC, MisRob commented
@iskipu I just found out that this isn't regression of this particular PR, as I could reproduce it on the `release-v0.16.x` too. It's broken but before it was broken too, just in a bit another way :) If you're interested in fixing it, we will appreciate it. I think the other calculation would need to be updated to your update anyways. But no problem if you don't have more bandwith. We can also co-author this PR and finish it. It's up to you! This will be valuable in any case. Let us know.

2023-11-30 17:16 UTC, iskipu commented
> There's one problem now with `$transcript-wrap-height: $video-player-max-vh - #{$video-player-height-vw};`

Hi @MisRob, I noticed this too but i thought this is not relevant to the Issue i tagged, and i assumed that i had to open a new issue before solving this 😅. Now i fixed it as you suggested

2023-11-30 18:24 UTC, MisRob commented
@iskipu Oh good, thanks for your flexibility. I assume it will be fine now, but let us review and test one more time in the next several days.

2023-12-01 11:17 UTC, pcenov commented
Hi @MisRob, initially when testing this I was looking mainly to verify that the issue which I had reported here https://github.com/learningequality/kolibri/issues/9501 is fixed. Thank you for comparing to the 0.15 version and identifying the issue with the video transcript. Now this is fixed but on closer inspection there is one more thing - when viewing in mobile portrait if I click the fullscreen option then there's some black padding under the video player, while this is not the case in 0.15 - wondering whether this can also be fixed here as a final touch or I should report it separately:

https://github.com/learningequality/kolibri/assets/79847249/5dbf11a5-06fb-4300-bddf-5f8de2412413

2023-12-01 15:30 UTC, iskipu commented
hi @pcenov what is the expected behaviour in this case when the screen is toggled to full screen ? just do nothing ?

2023-12-01 16:00 UTC, pcenov commented
Hi @iskipu here's a video of the behavior in Kolibri 0.15.12:

https://github.com/learningequality/kolibri/assets/79847249/602008b2-ca4d-4978-a8ce-c0b279dbbd05

2023-12-01 18:23 UTC, MisRob commented
Thank you, @pcenov.

> Now this is fixed but on closer inspection there is one more thing - when viewing in mobile portrait if I click the fullscreen option then there's some black padding under the video player, while this is not the case in 0.15 - wondering whether this can also be fixed here as a final touch or I should report it separately

I'd say it depends if that problem was present before this pull request on 0.16 branch or no. If yes, then changes here are not related. @iskipu you are welcome to look into it but also no pressure, we can also take time to confirm at first whether it's a regression caused here or no.

2023-12-01 21:03 UTC, iskipu commented
hi @pcenov & @MisRob, created a new commit to fix the issue pointed by @pcenov  now the full screen works fine with transcript please check and let me know if there are any other issues.

offtopic question: 
i am not able to understand where to find some of the imports in the file system

example : 

>   import commonCoreStrings from 'kolibri.coreVue.mixins.commonCoreStrings';`

i figured out it was referencing this path 

> kolibri/core/assets/src/mixins/commonCoreStrings.js

but the path which it is referencing is very unintuitive, so how  would i know which file path the import is referencing

2023-12-04 09:36 UTC, pcenov requested changes
Hi @iskipu, unfortunately this is still the same when running the latest asset:

https://github.com/learningequality/kolibri/assets/79847249/9b0d0f8f-5e9f-43e8-b752-189b7093b002

I tested in both Chrome on PC with cleared cache and cookies and in mobile Chrome on an Android phone. Can you double check?

2023-12-04 09:50 UTC, iskipu commented
@pcenov 

I dont find any issue 
![image](https://github.com/learningequality/kolibri/assets/143542192/7fb7c8b9-020a-4ad2-973a-fc139d57f37e)

Not full screen :

![image](https://github.com/learningequality/kolibri/assets/143542192/b6b8c233-9b7e-4844-81fa-520faa5d9798)


Full screen:

![image](https://github.com/learningequality/kolibri/assets/143542192/041813c5-f0e9-48b0-8c2f-0d5b329b0501)

2023-12-04 11:12 UTC, pcenov commented
Ok, thanks @iskipu lets wait for @MisRob to have a look as I am testing using the latest build artefacts from here: https://github.com/learningequality/kolibri/actions/runs/7049842538 and apparently your changes are not there for some reason.

2023-12-04 14:29 UTC, MisRob commented
Thanks @iskipu and @pcenov.

@pcenov I noticed that checks were waiting to be run (their run needs to be approved after every change on a PR from a first-time contributor) so I think it's quite possible you tested the previous build. I run them so now it should be up to date.

2023-12-04 14:32 UTC, MisRob commented
@pcenov if the last issue is fixed, could you please make one final run of all important scenarios? The latest commit may affect some areas that you've tested before.

2023-12-04 14:34 UTC, MisRob commented
@iskipu In regards to code, the latest changes make sense to me.

2023-12-05 10:27 UTC, pcenov approved these changes
Thank you @iskipu - I confirm that going to full screen is working correctly now. No other issues observed while regression testing in all of the supported browsers plus the Mac and Android apps. Good to go @MisRob.

2023-12-05 15:09 UTC, bjester approved these changes

2023-12-05 15:10 UTC, merged

2023-12-07 12:54 UTC, MisRob commented
Thanks @iskipu, you did lots of work here