Don't require channel name in content tasks API
learningequality/kolibri pull request #11603
Opened 2023-12-07 22:41 UTC by dbnicholson

## Summary

It's nice to include the channel name in the tasks extra metadata so that it can be shown in the frontend, but often the caller only has the channel ID and is required to supply a bogus name. Instead, default to the empty string and let anyone inspecting the task decide how they want to deal with a missing name.

## References

None, although we often have to make use bogus names in kolibri-explore-plugin during data import since we only have a content manifest, and that only contains channel IDs.

## Reviewer guidance

1. Start a server in dev mode
2. Create a superuser
3. Make a post request to `/api/tasks/tasks/` to import a channel with data like `{"type": "kolibri.core.content.tasks.remotechannelimport", "channel_id": "<channel_id>"}`

Currently that will error as invalid tasks data. After the change, it will be inspected and the generated job will have an empty `channel_name` in the `extra_metadata` field.

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2023-12-08 19:00 UTC, dbnicholson commented
I missed adding `allow_blank=True` in the field. If the default is an empty string, the caller should be allowed to supply an empty string.

2024-01-02 16:21 UTC, jredrejo requested changes

2024-01-02 16:21 UTC, jredrejo commented on kolibri/core/content/tasks.py
> +    channel_name = serializers.CharField(default="", allow_blank=True)
For most of the cases (different forms of import, mainly) I think this is fine, but I see `DeleteChannelValidator` uses a class that inherits from `ChannelValidator`. I think that, as a safety measure, it's good to have both the `id` and the `name` to confirm the deletion of a channel.

2024-01-17 01:25 UTC, rtibbles commented
No clear need for this from our side, so closing for now.

2024-01-17 01:25 UTC, closed without merging

2024-01-18 13:23 UTC, MisRob commented
@dbnicholson To prevent back and forth, I'd recommend opening an issue at first next time. Thank you for working on Kolibri.