Update ExamSerializers according to v3 model
learningequality/kolibri pull request #11674
Opened 2023-12-26 07:04 UTC by ozer550

## Summary
- Update the serializers to validate the sections in the quiz.
- Update usage of the Exam instances according to v3.
- Add tests for the serializers.
- Refactor existing tests according to new version of Exam.
- Add Validation in the frontend for Quiz object. 

## References
closes #11580

## Reviewer guidance
- Change `debug=true` on `function useQuizCreation ` in the code.
- Go to Quiz section.
- Save the quiz.
- Exam model is created.

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2023-12-26 07:07 UTC, ozer550 commented on kolibri/core/exams/test/test_exam_api.py
> +    def test_quiz_section_with_no_resource_pool(self):
Was curious about the resource pool and if it's required!

2023-12-27 18:49 UTC, nucleogenesis approved these changes
One quick change requested to update a docstring -- otherwise, this all looks good to me. 

With the docstring updated this can be merged.

2023-12-27 18:49 UTC, nucleogenesis commented on kolibri/plugins/coach/assets/src/composables/useQuizCreation.js
> +  function initializeQuiz(collection) {
Could you add a `@param {string} collection - The collection (aka current class ID) to associate the exam with` to the doc string above here?

2024-01-02 16:28 UTC, rtibbles requested changes
I am fairly sure that this will break horribly if we attempt to load an exam object from the database that predates the v3 model.

Did you test this scenario? It would be good to retain backend tests for that case as well to give us assurance (noting that the mapping between versions happens in the frontend).

2024-01-04 00:26 UTC, rtibbles requested changes
I think there are still two places here where breakage will happen.

2024-01-04 00:26 UTC, rtibbles commented on kolibri/core/exams/models.py
> -        yield (question_source["exercise_id"], None)
This function will still fail for pre-v3 exams.

2024-01-04 00:26 UTC, rtibbles commented on kolibri/core/exams/serializers.py
> +            first_question_source = data["question_sources"][0]
Seems like this conditionality could just be done based on the `data_model_version` rather than this sniff test?

2024-01-04 00:26 UTC, rtibbles commented on kolibri/core/exams/models.py
> +    def get_questions(self):
As will this.

2024-01-09 21:17 UTC, rtibbles approved these changes

2024-01-09 21:17 UTC, merged

2024-01-09 21:17 UTC, rtibbles commented
Docs failure is unrelated to this PR, merging.