Hide modal when a token has multiple channels
learningequality/kolibri pull request #11686
Opened 2024-01-03 10:50 UTC by jredrejo

## Summary
When a token results in more than one channel, modal to insert the token didn't dissappear. This PR fixes it.

## References
Closes: #11647 
Refers to : #9729

## Reviewer guidance
Using the procedure described in #11647 :
- Test it with a token that only has one channel as Kolibri QA Channel
- Test it with a token that provides more than one channel as `latuk-noriz`

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2024-01-03 14:58 UTC, pcenov approved these changes
Thank you @jredrejo, I confirm - the flow with importing channels from a collection is working correctly now.

2024-01-03 15:06 UTC, pcenov requested changes
Sorry I noticed an issue - if I click the 'Import with token' button immediately after having loaded the list with channels I can still see all the options in the modal disabled. See the following video:

https://github.com/learningequality/kolibri/assets/79847249/b9db0a8b-1637-434c-9c3a-56408e23be10

2024-01-04 11:13 UTC, jredrejo commented
hi @pcenov 


> Sorry I noticed an issue - if I click the 'Import with token' button immediately after having loaded the list with channels I can still see all the options in the modal disabled. See the following video:

This new issue should be solved now. Clearly the ability to have multiple channels from a single token had not been tested before. I would not be suprised if you find something else in your tests (I had tested as much as I've been able but I don't have the imagination you have to break things :wink:  )

2024-01-04 12:16 UTC, pcenov commented
Hi @jredrejo the issue that you are fixing here is a regression in 0.16 and is working fine in 0.15 where it's been tested before.
I can see that now if I enter the token for the collection the button `Import with token` disappears completely which is probably OK but it's different from the 0.15 implementation. So my question is - is there something that's preventing this functionality to work exactly as it was in 0.15, specifically the `Import with token` button to remain visible?
Notice also that when I click the `Select resources` button and then I click the back arrow I am no longer at 'Select resources for import' from the collection and have to enter the token again - I can report this as a separate issue if it's not caused by any changes made here.

https://github.com/learningequality/kolibri/assets/79847249/2f64bccd-1786-423a-94fc-6e1c2c7f6b30

2024-01-04 12:46 UTC, jredrejo commented
> Hi @jredrejo the issue that you are fixing here is a regression in 0.16 and is working fine in 0.15 where it's been tested before. I can see that now if I enter the token for the collection the button `Import with token` disappears completely which is probably OK but it's different from the 0.15 implementation. So my question is - is there something that's preventing this functionality to work exactly as it was in 0.15, specifically the `Import with token` button to remain visible? 

Actually I have made it disappear in the last commit because I didn't see the sense of having it available there when you have the list of channels. I must confess that after so long using 0.16.x I don't remember how this worked in 0.15.x. If you click on the token it reappears. Anyway, I can make it visible again if you think it's better.



>Notice also that when I click the `Select resources` button and then I click the back arrow I am no longer at 'Select resources for import' from the collection and have to enter the token again - I can report this as a separate issue if it's not caused by any changes made here.
>

Yes, I've seen that but I thought this was on purpose, code is designed to do exactly that. If you think that's a problem, fill a new issue. I think it'd be good if the designers take a look to decide what's the best UX.
 
>  2024-01-04_14-08-11.mp4

2024-01-04 13:37 UTC, pcenov commented
If it's not a problem let's keep the `Import with token` button visible to keep it same as in 0.15 and also because one can directly click it and import from another channel or collection if they wish to do so.
I'll file a separate issue for the back button behavior.

2024-01-04 13:54 UTC, jredrejo commented
> If it's not a problem let's keep the `Import with token` button visible to keep it same as in 0.15 and also because one can directly click it and import from another channel or collection if they wish to do so. I'll file a separate issue for the back button behavior.

:+1: restored!

2024-01-04 15:27 UTC, pcenov approved these changes
The problems with the modal are solved now! Thanks @jredrejo!

2024-01-04 17:34 UTC, rtibbles approved these changes

2024-01-04 17:34 UTC, merged