Bulkimport
learningequality/kolibri pull request #11779
Opened 2024-01-24 04:41 UTC by nick2432

## Summary
Description of the Change:
The proposed changes aim to enhance the user creation process in the FacilityUserManager class by addressing issues related to case-insensitive username matching and the verification of duplicate usernames during bulk user imports.
Case-Insensitive Username Matching (FacilityUserManager):

In the create_user function of the FacilityUserManager class, case sensitivity is introduced to the username matching process. This ensures that usernames are checked in a case-sensitive manner during user creation.
Link to the relevant code: [FacilityUserManager]
Bulk User Import Duplicate Username Check (bulkimportusers.py):
Previously, the bulk import code only checked for username clashes if a UUID was specified for the user. The proposed changes extend this check to cases where the UUID is not specified, providing a more comprehensive verification process.
…
## References
Fixes https://github.com/learningequality/kolibri/issues/11081

…

## Reviewer guidance

…

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2024-01-27 00:19 UTC, rtibbles requested changes
2 changes needed, to have consistent case insensitivity.

2024-01-27 00:19 UTC, rtibbles commented on kolibri/core/auth/models.py
> +            username=username, facility=extra_fields["facility"]
This should not be updated - the intention was for the bulk import flow to match the enforcement that happens here, not for this enforcement to be removed.

2024-01-27 00:19 UTC, rtibbles commented on kolibri/core/auth/management/commands/bulkimportusers.py
> +                        username=user, facility=self.default_facility
We should do a case insensitive match here as well, to parallel the changes you made above.

2024-01-27 10:31 UTC, nick2432 commented
@rtibbles  I have changed what you said.

2024-01-31 15:47 UTC, rtibbles reviewed
Excellent, this looks good. We'll have manual QA test this, but I think this should be mergeable soon.

We will hold off on merging it until the 0.16.0 release is out.

In the meantime, could you address the linting issue? For now we can ignore the complexity requirement by doing this:

```
def build_users_objects(self, users):  # noqa C901
```

This is a directive comment to our linter to ignore this rule for this function for now.

2024-02-14 10:34 UTC, nick2432 commented
@rtibbles , do you have an estimate for when this will be merged?

2024-02-14 14:35 UTC, rtibbles commented
After 0.16.0 is released! We're in the final stages of QA now, and made a release candidate yesterday, so it is close :)

2024-02-15 16:28 UTC, pcenov commented
Hi @nick2432 and @rtibbles - I confirm that it's no longer possible to import a duplicate username (regardless of the letter case) if it's already extant in the facility.
However if there are several duplicate usernames in the CSV file (with different letter case like Peter, PETER) and I am importing them for the first time it's still possible to import all of them. So the question is whether this is in scope for this PR and should be fixed as well?

https://github.com/learningequality/kolibri/assets/79847249/5d249098-56fe-47db-a369-c3753d749877

2024-02-15 16:31 UTC, rtibbles commented
That's a good catch, Peter - I think we can file that as a follow up issue for now, so as not to block @nick2432 further here, but very happy for him to pick it up if he's interested!

2024-02-16 05:28 UTC, nick2432 commented
Thank you for the clarification, @rtibbles . I'll proceed with the current PR as suggested. I'll make a note of the additional issue with importing several duplicate usernames and will file it as a follow-up task. If there are any specific considerations or details I should be aware of while working on the current PR, please let me know. Appreciate your guidance!

2024-02-16 09:38 UTC, pcenov commented
Hi @nick2432 I have filed the follow-up issue here: https://github.com/learningequality/kolibri/issues/11890
I didn't observe any other issues while manually testing so if you are not going to be making any other changes here we could go ahead and approve this PR.

2024-02-16 10:39 UTC, nick2432 commented
> Hi @nick2432 I have filed the follow-up issue here: #11890 I didn't observe any other issues while manually testing so if you are not going to be making any other changes here we could go ahead and approve this PR.

ok

2024-02-16 11:13 UTC, radinamatic approved these changes
Manual QA passed, with one follow-up issue opened, good to go! 💯 🚀 :shipit:

2024-02-21 04:28 UTC, rtibbles approved these changes

2024-02-23 20:05 UTC, merged