Add .git to aphrodite fork in perseus viewer's package json
learningequality/kolibri pull request #12013
Opened 2024-03-21 21:54 UTC by Abhishekzod007

## Summary
While setting up Kolibri, a common issue regarding the inability of yarn package manager to install the aphorodite fork from github occurs
I encountered this while setting up the `release` branch when trying to address #11879 
@marsian83 helped out by [referencing his pr in `studio`](https://github.com/learningequality/kolibri/issues/11879#issuecomment-2001960579)

I have made those changes, and I open this PR to help out future contributors who might face this issue while contributing!

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2024-03-26 19:40 UTC, rtibbles requested changes
I ran this locally, and it caused an additional entry to be added to the yarn.lock file. This now reads:

```
+"aphrodite@https://github.com/learningequality/aphrodite.git":
+  version "2.2.3"
+  uid fdc8d7be8912a5cf17f74ff10f124013c52c3e32
+  resolved "https://github.com/learningequality/aphrodite.git#fdc8d7be8912a5cf17f74ff10f124013c52c3e32"
+  dependencies:
+    asap "^2.0.3"
+    inline-style-prefixer "^4.0.2"
+    string-hash "^1.1.3"
+
 "aphrodite@https://github.com/learningequality/aphrodite/":
   version "2.2.3"
   resolved "https://github.com/learningequality/aphrodite/#fdc8d7be8912a5cf17f74ff10f124013c52c3e32"
```

I am not entirely sure what error this is intended to fix, but as described (avoiding installing aphrodite without the .git extension) this does not do that, rather it just causes duplication in the lock file.

If you can describe steps to reproduce the error you are seeing, that might help me or other reviewers to evaluate whether this is resolving it.

2024-03-28 03:37 UTC, Abhishekzod007 commented
> I ran this locally, and it caused an additional entry to be added to the yarn.lock file. This now reads:
> 
> ```
> +"aphrodite@https://github.com/learningequality/aphrodite.git":
> +  version "2.2.3"
> +  uid fdc8d7be8912a5cf17f74ff10f124013c52c3e32
> +  resolved "https://github.com/learningequality/aphrodite.git#fdc8d7be8912a5cf17f74ff10f124013c52c3e32"
> +  dependencies:
> +    asap "^2.0.3"
> +    inline-style-prefixer "^4.0.2"
> +    string-hash "^1.1.3"
> +
>  "aphrodite@https://github.com/learningequality/aphrodite/":
>    version "2.2.3"
>    resolved "https://github.com/learningequality/aphrodite/#fdc8d7be8912a5cf17f74ff10f124013c52c3e32"
> ```
> 
> I am not entirely sure what error this is intended to fix, but as described (avoiding installing aphrodite without the .git extension) this does not do that, rather it just causes duplication in the lock file.
> 
> If you can describe steps to reproduce the error you are seeing, that might help me or other reviewers to evaluate whether this is resolving it.

Hii @rtibbles , when we switch on the branch kolibri 0.16.x  then this error comes after starting the server
![image](https://github.com/learningequality/kolibri/assets/98864225/8bce4041-77a0-4cfa-823e-20f3ee814407)
and for reference you can check it in this issue #11879

2024-03-28 14:12 UTC, rtibbles commented
This seems more likely an issue with using yarn 4? Kolibri is deliberately pinned to yarn version 1.

2024-04-02 22:18 UTC, rtibbles commented
Closing, can reconsider if we see replication with Yarn 1.

2024-04-02 22:18 UTC, closed without merging