fixes user selection getting lost on closing the sidepanel
learningequality/kolibri pull request #12160
Opened 2024-05-11 16:06 UTC by AllanOXDi

## Summary
Fixes user selection getting lost on closing the sidepanel
Closes #12135

## References
#12135

## Reviewer guidance
1. Navigate to the select questions 
2. Check the question you want to replace 
3. Click replace icon 
4. Close the side panel

…

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2024-05-13 00:07 UTC, AlexVelezLl reviewed
LGTM, code change makes sense and I tried some use cases and the bug has been fixed. 

But the fact that there was a call to `clearSelectedQuestions` when closing the side Panel made me question if perhaps the intention was to clear the replacements.

Because these are not cleared anywhere, and if you do multiple replacements in a row, the references from the previous replacements continue. So probably instead of a `clearSelectedQuestions` there should be a `clearReplacements` on the beforeRouterLeave @nucleogenesis?

https://github.com/learningequality/kolibri/assets/51239030/83c1cd1b-eab8-4e73-8076-0f860d393077

2024-05-14 21:16 UTC, nucleogenesis requested changes
The original page's selection is updated but `replacements` is not being cleared. I think that you could set the value of `replacements` in `handleConfirmClose` where we handle when the user says "Continue" to the alert telling them they'll lose their changes. 

https://github.com/learningequality/kolibri/assets/6356129/822aefca-a849-4225-b5cb-320885b770e0

2024-05-20 22:49 UTC, nucleogenesis approved these changes
The updates here LGTM after some testing! Thanks Allan

2024-05-21 04:54 UTC, AlexVelezLl requested changes
Hi @AllanOXDi The error still happens when we save the questions. Because we are only clearing the replacements when we exit without saving the questions:

https://github.com/learningequality/kolibri/assets/51239030/264f19a9-fc35-4922-8b94-c6cea9823cdb

My suggestion would be to clean the replacements on [this line](https://github.com/learningequality/kolibri/pull/12160/files#diff-5763edce2bca3c768bf0c4fe151975e7ce704c44207066e60a07a4c9261dee51R340), on router leave. So it would work for both cases.

2024-05-21 19:10 UTC, AlexVelezLl approved these changes
Thanks @AllanOXDi! LGTM :tada:

2024-05-21 20:05 UTC, merged