EQM: Notify not enough resources to replace questions
learningequality/kolibri pull request #12219
Opened 2024-05-28 21:44 UTC by AlexVelezLl

## Summary

Adds a modal to notify the user when there are no enough resources to replace the current selected questions

https://github.com/learningequality/kolibri/assets/51239030/b769d7f6-a996-41f4-ac6b-6d5a90fcb9ef

## References
Closes #12094

## Reviewer guidance
* Fill a section with almost all, or/and all available questions in the pool.
* Select them all and try to replace them. A modal should appear and inform you that there are no enough questions, and redirect you to add more resources

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2024-05-29 16:39 UTC, AlexVelezLl commented on kolibri/plugins/coach/assets/src/composables/useQuizCreation.js
> -            return;
This return here has making the whole function to return, and the updates werent applied when we had resource_pool updates.

2024-05-30 20:38 UTC, nucleogenesis requested changes
Only one blocking issue noted, otherwise, things look good to me and worked well in testing!

2024-05-30 20:38 UTC, nucleogenesis commented on kolibri/plugins/coach/assets/src/views/plan/CreateExamPage/ReplaceQuestions.vue
> +      @close="showNoEnoughResources = false"
This should also "go back" in the router and close the side panel.

2024-05-30 22:52 UTC, AlexVelezLl commented
Thank you @nucleogenesis! I have updated the close handler!

2024-05-31 09:42 UTC, pcenov commented
Hi @AlexVelezLl I confirm that this is implemented as specified in https://github.com/learningequality/kolibri/issues/12094 but while testing I noticed the following:

1. The 'add' word is missing here:

![2024-05-31_11-30-38](https://github.com/learningequality/kolibri/assets/79847249/14211353-3d60-40ff-8beb-fd64f8e49fe6)

2. Each time the modal pops up I can see the 'Replace questions' sidebar as well, even when there are no questions in it. Wondering whether that could that be avoided as it seems unnecessary?

https://github.com/learningequality/kolibri/assets/79847249/5440ff90-5b0e-405d-8bec-ad3fbd0a786d

2024-05-31 16:57 UTC, nucleogenesis approved these changes
I fixed @pcenov 's comment about the missing word and I think that the other comment is a great point well suited for a follow-up issue - #12229 

I'll approve and merge this for now so that I can rebase my open PR on it.

2024-05-31 16:57 UTC, nucleogenesis commented on kolibri/plugins/coach/assets/src/views/plan/CreateExamPage/ReplaceQuestions.vue
> +    />
To @pcenov 's comment about the side panel showing under the modal, I think maybe moving this to the CreateQuizSection component would help. Show the modal before navigating there and should be good to go

2024-06-03 14:59 UTC, merged