Manage users in LOD
learningequality/kolibri pull request #12228
Opened 2024-05-30 18:18 UTC by AlexVelezLl

## Summary

…

## References

…

## Reviewer guidance

…

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2024-08-29 22:50 UTC, rtibbles reviewed
Some quick feedback - I've raised my main concern (which is more with the original spec, than the work you have done here) on Slack for further discussion, but ultimately I think having this as a separate SPA is not the right direction - but we'll see what the discussion leads us to.

2024-08-29 22:50 UTC, rtibbles commented on kolibri/core/assets/src/core-app/apiSpec.js
> +    importLodUsersMachine,
I think I'd rather put this in `kolibri-common` rather than add it to the core API spec.

2024-08-29 22:50 UTC, rtibbles commented on kolibri/core/assets/src/utils/UserType.js
> +  if (!userObject.roles || !userObject.roles.length) {
No need to change but could also do:
```
if (!userObject?.roles.length) {
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

(I feel like you used this in the `useBaseSearch` refactor work)

2025-05-13 15:12 UTC, nucleogenesis commented on kolibri/plugins/device/assets/src/users/composables/useUsers.js
> +export default function useUsers() {
If this is specific to the device plugin, perhaps we should name this something other than `useUsers`. If this is able to be generalized, then perhaps we should consider moving it to `kolibri-common`

2025-05-22 17:34 UTC, AlexVelezLl commented on kolibri/plugins/device/assets/src/views/lodUsers/composables/useLodDeviceUsers.js
> +  }
Its not an UI event handler

2025-05-22 19:05 UTC, AlexVelezLl commented on kolibri/plugins/device/assets/src/views/lodUsers/UsersList.vue
> +        context: 'Label indicating that a learner user account has already been imported.',
Im not sure if we should move these strings to the device strings or keep them here

2025-05-22 19:08 UTC, AlexVelezLl commented on kolibri/plugins/device/assets/src/views/lodUsers/composables/useLodDeviceUsers.js
> +import Lockr from 'lockr';
I have placed this composable in this specific folder since it just makes sense for these particular views. Is it okay to left this here? Should it better placed in the `device/assets/src/composables` folder?

2025-05-22 19:10 UTC, AlexVelezLl commented on kolibri/plugins/device/assets/src/views/lodUsers/importUser/ImportUserWithCredentialsPage.vue
> +<template>
When first implemented the issue some months ago, we decided to duplicate these components from the setup wizard https://github.com/AlexVelezLl/kolibri/blob/87eb263c135bb4f0e629035a9a2bece43dc52483/kolibri/plugins/setup_wizard/assets/src/views/ImportIndividualUserForm.vue#L25. Do we still want to keep these components duplicated? Or should we find a way to encapsulate the common logic in just one component in the scope of this PR?

2025-05-22 19:12 UTC, AlexVelezLl commented on kolibri/plugins/device/assets/src/views/lodUsers/UsersRootPage.vue
> +      const getExternalEditPermissionsPath = () => {
I have keep this message and redirection to make another user admin when we are removing the last admin, although this will change in https://github.com/learningequality/kolibri/issues/13398. But as it was already implemented I have left it here for now.

2025-05-22 19:19 UTC, AlexVelezLl commented on kolibri/plugins/device/assets/src/views/lodUsers/composables/useLodDeviceUsers.js
> +let importLodMachineService = null;
Here's a substantial change to how we handle the state machine in the setup wizard. In the setup wizard, we have a wrapper as RootVue that instantiates the state machine service and uses provide/inject so that all routes can then access the state machine instance. It works there because the entire plugin relies on the state machine and makes sense to instanciate it in its RootVue. But this isn't going to happen in the device plugin, so I've instead set it as a global variable in this composable. What do you think?

2025-05-28 01:42 UTC, rtibbles commented on kolibri/core/auth/models.py
> +        with DisablePostDeleteSignal(), transaction.atomic():
Looking at the deletion utilities: https://github.com/learningequality/kolibri/blob/develop/kolibri/core/auth/utils/delete.py

There's other cleanup we should be doing here. I think maybe it would be better to construct a user focused deletion function in that utility module, rather than adding it as a model method. We should also follow the more complete deletion that is done in the delete.py module, deleting the related models etc.

2025-05-28 02:03 UTC, rtibbles requested changes, later dismissed
Generally making sense to me. Main things I want updated:
* API endpoint and deletion logic - ideally I think we want some test coverage of this also.
* Removal of the flyby code reformatting
* As far as possible avoiding the module state in the composable, unless you can convince me otherwise, it feels like this isn't quite right.

I think I'd like a second opinion from @nucleogenesis or @marcellamaki about the component code deduplication question.

2025-05-28 02:03 UTC, rtibbles commented on kolibri/core/auth/api.py
> +            user = FacilityUser.objects.get(id=user_id)
This can cause a 500 if a non-UUID value is passed here. We should at a minimum validate that this is a valid UUID before attempting to query the user.

2025-05-28 02:03 UTC, rtibbles commented on kolibri/core/auth/api.py
> +    def post(self, request):
Any reason to implement this as post rather than delete? If we use delete, we can use the standard permissions handling here: https://github.com/learningequality/kolibri/blob/develop/kolibri/core/auth/api.py#L138

2025-05-28 02:03 UTC, rtibbles commented on kolibri/plugins/coach/assets/src/views/common/resourceSelection/subPages/ManageSelectedResources.vue
> -<style scoped lang="scss">
Let's revert these changes in files that you haven't touched - sorry, this is a byproduct of the core API migration code not completely preserving the original contents.

2025-05-28 02:03 UTC, rtibbles commented on kolibri/plugins/device/assets/src/views/lodUsers/composables/useLodDeviceUsers.js
> +let importLodMachineService = null;
My only thought is whether there would be a parent (but not root) component where this would be persisted through each of the stages? My only concern is if this is in module state, then we are executing this things at initial module execution - for example, isn't this running task polling for soud_sync immediately on execution of this code? There's just something about this global state that feels not quite right to me.

2025-05-28 02:03 UTC, rtibbles commented on kolibri/plugins/device/assets/src/views/lodUsers/importUser/ImportUserAsAdminPage.vue
> +<template>
I think my suggestion would be to have an index page that embeds each of these, which is where the composable is setup, so that we don't have to have global state.

2025-05-28 02:03 UTC, rtibbles commented on kolibri/plugins/device/assets/src/views/lodUsers/importUser/ImportUserWithCredentialsPage.vue
> +<template>
It does feel like there's some significant duplication here, and especially if it's useful to share all or some of the composable, that might be a way to update the setup wizard also - I am not sure I know how much extra work that would be though!

2025-05-28 02:03 UTC, rtibbles commented on kolibri/plugins/device/urls.py
> +urlpatterns = [
More flyby code formatting here, but I'm not sure why this file is being changed.

2025-05-28 22:06 UTC, nucleogenesis commented on kolibri/plugins/device/assets/src/views/lodUsers/importUser/ImportUserWithCredentialsPage.vue
> +<template>
I'm not bothered by the duplication between the two here for now. If we anticipate that this workflow will change sooner than later and it'd be nice to have cleaner code to work with when that time comes, then it'd probably be worth making it a priority to fix in a follow-up.

Unless there is some reason I'm not seeing beyond generally avoiding duplication where we can, then I think it'd be okay as a clean-up task.

2025-05-28 22:10 UTC, nucleogenesis commented on kolibri/plugins/device/assets/src/views/lodUsers/composables/useLodDeviceUsers.js
> +import Lockr from 'lockr';
I like it how you have it

2025-05-29 15:29 UTC, marcellamaki commented on kolibri/plugins/device/assets/src/views/lodUsers/importUser/ImportUserWithCredentialsPage.vue
> +<template>
I agree - I think the duplication is okay for now. @AlexVelezLl and I chatted about this briefly during our checkin today and my two justifications are: 1) it's only in two places, let's abstract at 3 places. 2) I think the benefits of having this merged in so we can have it in `develop` as part of the 0.19 work (for QA/testing edge cases, etc) outweigh doing some refactoring now.

2025-06-02 13:55 UTC, AlexVelezLl commented on kolibri/plugins/device/assets/src/views/lodUsers/composables/useLodDeviceUsers.js
> +let importLodMachineService = null;
I have moved this to have an index page that provides the data context, and moved all users pages to be children of this page so they can inject this data. This way we can know better when we enter/leave users pages and know when to initialize/destroy the lod state machine.

2025-06-02 13:55 UTC, AlexVelezLl commented on kolibri/core/auth/models.py
> +        with DisablePostDeleteSignal(), transaction.atomic():
Done!

2025-06-02 17:23 UTC, AlexVelezLl commented on kolibri/core/auth/api.py
> +            user = FacilityUser.objects.get(id=user_id)
Just added a validator for this :)

2025-06-02 17:24 UTC, AlexVelezLl commented on kolibri/core/auth/api.py
> +    def post(self, request):
Dont recall why did I did it this way :sweat_smile:, but just updated it to be a delete :)

2025-06-02 17:24 UTC, AlexVelezLl commented on kolibri/plugins/coach/assets/src/views/common/resourceSelection/subPages/ManageSelectedResources.vue
> -<style scoped lang="scss">
Done

2025-06-02 17:26 UTC, AlexVelezLl commented on kolibri/plugins/device/urls.py
> +urlpatterns = [
Done! I think this was because I had initially added a new route for lod users here.

2025-06-13 18:34 UTC, rtibbles reviewed
This looks very close to mergeable from a quick read through - the backend code seems very clean, although I'd like a double check for whether we're doing extensive enough deletion.

For the frontend code, it looks a lot cleaner than previously, and I think the lack of consolidation is fine, except I think maybe we should consolidate strings more.

2025-06-13 18:34 UTC, rtibbles commented on kolibri/core/auth/api_urls.py
> +            r"^deleteimporteduser/(?P<user_id>[a-f0-9]{32})$",
This might even make the serializer check redundant, but measure twice, cut once!

2025-06-13 18:34 UTC, rtibbles commented on kolibri/core/auth/utils/delete.py
> +    delete_group = GroupDeletion(
I notice that there are still a lot of other models being deleted in the more general deletion case (looking at `_get_morango_models`, `_get_log_models` in particular) that may be relevant to the specific user - possible that the log models will be handled by cascade deletions from the facility user, but I'd like a double check from @bjester or @jamalex if we need to do some more explicit deletions here.

2025-06-13 18:34 UTC, rtibbles commented on kolibri/plugins/device/assets/src/views/lodUsers/UsersList.vue
> +        context: 'Label indicating that a learner user account has already been imported.',
I think fine to move to the device strings, as we're using the composition API.

2025-06-13 18:34 UTC, rtibbles commented on kolibri/plugins/device/assets/src/views/lodUsers/UsersPage.vue
> +      removeUserTitle: 'Remove user',
Similarly for these.

2025-06-13 18:34 UTC, rtibbles commented on kolibri/plugins/device/assets/src/views/lodUsers/importUser/ImportUserWithCredentialsPage.vue
> +    $trs: {
Maybe the compromise here is to at least consolidate the strings for reuse between the duplicated components?

2025-06-13 18:34 UTC, rtibbles commented on kolibri/plugins/device/assets/src/views/lodUsers/importUser/SelectFacilityPage.vue
> +      selectDifferentDeviceLabel: {
Likewise here.

2025-06-13 18:50 UTC, marcellamaki commented on kolibri/plugins/device/assets/src/views/lodUsers/importUser/ImportUserWithCredentialsPage.vue
> +    $trs: {
What if we put them in the `bulkUserManagement` string file? I know this is pre-existing piece of work (and in a different plugin), but in terms of the benefits for the release of having all of the new feature strings in one place, it would be nice. If that's conceptually too weird, I think yes, I might prefer these go into _some_ common string file, either another string feature file `lodUserManagement` if we want to be explicit/distinct, or into the device strings.

2025-06-13 19:45 UTC, rtibbles commented on kolibri/plugins/device/assets/src/views/lodUsers/importUser/ImportUserWithCredentialsPage.vue
> +    $trs: {
We're consolidating strings between the setup wizard and this new functionality, so I think it makes sense to have a separate file from bulkUserManagement. `lodUserManagement` is fine by me.

2025-06-13 21:21 UTC, AlexVelezLl commented on kolibri/plugins/device/assets/src/views/lodUsers/importUser/ImportUserWithCredentialsPage.vue
> +    $trs: {
Thanks! Changed :)

2025-06-13 21:22 UTC, AlexVelezLl commented on kolibri/plugins/device/assets/src/views/lodUsers/importUser/SelectFacilityPage.vue
> +      selectDifferentDeviceLabel: {
Moved to the new lodUsersManagementStrings :)

2025-06-17 15:33 UTC, bjester commented on kolibri/core/auth/utils/delete.py
> +    delete_group = GroupDeletion(
From what I recall, when we implemented the general deletion mechanism, we decided that being explicit was good because:
- relying on implicit cascade deletion could result in confusion or bugs as things change with continued development
- being explicit gives us the ability to present the user with accurate progress on deletion
- the UX is better with more explicit deletion, as it avoids background deletion for an indeterminate amount of time
- provides us with a self-check to compare the resulting counts from deletion

So, I would say, it would be good to just be explicit.

2025-06-25 11:46 UTC, AlexVelezLl commented
@coderabbitai review

2025-06-25 12:15 UTC, AlexVelezLl commented on kolibri/plugins/device/assets/src/views/lodUsers/importUser/SelectFacilityPage.vue
> +        selectedFacilityId: 'selectedFacilityId',
It seems that in its original component, it is somehow fixing something

2025-06-30 22:02 UTC, AlexVelezLl commented
@rtibbles Just a heads up that this is ready for a re-review

2025-07-02 18:35 UTC, rtibbles reviewed
I think all previous comments from code review have been addressed. I have not done _any_ manual testing, so I'll flag this for QA review and see how that goes!

2025-07-03 13:34 UTC, pcenov commented
Hi @AlexVelezLl, I was able to identify the following issues while manually testing (as always, I'll file follow-ups if something is not in scope for this PR):

1. The device name is missing in the "Remove user" modal:

![2025-07-03_10-09-34](https://github.com/user-attachments/assets/8565f2ee-8c06-4d8b-9b87-d7d35f2da022)

2. If I have already imported a user and I attempt to import the same user again then I am seeing "Successfully imported user". In this case the admin should be notified that the user is already imported. 

https://github.com/user-attachments/assets/520213b3-20ff-4f60-8410-bdade3223815

3.  I am getting an "Error removing user" when I attempt to remove the super admin user (with whom I am currently signed in) and I have already created another super admin user. So perhaps the Remove button should be disabled for that user:

https://github.com/user-attachments/assets/1662aa0f-7f52-473a-a041-35abfc03fd53

4. After importing and removing users at some point the device stopped syncing to the server. I was not able to replicate this issue subsequently after setting up a new LOD but adding the logs here in case you can get an idea what might have caused the issue:

[UbuntuLogs.zip](https://github.com/user-attachments/files/21038322/UbuntuLogs.zip)

2025-07-07 13:49 UTC, AlexVelezLl commented
Hi @pcenov! I have pushed some changes fixing 2, 3 and potentially 4. 

For number 1, I see that in the specs in this part, it is supposed to show the remote device name from where the user was imported, but I don't think we are storing this data right now, and Im not sure how difficult should it be to store it. @rtibbles is it possible to get the device name this user was imported from? Or should we rephrame the string to be something more generic?

2025-07-07 14:12 UTC, rtibbles commented
> For number 1, I see that in the specs in this part, it is supposed to show the remote device name from where the user was imported, but I don't think we are storing this data right now, and Im not sure how difficult should it be to store it. @rtibbles is it possible to get the device name this user was imported from? Or should we rephrame the string to be something more generic?

Yes, I don't believe we can reliably retrieve this information. So we should tweak this to something simple like "on the server" - we could say something more involved like "on the server this use was imported from" but it feels very convoluted without adding much.

2025-07-08 14:30 UTC, pcenov commented
Hi @AlexVelezLl 
For point 1 "The device name is missing in the "Remove user" modal" - are we going to have a follow-up issue filed or the text will be changed as part of this PR?
For point 2 - now when I try to import an already imported user I can see a "This user already exists on this device" validation message, however in that case if immediately after seeing the validation message I try to sign in as an admin I continue to see the same message while it should be possible to sign in as an admin:

https://github.com/user-attachments/assets/6e96ac74-0f1b-4d11-aadc-94b46c2be661

Point 3 is fixed 

While additionally testing I noticed the following issue too:

If I remove an imported LOD user while the user is signed in, that user doesn't get automatically signed out, instead I am seeing an unhandled error:

https://github.com/user-attachments/assets/da3a7e14-5306-43ce-aed0-e7c2d61f3aaa

For point 4 - Syncing between the server and the devices is still happening but I can't catch what exactly is causing it and when, so here are some sample logs from my Ubuntu server and one Android device. I'll try to further investigate tomorrow as it's quite time consuming.

[android_logs.zip](https://github.com/user-attachments/files/21123720/android_logs.zip)
[ubuntu_server.zip](https://github.com/user-attachments/files/21123721/ubuntu_server.zip)

2025-07-08 16:12 UTC, AlexVelezLl commented
Thanks @pcenov!

I have chaned the text for point 1 to be "If you remove this user from this device you will still be able to access their account and all their data on the server".

I have fixed point 2.

I think the new error you saw in point 3 can be filled as a separate issue, it seems to be because of a wrong response of the usersyncstatus mechanism, as it should return 403 instead of 400, so this can be fixed in a follow up :).

2025-07-09 14:09 UTC, pcenov commented
Thanks @AlexVelezLl - I confirm that the issues are fixed now.
I have created follow-up issues for the [stopping of syncing between the devices](https://github.com/learningequality/kolibri/issues/13543) and the [error when removing a signed in user](https://github.com/learningequality/kolibri/issues/13542).

2025-07-10 18:44 UTC, rtibbles approved these changes
Follow up issues filed for the observed issues. Let's merge this to avoid it becoming stale, and then we can fix the follow ups before release.

2025-07-10 18:44 UTC, merged