Distributed error reporting: Create model to store captured Errors
learningequality/kolibri pull request #12255
Opened 2024-06-07 10:45 UTC by thesujai

## Summary

1. Adds new model `ErrorReports` for storing reported errors
2. Add Class methods(utils) for manipulating ErrorReports
3. New tests for the model methods 
**Screenshots**
Test passed:
![Screenshot from 2024-06-07 15-56-33](https://github.com/learningequality/kolibri/assets/120925871/bba6db7c-03fe-4d24-9ba2-216139577401)
Functionality Passed:
![Screenshot from 2024-06-07 15-56-16](https://github.com/learningequality/kolibri/assets/120925871/aa0d46e6-fd6f-4aea-942e-502f246cce67)

## References

Fixes waiting

## Reviewer guidance

…

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2024-06-10 15:20 UTC, thesujai commented
@akolson @rtibbles Ready for review!

2024-06-11 11:57 UTC, akolson commented on kolibri/core/errorreports/models.py
> +        ...
Lets use `pass` here!

2024-06-11 12:00 UTC, akolson requested changes
Generally PR looks good to me! Just one blocking change and I think we should be good for the merge! Thanks @thesujai !

2024-06-11 12:00 UTC, thesujai commented on kolibri/core/errorreports/models.py
> +        ...
ok. I ain't using ellipsis ever again

2024-06-11 12:23 UTC, akolson commented on kolibri/core/errorreports/models.py
> +        if not settings.DEVELOPER_MODE:
Can we use `getattr(settings, "DEVELOPER_MODE", None)` instead based the issues we discussed?

2024-06-11 12:29 UTC, thesujai commented on kolibri/core/errorreports/models.py
> +        if not settings.DEVELOPER_MODE:
Done and tested as well

2024-06-11 12:55 UTC, akolson approved these changes
LGTM! Thanks @thesujai

2024-06-11 12:57 UTC, merged