Update to allow and implement randomization of sections.
learningequality/kolibri pull request #12278
Opened 2024-06-13 14:49 UTC by rtibbles

## Summary
* Changes description for the global 'learner_sees_fixed_order' flag to be about the section ordering, not questions
* Allows editing this flag in the quiz creation/editing flow
* Updates the learner experience to randomize the section order if this is set to false.

## References
Fixes [#12248](https://github.com/learningequality/kolibri/issues/12248)

## Reviewer guidance
Check that when creating a quiz, the section ordering can be randomized or set fixed, and that the learner experience of the quiz accords to this.

![Screenshot from 2024-06-13 07-46-09](https://github.com/learningequality/kolibri/assets/1680573/7e79bb72-5b5d-414b-b6e5-6de69eda47ae)

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2024-06-13 17:45 UTC, marcellamaki requested changes
The code changes here look fine, with the exception of one thing that seems like a bug and is making the UX a bit weird. Otherwise, I have one improvement idea about to the UX is worth making that I hadn't considered until I started playing around with it in manual QA.

First, I create a quiz that I want a fixed section order, but random questions:
<img width="1435" alt="Screenshot 2024-06-13 at 12 52 17 PM" src="https://github.com/learningequality/kolibri/assets/17235236/b7598649-a0b3-4bb7-90bc-f292d36d9961">

Before I assign the quiz, while I can still edit, I go back into the quiz, and the default seems to be "randomized" not what I have saved (this feels like a bug)
<img width="972" alt="Screenshot 2024-06-13 at 12 51 37 PM" src="https://github.com/learningequality/kolibri/assets/17235236/187efda4-6c84-4fcf-84d1-2fe7f33cf2f9">

Then (my idea of a UI update) in the coach reports, I think adding a distinction between section order and question order would also be helpful, because I think right now they are still conflated.
<img width="977" alt="Screenshot 2024-06-13 at 12 49 34 PM" src="https://github.com/learningequality/kolibri/assets/17235236/4cddee55-322e-4519-b560-963dc65a7873">

Maybe both "section order" and "question order" explained on the side? I'm not really sure how this would interact with the other quiz section report work so maybe it would be best done in follow up, actually..... I can open a follow up issue if that's preferable to fit into the changes made there, rather than try to sort that out now.

But the radio button stuff does seem worth fixing.

2024-06-13 17:45 UTC, marcellamaki commented on kolibri/plugins/coach/assets/src/views/plan/CreateExamPage/index.vue
> +              :currentValue="quiz.learners_see_fixed_order"
There's something going on here with the saving/setting current value that is changing the saved value on edit, that I'm pretty sure is a bug although I can't see on code read through where precisely it's happening (see screenshot in overall PR comment)

2024-06-14 15:16 UTC, marcellamaki commented
@rtibbles here's a video since the screenshots I shared was the wrong one: 


https://github.com/learningequality/kolibri/assets/17235236/daf3176c-2f18-459c-b343-df36a50adc75

2024-06-14 17:55 UTC, rtibbles commented
Looks like the issue you are seeing is actually caused by the fact that we're not actually saving the field to the backend!

2024-06-14 21:44 UTC, marcellamaki approved these changes
thanks for the updates @rtibbles

2024-06-14 21:46 UTC, merged