Fix coreStrings import in AttemptLogList
learningequality/kolibri pull request #12429
Opened 2024-07-09 13:32 UTC by AlexVelezLl

## Summary

For some webpack import issues, when importing coreStrings from a component inside core using `kolibri.utils.coreStrings` for some reason this import gets the default import of the file `commonCoreString` which is a mixin, instead of importing the named export of the coreStrings Translator. Referencing directly using relative import is a workaround to solve this [e.g.](https://github.com/AlexVelezLl/kolibri/blob/72297db6b321cb9c0ff7df8039da4930181c3d6d/kolibri/core/assets/src/views/BottomNavigationBar.vue#L67).

## References
Closes #12424.

## Reviewer guidance
Replicate the escenario showed in ##12424.

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2024-07-09 15:58 UTC, nucleogenesis requested changes, later dismissed
Thanks @AlexVelezLl - I'm requesting changes to block merge until @rtibbles has a chance to look at this if he's able to tomorrow. He and I discussed this a bit and I recall he was skeptical of the need to import the file differently here than in other parts of the code.

One thing I noticed is that this appears to be an issue with the `core` package itself in that all plugins can import `import coreStrings...` but the one file in `core` cannot.

```bash
kolibri/plugins/user_auth/assets/src/views/LoginSideNavEntry.js|4 col 1| import coreStrings from 'kolibri.utils.coreStrings';
kolibri/plugins/user_profile/assets/src/views/UserProfileSideNavEntry.js|4 col 1| import coreStrings from 'kolibri.utils.coreStrings';
kolibri/plugins/learn/assets/src/views/LearnSideNavEntry.js|3 col 1| import coreStrings from 'kolibri.utils.coreStrings';
kolibri/plugins/learn/assets/src/views/LibraryPage/OtherLibraries.vue|145 col 3| import coreStrings from 'kolibri.utils.coreStrings';
kolibri/plugins/learn/assets/src/views/ExamPage/AnswerHistory.vue|109 col 3| import coreStrings from 'kolibri.utils.coreStrings';
kolibri/plugins/learn/assets/src/composables/useLearningActivities.js|11 col 1| import coreStrings from 'kolibri.utils.coreStrings';
kolibri/plugins/learn/assets/src/my_downloads/views/MyDownloadsSideNavEntry.js|3 col 1| import coreStrings from 'kolibri.utils.coreStrings';
kolibri/plugins/device/assets/src/views/DeviceManagementSideNavEntry.js|6 col 1| import coreStrings from 'kolibri.utils.coreStrings';
kolibri/plugins/facility/assets/src/views/FacilityManagementSideNavEntry.js|4 col 1| import coreStrings from 'kolibri.utils.coreStrings';
kolibri/plugins/coach/assets/src/csv/fields.js|4 col 1| import coreStrings from 'kolibri.utils.coreStrings';
kolibri/plugins/coach/assets/src/views/CoachSideNavEntry.js|3 col 1| import coreStrings from 'kolibri.utils.coreStrings';
kolibri/plugins/coach/assets/src/views/common.js|2 col 1| import coreStrings from 'kolibri.utils.coreStrings';
kolibri/core/assets/src/views/AttemptLogList.vue|157 col 3| import coreStrings from 'kolibri.utils.coreStrings';
```

This may be a quirk of our build system and it may be one that can be fixed on the build-system level but that's probably more work than is necessary in light of our timeline.

In any case, let's see if Richard is back tomorrow and has any thoughts as well.

2024-07-10 13:30 UTC, pcenov commented
LGTM as well, though there's a `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'exercise_id'`) in the console when I select a question from the drop-down:

https://github.com/learningequality/kolibri/assets/79847249/1baa2a96-838e-49e9-bd0f-a41840a4b9b8

2024-07-10 19:23 UTC, AlexVelezLl commented
Thank you @pcenov! I have fixed this

2024-07-11 11:10 UTC, pcenov approved these changes
Thanks @AlexVelezLl!

2024-07-12 15:50 UTC, merged