Adjust CSS for button layout in EQM
learningequality/kolibri pull request #12465
Opened 2024-07-17 15:06 UTC by marcellamaki

## Summary
Updates `KGrid` span and CSS so that long buttons will fit without being cut off

## References
Fixes [#12449](https://github.com/learningequality/kolibri/issues/12449)

## Reviewer guidance
In German, or another language where the button is longer, does it still fit on all screensizes without cutoff? Is the placement still correct across languages and screensizes (i.e. not additional regressions)

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2024-07-18 02:02 UTC, rtibbles requested changes
One bit of cleanup, one naming nit. Have not manually tested yet.

2024-07-18 02:02 UTC, rtibbles commented on kolibri/plugins/coach/assets/src/views/plan/CreateExamPage/CreateQuizSection.vue
> +          // flexWrap: 'nowrap',
Remove commented style.

2024-07-18 02:02 UTC, rtibbles commented on kolibri/plugins/coach/assets/src/views/plan/CreateExamPage/CreateQuizSection.vue
> +        class="add-more-button"
Maybe `add-more-button-container` as this class is for the KGridItem not the contained KButton?

2024-07-18 08:50 UTC, radinamatic commented
The original issue seems to have been fixed for the ``+ Add questions`` button! 👍🏽  💯 

What was also visible on narrow screens was the lack of padding between the _There are no questions_ and the ``Save and close`` button when stacked, I'm wondering if we can adjust that in this same PR...?

German | Italian | Indonesian | Urdu
-- | -- | -- | --
<img width="357" alt="de" src="https://github.com/user-attachments/assets/fb4cfdea-a1df-42db-af32-69e6d620c81d"> | <img width="287" alt="it" src="https://github.com/user-attachments/assets/23c5a09c-74cc-41e2-ad45-b6bbddcdd1b2"> | <img width="230" alt="id" src="https://github.com/user-attachments/assets/c9e03c77-3f82-4c57-8ef9-f1454ab33cca"> | <img width="234" alt="ur" src="https://github.com/user-attachments/assets/4280e3d9-88c4-4496-83ee-e01f545e476a">

However, the button cutoff was present in other places, like ``Add N questions`` and ``Apply settings``. The latter should stack with the ``Delete section`` button if there are no horizontal space for both, correct?:

Indonesian | German | Greek | Greek (settings)
-- | -- | -- | --
<img width="248" alt="id2" src="https://github.com/user-attachments/assets/f0b8a239-5e10-4b39-9eae-9fef2809b454"> | <img width="237" alt="de2" src="https://github.com/user-attachments/assets/7640b2a6-ac8b-490a-b180-04ecf06a85a5"> | <img width="347" alt="el" src="https://github.com/user-attachments/assets/d4d800c1-2f79-4a0d-8760-71becaf8d324"> | <img width="244" alt="el2" src="https://github.com/user-attachments/assets/e5e3dc7e-8fed-4bfc-b7cd-fa163a1ff2b5">

2024-07-30 13:29 UTC, radinamatic commented
We still have some rough edges with the latest asset, especially around the 400px breakpoint: below it the button `Add N questions` sort of expands to fill in the bottom bar, while in the section settings sidebar, the buttons in the bottom bar still do not stack.

Greek | German
-- | --
https://github.com/user-attachments/assets/d5e6cb47-1312-441b-826f-d51c10d3d4ae | https://github.com/user-attachments/assets/4630bba2-1c88-4053-8ad3-5b1c4a107a4e

2024-07-30 19:54 UTC, marcellamaki commented
@radinamatic I've created a follow up for the bottom bar problem, as I'd like some feedback from the designers. I've assigned to myself and will prioritize for planned patch 1

2024-07-30 20:33 UTC, radinamatic approved these changes
Main original issue is fixed, follow-up filed, good to go for now! :shipit:

2024-07-30 21:58 UTC, rtibbles approved these changes

2024-07-30 21:58 UTC, merged