Remove channel labels from non-public ContentNode API
learningequality/kolibri pull request #12843
Opened 2024-11-14 05:49 UTC by Pulkitxm

## Fixes
Closes #12842

## Summary

- Removed the channel labels from the non-public `ContentNodeViewset` API.
- Added a flag `use_deprecated_channels_labels` to the `OptionalContentNodePagination` class to handle the inclusion of channel labels.
- Ensured that the public API still provides the channel labels.
- Verified that older Kolibri versions can navigate and search the library remotely without issues.

## References
- Issue: Remove the channel labels from the non-public ContentNode API
- Related PR: Update SearchFiltersPanel for Coach

## Reviewer guidance
- Test the non-public `ContentNodeViewset` API to ensure that channel labels are no longer returned.
- Verify that the public API still provides the channel labels.
- Ensure that older Kolibri versions (0.17.x) can navigate and search the library remotely from Kolibri 0.18.x and filter by Channels.
- Check for any potential issues or regressions in the search functionality and filtering by channels.

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [x] Critical user journeys are covered by Gherkin stories
- [x] Critical and brittle code paths are covered by unit tests

## PR process

- [X] PR has the correct target branch and milestone
- [X] PR has 'needs review' or 'work-in-progress' label
- [X] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [X] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [X] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2024-11-14 07:39 UTC, MisRob commented
Hi @Pulkitxm, welcome and thanks for your effort.

@nucleogenesis would you please have a look and decide whether we should review and if so, if the changes make sense?

@Pulkitxm Looking at https://github.com/learningequality/kolibri/issues/12842 it wasn't originally indicated as open for contributions. I wanted to provide some guidance so next time you can contribute successfully. Please find an unassigned 'help wanted' issue and before working on it, message us there and wait for an assignment. It's best to familiarize yourself with the contributing guidelines:

- [Kolibri Contributing Guidelines](https://github.com/learningequality/kolibri/blob/release-v0.16.x/CONTRIBUTING.md)
- [Kolibri Design System Contributing Guidelines](https://github.com/learningequality/kolibri-design-system/blob/main/CONTRIBUTING.md)
- [Studio Contributing Guidelines](https://github.com/learningequality/studio/blob/unstable/CONTRIBUTING.md)

Then you can see the list of unassigned ["help wanted"](https://github.com/search?q=org%3Alearningequality+is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+no%3Aassignee&type=issues) or ["good first issue"](https://github.com/search?q=org%3Alearningequality+is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee&type=issues) issues across all repositories.

2024-11-14 20:31 UTC, rtibbles requested changes
This needs some cleaning up - this may achieve the end desired end result, but has more code changes than I would expect, and adds additional code changes that are not needed.

This rather has the appearance of having been automatically generated by a generative AI, due to these extra, seemingly duplicative, changes. Feel free to use AI, however make sure you can understand the task and adjust the AI output in a meaningful manner, and provide with the smallest diff needed to achieve the task at hand.

2024-11-14 20:31 UTC, rtibbles commented on kolibri/core/content/api.py
> +            request.query_params.get("use_deprecated_channels_labels", "false").lower()
Using a query parameter to set this was not asked for in the issue description - this should be removed.

2024-11-14 20:31 UTC, rtibbles commented on kolibri/core/content/api.py
> +        labels = get_available_metadata_labels(self.queryset)
I think it would be cleaner to pass through this flag into the get_available_metadata_labels function and have that do the conditional behaviour for adding it to the labels.

2024-11-14 20:31 UTC, rtibbles commented on kolibri/core/content/api.py
> -                    ("labels", get_available_metadata_labels(self.queryset)),
This can remain inline with just the new argument for deprecated channel labels being passed.

2024-11-14 20:31 UTC, rtibbles commented on kolibri/core/content/api.py
> -        return {
No need to update this at all.

2024-11-14 20:31 UTC, rtibbles commented on kolibri/core/content/api.py
> +    def get_paginated_response(self, data):
This method doesn't belong on this class - this is extraneous.

2024-11-14 20:31 UTC, rtibbles commented on kolibri/core/content/api.py
> +            def paginate_queryset(self, queryset, request, view=None):
Instead of having to set this inside the paginate_queryset call, you can instead just define it as a class property:

```
class DeprecatedChannelsLabelsPagination(OptionalContentNodePagination):
    use_deprecated_channels_labels = True
```

2024-11-14 20:31 UTC, rtibbles commented on kolibri/core/content/utils/search.py
> +def _get_available_channels(base_queryset, include_labels=False):
This method doesn't need to be updated, the `get_available_metadata_labels` method should be updated to conditionally call this and add the result to the returned labels.

2024-11-19 23:16 UTC, rtibbles commented
Hi @Pulkitxm - any further guidance needed here? Feel free to ask any follow up questions!

2024-12-02 22:05 UTC, nucleogenesis reviewed
@Pulkitxm do you think you'll be able to address the feedback given above? If so please let us know, even if you need some additional time, otherwise we'll probably close this PR and reassign the related issue.

2024-12-19 20:08 UTC, rtibbles commented
This has now been taken over by @ozer550 so closing this PR.

2024-12-19 20:08 UTC, closed without merging