Moved login/logout logic into the useUser composable and updated references
learningequality/kolibri pull request #12915
Opened 2024-12-06 12:49 UTC by iamshobhraj

## Summary

Login/logout and session logic is moved into `useUser` composable from `action.js`. Refactored vuex state into module level state. References to `CORE_SET_SESSION` is updated to use the setSession method from useUser composable.  

## References

fixes #12204 

## Reviewer guidance

after updating references to `CORE_SET_SESSION` in `heartbeat.spec.js` file, some tests still failed. I am unable to figure out why these tests are failing. I updated the mock file and implementated it as written in documentation.

2024-12-09 20:05 UTC, nucleogenesis commented on packages/kolibri/__tests__/heartbeat.spec.js
> +  beforeEach(() => useUser.mockImplementation(() => useUserMock()));
Is there a particular reason for `mock.setup()` not to be called anymore? I'm wondering if this is related to the failing tests

2024-12-09 20:12 UTC, nucleogenesis requested changes
In the description you mentioned that the logic was moved _from_ an actions.js file but there are no changes to any Vuex files included.

I also see that `heartbeat.js` may need to be updated to use the `useUser` module as it is still calling `dispatch('setSession', ...)` [here](https://github.com/iamshobhraj/kolibri/blob/b5647baeb48179b37e234489e68bbe33bfde23f8/packages/kolibri/heartbeat.js#L199).

I had a comment in the heartbeat.spec.js file re: the tests but I think that updating `heartbeat.js` might be the key

2024-12-10 13:24 UTC, iamshobhraj commented on packages/kolibri/__tests__/heartbeat.spec.js
> +  beforeEach(() => useUser.mockImplementation(() => useUserMock()));
Sorry for the oversight. I’ve fixed this now.

2024-12-10 13:32 UTC, iamshobhraj commented
> In the description you mentioned that the logic was moved _from_ an actions.js file but there are no changes to any Vuex files included.
> 
@nucleogenesis Thanks for pointing that out. I had initially planned on removing the Vuex logic after successfully migrating the login and session logic to the new Composition API. However, I got stuck with the heartbeat.spec.js tests. I’ve now removed the login/logout and session logic from the Vuex files.

> I also see that `heartbeat.js` may need to be updated to use the `useUser` module as it is still calling `dispatch('setSession', ...)` [here](https://github.com/iamshobhraj/kolibri/blob/b5647baeb48179b37e234489e68bbe33bfde23f8/packages/kolibri/heartbeat.js#L199).
> 
> I had a comment in the heartbeat.spec.js file re: the tests but I think that updating `heartbeat.js` might be the key
>

Regarding the heartbeat.js, I refactored the store.dispatch to use the setSession method, but the failing tests persist. I suspect the issue might be related to xhr-mock, but I’m unable to pinpoint the exact cause.

Please let me know if you have any suggestions.

2024-12-13 00:37 UTC, nucleogenesis reviewed
I added one comment to the mock function for `setSession` and after some thinking and looking at the code locally I'm not sure precisely what the fix is, but I'm feeling it is very likely to do with that function altogether and it's differences to the real `setSession`.

Another thing I saw was that the `kolibriLogin` action is being dispatched a few places - such as the [`store.spec.js` file](https://github.com/iamshobhraj/kolibri/blob/ec7851aa405df9e32f819ad44cd488128408854b/packages/kolibri/__tests__/store.spec.js#L61-L62) 

Thank you for your effort on this. I hope anything I've said can be helpful. I'll keep thinking about this and come back to it again tomorrow if I can

2024-12-13 00:37 UTC, nucleogenesis commented on packages/kolibri/composables/__mocks__/useUser.js
> +    setSession: jest.fn(({ session: newSession, clientNow }) => {
One of the failing tests re: not calling `serverTime` w/ `clientNow` may be fixed by calling it here.

2025-01-09 03:01 UTC, rtibbles commented
When I did a rebase locally on develop here, it threw up some weird conflicts, but resolving them during the rebase did reduce it down to only about 10 commits, so I think this can be cleaned up! Let me know if it would be helpful for me to force push updates for this.

2025-01-13 07:21 UTC, iamshobhraj commented
> When I did a rebase locally on develop here, it threw up some weird conflicts, but resolving them during the rebase did reduce it down to only about 10 commits, so I think this can be cleaned up! Let me know if it would be helpful for me to force push updates for this.

Thank you for your help! If you think force pushing the updates would clean up the commit history and make it easier to manage, I would appreciate it. Please go ahead and do so if it's not too much trouble.

2025-01-16 17:56 UTC, rtibbles commented
Sure thing, @iamshobhraj - I will make the update for you!

2025-01-21 17:33 UTC, rtibbles requested changes
There are still a few failing tests after the rebase, but the commit history seems a bit more coherent now.

2025-01-21 17:33 UTC, rtibbles commented on packages/kolibri/composables/useUser.js
> -    //state
Did you cross check that these are not used anywhere before deleting them?

2025-01-21 17:33 UTC, rtibbles commented on packages/kolibri/composables/useUser.js
> +  async function kolibrisetUnspecifiedPassword({ username, password, facility }) {
This doesn't need to be in here, we can leave it in the actions.js instead.

2025-01-21 17:33 UTC, rtibbles commented on packages/kolibri/heartbeat.js
> -          // Calculate an approximation of the client 'now' that was simultaneous to the server
This explanatory comment should not be deleted.

2025-02-08 23:19 UTC, iamshobhraj commented
@nucleogenesis  i've hit a roadblock with these failing tests:

1. heartbeat › _checksession method › should sign out if an auto logout is detected
1. heartbeat › _checksession method › should redirect if a change in user is detected
   
   I am unable to figure out or debug the cause of these failing tests.
   
  Could you please help me understand:
   1. Why these specific tests are failing?
   2. What am I missing in my implementation?

2025-02-17 19:09 UTC, rtibbles commented
For most of the tests it seems that they are still trying to use `store.dispatch` to trigger the login action - as we have removed that action, this will have no effect! So moving those tests into tests for the useUser composable instead seems like the first step here.

2025-04-07 19:33 UTC, nucleogenesis commented
@iamshobhraj - will you be able to come back to work out the failing tests & linting? I looked at your last commit and it's quite large - did you do a substantial rewrite since the last review?

2025-04-07 20:36 UTC, iamshobhraj commented
@nucleogenesis I was trying to go back and do everything from scratch. Last time i was stuck on the failing test for `heartbeat.spec.js`, but this time ignored it initially and tried to update references in other files hoping that would fix the failing test. But the failing test in `heartbeat.spec.js` file is still persistent. From what i understand, the issue is in `_checksession` method particularly in disconnect-reconnect workflow. When Kolibri is disconnected and then reconnected to the server, the expected snackbar message is “Successfully reconnected,” but the test is throwing “Disconnected from the server.”. Same goes for when disconnected and trying to reconnect.

Also, I am sorry i havent been able to work on this pr over the past few weeks, I was occupied in some other stuff, particularly preparing my gsoc proposal, and i had hoped to return this some time later. So far i have moved the login/logout logic into useUser Composable and updated some references. But while updating the CORE_SET_SESSION referencee in `heartbeat.spec.js`, i think ive hit a roadblock.

2025-04-19 05:37 UTC, iamshobhraj commented
@nucleogenesis @rtibbles I'm closing this PR for now — I'll revisit it in the future after resolving the issue. In the meantime, feel free to reassign the issue if someone else would like to pursue it.

2025-04-19 05:37 UTC, closed without merging