Avoid displaying CoachClassListPage until after data is finished loading
learningequality/kolibri pull request #12951
Opened 2024-12-16 16:59 UTC by LianaHarris360

## Summary

This pull request handles the brief flash of the `CoachClassListPage` when there's only a single class, after navigating from another plugin to a page in the Coach plugin. The page now renders and displays only after the data is fully loaded. This allows the redirection implemented in `classIdParamRequiredGuard()` to correctly display the `CoachClassListPage` only when necessary.

Correct behavior:

https://github.com/user-attachments/assets/903803ff-c272-4259-b998-d0b7a7c60f5a

## References

Fixes #12815 

## Reviewer guidance

1. Navigate to any coach page from another plugin. Inspecting the page, pressing the Network tab, and setting the network throttling to slow 4g or 3g would be helpful to see a slower transition.

2024-12-16 21:41 UTC, nucleogenesis requested changes
I tested this locally and still see the flash.

https://github.com/user-attachments/assets/0b733c92-e344-4f4e-bc9b-e418e805d5b6

Does the CoachClassListPage have to be loaded at all if there is only one class? I wonder if maybe we could avoid routing to the page altogether in this case?

2024-12-17 20:18 UTC, LianaHarris360 commented
I was able to preventing loading the `CoachClassListPage` if there is only one class, avoiding the brief flash before the correct page is displayed. I added the check `classListPageEnabled` to the page, which will not display the page if there is only one class. Thanks for the suggestion @nucleogenesis 

https://github.com/user-attachments/assets/f501861c-94ec-4cd9-a758-4c3dc1e2a01a

2024-12-18 14:37 UTC, AllanOXDi approved these changes
Tested it locally and works fine for me. Thanks @LianaHarris360

2024-12-19 18:31 UTC, nucleogenesis approved these changes
Code changes LGTM! Thanks Liana

2024-12-19 18:49 UTC, merged