Aligned user-dropdown with app bar
learningequality/kolibri pull request #3686
Opened 2018-05-18 00:29 UTC by HansGam

### Summary

Before
![beforealign](https://user-images.githubusercontent.com/18543718/40210061-c30dfb7a-59f7-11e8-8dc2-dab125c98769.png)

After
![afteralign](https://user-images.githubusercontent.com/18543718/40210060-c2cf0f50-59f7-11e8-864e-a0a9a6c46baf.jpg)

…

### Reviewer guidance

-Sign in as a user
-Hover over the user dropdown bar
-It should be aligned with the search bar and also have a space (8px) separating them
…

### References
See #3639 

…

----

### Contributor Checklist

- [ ] Contributor has fully tested the PR manually
- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

2018-05-18 00:53 UTC, indirectlylit commented
yay!

2018-05-23 01:15 UTC, christianmemije requested changes
So usually vertical misalignment can be fixed using `vertical-align`, especially if elements have the same height. So an option would be to just add `vertical-align: middle` to `.user-menu-button`

2018-05-24 23:47 UTC, HansGam commented
Pushed changes, removed the 3px padding from top margin and added vertical-align: middle to a second file (kolibri/core/assets/src/views/app-bar.vue). They are now aligned from both mobile and desktop views, here is how mobile looks now:

![screenshot 2018-05-24 16 39 53](https://user-images.githubusercontent.com/18543718/40518972-089b3886-5f72-11e8-9725-8b6239060414.jpg)

2018-05-25 17:50 UTC, christianmemije approved these changes

2018-05-25 20:57 UTC, merged