Speeds up building by compiling messages *before* populating kolibri/dist
learningequality/kolibri pull request #3776
Opened 2018-06-08 16:27 UTC by benjaoming

### Summary

There's no immediate way to exclude child folders when running `compilemessages` (that would be an interesting upstream fix).

However, by moving the call to `compilemessages` in before calling `staticdeps`, then `kolibri/dist` will be empty provided that it's a clean environment. Otherwise run `make clean`.

### Reviewer guidance

n/a - if builds work I say go?

### References

#3384

----

### Contributor Checklist

- [x] Contributor has fully tested the PR manually
- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [x] If there are any front-end changes, before/after screenshots are included
- [x] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

2018-06-12 12:43 UTC, benjaoming commented
@indirectlylit this is ready to review.

2018-06-12 22:56 UTC, indirectlylit requested changes
Can you share your numbers? I'm not reproducing a speed up.

Here's what I see:


pre-change:

```
Start +2018-06-12T15:33:35-0700
End   +2018-06-12T15:38:32-0700
                      4:53
```

post-change

```
Start +2018-06-12T15:47:42-0700
End   +2018-06-12T15:53:05-0700
                      5:23
```

2018-06-13 13:12 UTC, benjaoming commented
@indirectlylit is your `kolibri/dist` clean when you compile the numbers?

2018-06-13 13:17 UTC, benjaoming commented
@indirectlylit Sorry if what I meant by "speed up" was perhaps a bit of an overstatement. You cannot measure runtime using a system's clock. You need to count CPU cycles, memory, i/o etc.

2018-06-13 15:58 UTC, indirectlylit commented
>  is your `kolibri/dist` clean when you compile the before numbers?

Yes, I ran `make clean` before each run.

Obviously not a very scientific test - I only ran the it one time - but it looked 10% slower which is why I wanted to make sure we're inadvertently making the situation worse.

2018-07-26 16:28 UTC, benjaoming commented
Am including this in #4056 after looking at the same message gathering outputs for too many times while dev'ing :)

2018-07-26 16:37 UTC, benjaoming commented
But you are right, this doesn't work very well.

I see that because of calling `kolibri manage compilemessages`, we are also going through migrations etc.. the initial kolibri setup.

```
python -c "import kolibri; print(kolibri.__version__)" > kolibri/VERSION

Current version is now 0.11.0a3.dev0+git.191.g3e2b898c0
# Change working directory to kolibri/ such that compilemessages
# finds only the .po files nested there.
cd kolibri && PYTHONPATH="..:$PYTHONPATH" python -m kolibri manage compilemessages
INFO     Running Kolibri with the following settings: kolibri.deployment.default.settings.base
INFO     Kolibri running for the first time.
INFO     We don't yet use pre-migrated database seeds, so you're going to have to wait a bit while we create a blank database...

```

2018-07-26 16:42 UTC, benjaoming commented
I'm going to have a look at this in #4056 

Also, there's this perhaps new problem, these are all-together easier to solve in one go, because I'm invoking the same build commands so many times.

![image](https://user-images.githubusercontent.com/374612/43275967-94dc5fba-9103-11e8-811d-2881cbd78552.png)

2018-07-26 16:42 UTC, closed without merging