Gherkin Coach module, I delete and add one coach scenario that existing in kolibri
learningequality/kolibri pull request #4101
Opened 2018-08-03 02:30 UTC by mrpau-julius

### Summary
Gherkin coach module
I finish all the coach scenarios base on pickle and I delete two .feature that not existing in latest kolibri version. I think that two scenarios was seen in kolibri 0.7.2 and I add one more scenario to complete the Gherkin coach module. 
please review my PR @radinamatic :smiley:

### Contributor Checklist

- [ ] Contributor has fully tested the PR manually
- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

2018-08-03 19:53 UTC, radinamatic requested changes
The two files you deleted were there for a reason:

- `class-coach-view.feature` should describe the scenario that covers the experience of the *Class coach* - coach that has access *only* to the classes they are assigned to, as opposed to the *Facility coach* who has access to *all* the classes in the facility.

- `coach-view-class-report-progress.feature`  should describe the scenario of reviewing the progress of the whole class per each channel. View this video to understand the difference from reviewing the progress of individual learners:
https://drive.google.com/file/d/1bbOUjnBd3K8vvWw4P4gGPbNuRtlwMj18/view

2018-08-03 19:53 UTC, radinamatic commented on integration_testing/features/coach/coach-lesson-report.feature
> +      And I am on the *Coach > lessons* page
Capitalize the L in `*Coach > lessons*`.

2018-08-03 19:55 UTC, radinamatic commented on integration_testing/features/coach/coach-lesson-report.feature
> +    Then I am on the *lesson report details* page
Capitalize the words in `*lesson report details*` to reflect the UI:

![2018-08-03_21-35-17](https://user-images.githubusercontent.com/1457929/43662964-f375e734-9767-11e8-8a84-cd70b077d8c9.png)

2018-08-06 01:46 UTC, mrpau-julius commented
thank you so much @radinamatic for review my PR, I thoughts class coach and facility coach are same access but not. yes your right that two coach users are different. I will edit that today. so that I can proceed to guest user :smiley:

2018-08-06 21:19 UTC, radinamatic approved these changes
Looking better @mrpau-julius! 👍

2018-08-06 21:19 UTC, merged