Guest role gherkin .feature files.
learningequality/kolibri pull request #4116
Opened 2018-08-07 09:42 UTC by mrpau-richard

### Summary
I create a gherkin .feature files that contains a guest role.

### Contributor Checklist

- [ ] Contributor has fully tested the PR manually
- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

2018-08-07 14:24 UTC, radinamatic requested changes
Added a couple of comments, but otherwise looking good!

2018-08-07 14:24 UTC, radinamatic commented on integration_testing/features/guest/guest-engage-content-channels.feature
> +      And I am on *learn > classes page
If this is a guest user, they cannot be on *Learn > Classes* page.

2018-08-07 14:24 UTC, radinamatic commented on integration_testing/features/guest/guest-engage-content-channels.feature
> +      And I am on *learn > classes page
Remember always to capitalize the location, so `*Learn > Channels*` or `*Learn > Recommended*`.

2018-08-07 14:24 UTC, radinamatic commented on integration_testing/features/guest/guest-engage-content-channels.feature
> +     And I am on *learn > topic* page
The convention we are using is meant to indicate the location with plugin and tab specifiers, and not go further down the channel's topic tree, so this is technically still `*Learn > Channels*`.

2018-08-07 14:24 UTC, radinamatic commented on integration_testing/features/guest/guest-engage-content-recommended.feature
> +      And I am on *learn > classes page
Same comments as above: remember to capitalize, and no `Classes` page for guests.

2018-08-07 14:24 UTC, radinamatic commented on integration_testing/features/guest/guest-find-content-item.feature
> +    When I fill in the search bar <search bar> with the item that I need to find
This would be better named as `search_term`, as *search bar* is an UI element.

2018-08-08 09:13 UTC, mrpau-richard commented
@radinamatic done fixing all of your review comments in this PR.

2018-08-08 12:13 UTC, radinamatic approved these changes

2018-08-08 12:13 UTC, merged