Calculate ChannelMetadata public api fields
learningequality/kolibri pull request #4226
Opened 2018-09-08 02:27 UTC by ralphiee22

### Summary

Adds fields to `ChannelMetadata` that will be returned by the public channel api. We now calculate these fields during channel import, as well as during a migration.
Added a test for calculating fields during data migration. 
We now have a blacklist of models to exclude during channel import, such as the `Language` M2M field on `ChannelMetadata`.

### Reviewer guidance

make sure you have content locally and 
A. go to http://0.0.0.0:8000/api/remotechannel?baseurl=http://0.0.0.0:8000/ to see public api.
B. migrate old dbs
C. import channel/content from studio

----

### Contributor Checklist

- [x] Contributor has fully tested the PR manually
- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

2018-09-17 14:06 UTC, rtibbles requested changes
A bit of cleanup would be handy. Some questions and comments.

2018-09-17 14:06 UTC, rtibbles commented on kolibri/core/content/models.py
> +        verbose_name=_("languages"),
To reduce confusion for translators, I have been trying to remove gettext calls for explicitly developer facing code, so I think we can unwrap this.

2018-09-17 14:06 UTC, rtibbles commented on kolibri/core/content/serializers.py
>      def get_last_published(self, instance):
Hrm - this conflates the last updated time with the last publish time, do we want to do this?

2018-09-17 14:06 UTC, rtibbles commented on kolibri/core/content/serializers.py
> -class PublicChannelSerializer(KolibriModelSerializer):
Presumably this is ok because we do not directly serialize the last updated time?

2018-09-17 14:06 UTC, rtibbles commented on kolibri/core/content/serializers.py
> -class PublicChannelSerializer(KolibriModelSerializer):
Is it explicitly an issue because of the validation logic?

2018-09-17 14:06 UTC, rtibbles commented on kolibri/core/content/serializers.py
> -class PublicChannelSerializer(KolibriModelSerializer):
Oh, I guess my first point doesn't matter because `last_updated` doesn't need this either...

2018-09-17 14:06 UTC, rtibbles commented on kolibri/core/content/test/test_data_migrations.py
> +class TestMigrations(TestCase):
Is this the same as the code in auth? Could we have a common base class for testing this, rather than repeating?

2018-09-17 14:06 UTC, rtibbles commented on kolibri/core/content/utils/annotation.py
> +def recurse_availability_coach_content(channel_id):
This function should be renamed, it's not about the availability of coach content, per se, but the number of coach contents.

2018-09-17 14:06 UTC, rtibbles commented on kolibri/core/content/utils/annotation.py
> +    logger.info('Setting availability of coach content ContentNode objects with children for {levels} levels'.format(levels=node_depth))
`Setting totals of coach content Contentnode objects`

2018-09-17 14:06 UTC, rtibbles commented on kolibri/core/content/utils/annotation.py
> +        logger.info('Setting availability of coach content ContentNode objects with children for level {level}'.format(level=level))
`Setting totals of coach content Contentnode objects`

2018-09-17 14:06 UTC, rtibbles commented on kolibri/core/content/utils/annotation.py
> +    logger.debug("Availability of coach content annotation took {} seconds".format(elapsed.seconds))
`Topic coach content annotation`

2018-09-17 14:06 UTC, rtibbles commented on kolibri/core/content/utils/annotation.py
> +    channel.total_resource_count = content_nodes.filter(available=True).exclude(kind=content_kinds.TOPIC).count()
Does studio dedupe by `content_id`? If it doesn't, I kind of think it should, and so should Kolibri.

2018-09-17 14:42 UTC, rtibbles commented
Seems to work somewhat as intended.
Note that the URL is actually: http://127.0.0.1:8000/api/content/remotechannel/?baseurl=http://127.0.0.1:8000/

One issue is that the public URL returns channels with no available resources (I realize this is not a result of this PR, but this should be fixed).

2018-09-18 17:15 UTC, ralphiee22 commented on kolibri/core/content/serializers.py
>      def get_last_published(self, instance):
this is up for debate. we could add another field which is actually the last updated time. but the public API relies on `last_published` for filling in some fields, so we need to carry that data over from studio. Also, when doing P2P content syncing, it seems more useful to know when a channel has been updated (perhaps with more content?) then knowing the last published. Could also add a comment which explains this discrepancy.

2018-09-18 17:15 UTC, ralphiee22 commented on kolibri/core/content/test/test_data_migrations.py
> +class TestMigrations(TestCase):
will do!

2018-09-18 19:46 UTC, rtibbles commented on kolibri/core/content/test/test_annotation.py
> +        recurse_availability_coach_content(channel_id="6199dde695db4ee4ab392222d5af1e5c")
Looks like you need to update the name of this function in this test?

2018-09-18 19:47 UTC, rtibbles commented on kolibri/core/public/api.py
> +    return channels.filter(root__available=True).distinct()
:+1:

2018-09-18 20:54 UTC, rtibbles approved these changes

2018-09-18 20:55 UTC, merged