Super admin gherkins
learningequality/kolibri pull request #4358
Opened 2018-10-03 01:22 UTC by DXCanas

Adding gherkins from [here](https://docs.google.com/document/d/1xrRq0UTVn0bum5YuPRQ4ZSNkgpdy5Ny4tzdvgS7lBfg/edit), refactoring them for `super admin` over `superuser`

2018-10-03 14:43 UTC, indirectlylit commented
thank you! @radinamatic would you mind reviewing?

2018-10-03 16:23 UTC, radinamatic requested changes
Welcome @DXCanas to the pickling club! :tada: 

Looking good, just a few comments :+1:

2018-10-03 16:23 UTC, radinamatic commented on integration_testing/features/super-admin/super-admin-downgrade-from-super-admin-to-device-permissions.feature
> +Feature: Super admin changes device permissions from super admin to device permissions
Scenario is well described, but the filename and the feature name is a bit unclear. Maybe it's our internal convention at this moment, but "downgrading _to_ device permissions", sounds unclear to me. Technically it's a group/type of permissions, for the moment we have just one but that might change in the future. Could we change this to "content import permission"?

2018-10-03 16:23 UTC, radinamatic commented on integration_testing/features/super-admin/super-admin-downgrade-from-super-admin-to-device-permissions.feature
> +      And I see that all checkboxes also become active
Nitpicking, but technically it's just one that becomes active :stuck_out_tongue: 
Not sure if spelling it out in full is necessary (it's long), it's just that the sequence where all checkboxes are deselected, and then they are active sounded weird...

2018-10-03 16:23 UTC, radinamatic commented on integration_testing/features/super-admin/super-admin-downgrade-from-super-admin-to-device-permissions.feature
> +    Then I should see that I can still *Save changes*
Is step necessary? I mean is there a scenario where you would be able to change a state of the checkbox, but not save changes?

2018-10-03 16:23 UTC, radinamatic commented on integration_testing/features/super-admin/super-admin-edit-user.feature
> +    When I click on *Manage* button for the user I want to edit
Is this on latest develop? It should be `Options` button and `Edit details` option in the step below...

![ledev18aut running - oracle vm virtualbox_220](https://user-images.githubusercontent.com/1457929/46424134-8ba8ed80-c738-11e8-9ae7-d854c5dac66c.png)

You should review the rest of the scenario too.

2018-10-03 16:23 UTC, radinamatic commented on integration_testing/features/super-admin/super-admin-grant-super-admin-permissions.feature
> +make a facility user a super admin
Who exactly is **facility** user, any user of the facility or a **Facility admin**?

2018-10-03 16:23 UTC, radinamatic commented on integration_testing/features/super-admin/super-admin-revoke-super-admin-permissions.feature
> +    When I deselect the *Make super admin checkbox*
`When I deselect the *Make super admin* checkbox`

2018-10-03 16:23 UTC, radinamatic commented on integration_testing/features/super-admin/super-admin-revoke-super-admin-permissions.feature
> +      And I see that those checkboxes under *Device permissions also become active
Missing `*` after "permissions".

2018-10-03 20:57 UTC, DXCanas reviewed
Pinging @jtamiace for contributions

@indirectlylit I'm noticing that it's pretty easy for Gherkins to get out of date (and less useful) with a simple change in copy. The ones I pasted here were written before some string updates happened in the UI, becoming significantly less useful since the strings act as identifiers for an integration tester. Don't really have any solutions, just flagging a shortcoming... thoughts?

2018-10-03 20:57 UTC, DXCanas commented on integration_testing/features/super-admin/super-admin-downgrade-from-super-admin-to-device-permissions.feature
> +Feature: Super admin changes device permissions from super admin to device permissions
Is "downgrade" is still acceptable?

2018-10-03 20:57 UTC, DXCanas commented on integration_testing/features/super-admin/super-admin-downgrade-from-super-admin-to-device-permissions.feature
> +Feature: Super admin changes device permissions from super admin to device permissions
Also, what do you think of "limited device permissions"? To maintain consistency between the UI and the gherkin?

2018-10-03 20:57 UTC, DXCanas commented on integration_testing/features/super-admin/super-admin-downgrade-from-super-admin-to-device-permissions.feature
> +    Then I should see that I can still *Save changes*
@jtamiace

2018-10-03 20:57 UTC, DXCanas commented on integration_testing/features/super-admin/super-admin-edit-user.feature
> +    When I click on *Manage* button for the user I want to edit
Didn't update every gherkin story; by and large left the existing ones alone. I did rename files, however, which is why they're showing up here as "new". I'll update this, though.

2018-10-03 20:57 UTC, DXCanas commented on integration_testing/features/super-admin/super-admin-grant-super-admin-permissions.feature
> +make a facility user a super admin
Any user on the facility. This is carryover from the time before `superuser` - when device owners where facility agnostic.

@jtamiace thoughts?

2018-10-03 21:55 UTC, jtamiace commented on integration_testing/features/super-admin/super-admin-grant-super-admin-permissions.feature
> +make a facility user a super admin
Yep, any user of the facility (learner, coach, or facility admin)

2018-10-03 22:29 UTC, indirectlylit commented
>  I'm noticing that it's pretty easy for Gherkins to get out of date (and less useful) with a simple change in copy

that's a great point.

I guess the two options are either

1. find a way to abstract them from actual text. Not sure if that's possible... (@radinamatic)
2. make it a matter of process to search stories when updating user-facing text

I think 2 is probably more likely what we'll need to do...

2018-10-04 06:36 UTC, radinamatic commented on integration_testing/features/super-admin/super-admin-downgrade-from-super-admin-to-device-permissions.feature
> +Feature: Super admin changes device permissions from super admin to device permissions
"Downgrade" sounds Ok to me (anything below the super admin is _down_ :wink:), as does  "limited device permissions",  but "content import permission" is more explicit, at least at this stage.

2018-10-04 06:39 UTC, radinamatic commented on integration_testing/features/super-admin/super-admin-edit-user.feature
> +    When I click on *Manage* button for the user I want to edit
Understood, I think that is a fair choice, write the new ones according to the current state of things, and update the rest in a separate PR (not you necessarily).

2018-10-04 06:39 UTC, radinamatic commented on integration_testing/features/super-admin/super-admin-grant-super-admin-permissions.feature
> +make a facility user a super admin
Gotcha!

2018-10-04 06:48 UTC, radinamatic commented
> 1. find a way to abstract them from actual text. Not sure if that's possible...

Not that I've seen, but will research more!

> 2. make it a matter of process to search stories when updating user-facing text

Maybe add a `gherkin-review` label on each PR that involves a change in the copy, so that they can be filtered once merged in order to update the scenarios?

2018-10-04 06:50 UTC, radinamatic approved these changes
Looking good! :+1:

2018-10-04 14:42 UTC, indirectlylit commented
thanks all!

2018-10-04 14:42 UTC, merged