Increase font size of description, add spacing above read more link
learningequality/kolibri pull request #4403
Opened 2018-10-12 13:51 UTC by JasonTame

### Summary

- Changed description font size from 12px to 14px

- Adding margin of 8px above 'View More' link

**Before:**
![description_before](https://user-images.githubusercontent.com/15672948/46873304-8170a880-ce36-11e8-83de-a36d4e7e816e.png)

**After:**
![description_after](https://user-images.githubusercontent.com/15672948/46873312-83d30280-ce36-11e8-86f7-df8d93bddf4a.png)

…

### Reviewer guidance

1. Navigate to Coach view
2. Add new lesson/select existing lesson
3. Click on 'Add Resources'
4. View card descriptions
…

### References

https://github.com/learningequality/kolibri/issues/4396

----

### Contributor Checklist

- [ x] Contributor has fully tested the PR manually
- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [x ] If there are any front-end changes, before/after screenshots are included
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] Reviewer has fully tested the PR manually
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependencies files were updated (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Link to diff of internal dependency change is included
- [ ] CHANGELOG.rst is updated for high-level changes
- [ ] Contributor is in AUTHORS.rst

2018-10-12 14:13 UTC, benjaoming commented
@JasonTame welcome! Thanks for the contribution and for adding screenshots!

The screenshots certainly look like something is improved! I have changed the base to the upcoming 0.11 release branch.

There are some conflicts apparently - I wonder if they are due to someone already having worked with this. Could you try to merge the upstream branch `release-v0.11.x` into your branch, looking at the conflicts and what you think should happen?

2018-10-12 16:05 UTC, rtibbles commented
It might be worth just looking at latest `release-v0.11.x` branch and then reapplying the changes. The changes are relatively minor, and resolving the merge conflict is probably not worth it (especially since Github seems to think the merge conflict is too complex to resolve with its web tool).

2018-10-12 17:18 UTC, christianmemije requested changes
Instead of adding the top margin to the `TextTruncator` component we should only add it where it is necessary, within the `.description` class in the `LessonContentCard`.

2018-10-13 06:28 UTC, JasonTame commented
Hi guys, thanks for the feedback. I'll make the changes as requested

2018-10-13 16:35 UTC, closed without merging