0.12 pickles update
learningequality/kolibri pull request #4693
Opened 2019-01-06 19:14 UTC by radinamatic

### Summary

*WIP - don't merge!*

### Reviewer guidance

TBAdded

### References

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] Gherkin stories have been updated

### Reviewer Checklist

- PR is fully functional
- Documentation is updated

2019-01-09 19:03 UTC, indirectlylit commented
minor note - recommend not removing checkboxes from the PR template

2019-01-09 20:25 UTC, radinamatic commented
> recommend not removing checkboxes from the PR template

Noted, but even when they are not applicable at all?

2019-01-10 17:34 UTC, indirectlylit commented
> even when they are not applicable at all?

correct - just leaving them unchecked is fine

2019-01-15 23:57 UTC, indirectlylit requested changes
changes look great!

please revert the changes to yarn.lock - you may need to update your yarn installation locally

2019-01-15 23:57 UTC, indirectlylit commented on integration_testing/features/super-admin/super-admin-profile-command.feature
> +      And I see that "xxxxxxxx_xxxxxx_requests_performance.csv" file has at least one line per each Kolibri page I interacted with in the browser, and lines begin with a timestamp followed by request
great

2019-01-15 23:57 UTC, indirectlylit commented on yarn.lock
> -  integrity sha512-OfC2uemaknXr87bdLUkWog7nYuliM9Ij5HUcajsVcMCpQrcLmtxRbVFTIqmcSkSeYRBFBRxs2FiUqFJDLdiebA==
please revert the changes to this file

2019-01-16 00:15 UTC, radinamatic commented
@indirectlylit `yarn.lock` has been reverted, let's wait for the checks to pass and it can be merged!

2019-01-16 00:36 UTC, indirectlylit approved these changes

2019-01-16 00:36 UTC, indirectlylit commented
skipping checks because it's just feature files

2019-01-16 00:36 UTC, merged