Simplify interface for createSnackbar action
learningequality/kolibri pull request #5241
Opened 2019-03-04 23:15 UTC by jonboiser

### Summary

1. Simplifies the interface of the `createSnackbar` action to reflect how it's used virtually 100% of the time (to show a snackbar with text that auto-dismisses).
1. For the lower-level `CORE_CREATE_SNACKBAR` mutation, enforces that the `autoDismiss` action is always explicitly set.
1. In Lesson Resource List, change the KDraggable container so it doesn't emit a sort/change event when nothing has been moved.

Removes a net of 100 lines.

### Reviewer guidance

1. Check each refactored section to see if it reflects the new interfaces.

### References

…

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.rst

2019-03-04 23:20 UTC, radinamatic commented
> Removes a net of 100 lines.

Way to go! 🙇‍♀️

2019-03-06 00:45 UTC, indirectlylit commented
switching base to `develop`

conflict  should be resolved when #5244

2019-03-19 20:46 UTC, indirectlylit commented on kolibri/plugins/style_guide/assets/src/views/StyleGuideIndex.vue
> +  FullVue.use(VueAphrodite);
I actually have some major changes and fixes to the `style_guide` plugin coming up. Would you mind removing these changes to prevent conflict?

2019-03-22 22:31 UTC, indirectlylit requested changes
one bug and one optional suggestion

2019-03-22 22:31 UTC, indirectlylit commented on kolibri/core/assets/src/state/modules/snackbar.js
> +      // hideCallback
I know this pre-dated your PR, but just noting that on line 4 only `text` and `autoDismiss` are mentioned. The other ones seem to be added dynamically and are only implicitly part of the API.

I wonder if there's a need to nest these options in their own `options` object? Perhaps the state here should be flattened to

```javascript
  state: {
    isVisible: false,
    text: '',
    autoDismiss: true,
    duration: null,
    actionText: null,
    actionCallback: null,
  },
```

thoughts?

2019-03-22 22:31 UTC, indirectlylit commented on kolibri/plugins/coach/assets/src/views/plan/CreateExamPage/index.vue
> +          this.createSnackbar(snackbarString, { item: contentNode.title });
looks like we're missing a `this.$tr(...)` here?

2019-03-22 23:07 UTC, jonboiser commented
Fixed the missing `$tr` call in CreateExamPage. I'm going to suggest not flattening out the `snackbar.state.options`, as it will require some more refactors.

2019-03-22 23:22 UTC, indirectlylit approved these changes

2019-03-22 23:23 UTC, indirectlylit commented
cool. Nice refactor changing the `autoDismiss` defaults

feel free to merge once the tests pass

2019-03-22 23:51 UTC, merged