update the super-admin-export-data.feature
learningequality/kolibri pull request #5357
Opened 2019-04-12 08:32 UTC by mrpau-julius

### Summary

 
The additional step for super admin export data features. 

### Reviewer guidance

…

### References

#5138 

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.rst

2019-04-12 08:43 UTC, radinamatic commented on integration_testing/features/super-admin/super-admin-export-data.feature
> +    Then I see generating log file loading
Then I see the loading indicator

2019-04-12 08:43 UTC, radinamatic commented on integration_testing/features/super-admin/super-admin-export-data.feature
> +      And the *Download* button is enabled
Swap the order of the lines 12 & 13.

2019-04-12 08:45 UTC, radinamatic commented on integration_testing/features/super-admin/super-admin-export-data.feature
> +    Then I see generating log file loading
Same as line 11.

2019-04-12 08:45 UTC, radinamatic commented on integration_testing/features/super-admin/super-admin-export-data.feature
> +      And the *Download* button is enabled
Swap the lines 23 & 24.

2019-04-12 08:46 UTC, radinamatic requested changes
Looking good, just a few changes needed.

2019-04-15 00:11 UTC, mrpau-julius commented
Thank you @radinamatic for reviewing my PR. I will change that later.

2019-04-23 22:06 UTC, indirectlylit commented
Is this ready for re-review or still a WIP?

Please set the appropriate labels

2019-04-29 08:26 UTC, radinamatic approved these changes
Looking good! :+1:

2019-04-29 08:26 UTC, merged