Add Gherkin stories for editing and previewing lessons/quizzes
learningequality/kolibri pull request #5460
Opened 2019-05-07 00:43 UTC by khangmach

Adds stories for the following:
- Edit lesson from reports tab
- Edit quiz from reports tab
- Preview quiz
- Preview lesson

2019-05-07 17:36 UTC, jonboiser commented on integration_testing/features/coach/coach-edit-lesson-from-report.feature
> +    Then I click into Lesson A report
Combine the above When and Then into the "Given", so the starting point for the test is being on the Report page.

2019-05-07 17:38 UTC, jonboiser commented on integration_testing/features/coach/coach-edit-lesson-from-report.feature
> +    Then I click into Lesson A report
Apply this to the other scenarios, so there is a shorter path to the Feature we're trying to test.

2019-05-08 05:30 UTC, radinamatic commented
Seemed easier to [open a PR](https://github.com/khangmach/kolibri/pull/1) on top of your PR :slightly_smiling_face: 
Feel free to merge and add more changes if necessary!

2019-05-09 18:38 UTC, radinamatic approved these changes
This looks good to me! :+1: 
Let's merge, and I'll make another pass through all the gherkins (not just coach) before the next integration testing round :slightly_smiling_face:

2019-05-09 18:54 UTC, jonboiser requested changes
I have another PR on khangmach/gherkins to shorten the scenarios and add other details that should be testd

2019-05-09 18:58 UTC, radinamatic commented
Awesome, thanks @jonboiser :+1:

2019-05-09 18:59 UTC, jonboiser approved these changes

2019-05-09 22:34 UTC, indirectlylit commented
Thanks all - great job!

Moving forward I'd like to use this iterative approach to the stories in git from the start: @khangmach and @jtamiace can submit the skeletons early, and the rest of us can give feedback and then make updates to them

2019-05-09 22:34 UTC, merged

2019-05-09 23:17 UTC, radinamatic commented
Seems like a great workflow to use! Yey teamwork :busts_in_silhouette: