Gherkin stories for the Windows setup logging
learningequality/kolibri pull request #5742
Opened 2019-07-04 09:52 UTC by mrpau-richard

### Summary
I created a Gherkin stories for this [PR](https://github.com/learningequality/kolibri/pull/5732)
This is still a work in progress PR

### Reviewer guidance

…

### References

…

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2019-07-08 01:44 UTC, cpauya requested changes

2019-07-08 01:44 UTC, cpauya commented on integration_testing/features/super-admin/super-admin-windows-installer-setup-error-log.feature
> +Feature: Super admin Windows installer setup failed show the error logs
Please re-phrase, maybe into: `Super admin can see error logs during a failed Windows installer setup.`

2019-07-08 01:44 UTC, cpauya commented on integration_testing/features/super-admin/super-admin-windows-installer-setup-error-log.feature
> +        And I double click the Kolibri Windows installer
I think this is missing a `Given` right after the `Scenario` line?

2019-07-08 01:44 UTC, cpauya commented on integration_testing/features/super-admin/super-admin-windows-installer-setup-error-log.feature
> +
Can we also put other scenarios which may possibly fail during a Windows installation?  Maybe like:

1. Install using `KOLIBRI_HOME_PORT` environment variable but with a non-numeric value like `ABC` or a combo like `ABC8080`?
1. Upgrade from an existing Kolibri installation where we want to preserve the database?

2019-07-09 07:01 UTC, mrpau-richard commented on integration_testing/features/super-admin/super-admin-windows-installer-setup-error-log.feature
> +
> Install using KOLIBRI_HOME_PORT environment variable but with a non-numeric value like ABC or a combo like ABC8080?

I think we can't add that scenarios here, The error happens after the Kolibri setup successfully install not during the Kolibri setup installation. I created an issue about this [here](https://github.com/learningequality/kolibri-installer-windows/issues/113), lets create a gherkin feature after that issue resolve


> Upgrade from an existing Kolibri installation where we want to preserve the database?

That scenario also not related to this gherkin feature. During the installation the Kolibri setup did not check if there is an existing database.

2019-07-10 02:56 UTC, cpauya requested changes
Good update, very straight-forward.  Please address my requested changes.

2019-07-10 02:56 UTC, cpauya commented on integration_testing/features/super-admin/super-admin-windows-installer-setup-error-log.feature
> +    Scenario: Install the kolibri Windows installer with the error
This `Scenario` still has no `Given` or `When` statements after it.  Is this intentional?

2019-07-10 02:56 UTC, cpauya commented on integration_testing/features/super-admin/super-admin-windows-installer-setup-error-log.feature
> +
Please fix the indentation and capitalisations in this `Scenario`.  I remember that we're using two spaces for to indent Gherkin statements.

2019-07-11 02:29 UTC, cpauya approved these changes
Good updates!  Looks good to me. 😸

2019-07-11 02:34 UTC, merged

2019-10-17 17:53 UTC, indirectlylit commented
fixes https://github.com/learningequality/kolibri/issues/5911