Corrected Progress bar position on Card thumbnail
learningequality/kolibri pull request #5766
Opened 2019-07-14 22:17 UTC by luna215

### Summary
Changed CSS style for the class `progress-bar-wrapper` and have tested it on Chrome and Mozilla Firefox

…

### Reviewer guidance
Navigate to /learn/channels/

…

### References
This pull request fixes this issue:
![Issue](https://github.com/learningequality/kolibri/issues/5755)

…

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2019-07-15 17:11 UTC, jonboiser approved these changes
Looks good to me!

2019-07-15 17:15 UTC, indirectlylit commented
my main question is .. why was it `-12px;` before, and when did that stop being correct?

2019-07-15 17:24 UTC, jonboiser commented
The bottom was added as part of #5502. I don't think that was the right fix for this problem. I'm adding some more code to this PR to fix both the issue from #5502 and this one.

2019-07-15 17:24 UTC, indirectlylit commented
@luna215  thanks for the contribution.

For next time please check your markdown and the checklist:

![image](https://user-images.githubusercontent.com/2367265/61235488-7eb72280-a6ea-11e9-883c-376bc7318ee4.png)

If possible, it would be great to identify when this broke. `git bisect` is a useful tool for this sort of thing!

2019-07-15 17:25 UTC, jonboiser requested changes
This will actually bring back the issue #5007. I need to add some extra stuff to this.

2019-07-15 18:19 UTC, jonboiser approved these changes

2019-07-15 18:20 UTC, merged

2019-07-15 23:56 UTC, luna215 commented
@jonboiser I wasn't too sure how you wanted the progress bar to look, so I assumed you just wanted to get rid of the space between the thumbnail and the progress bar. I can give it another shot once you're done adding things to it.

2019-07-16 00:01 UTC, jonboiser commented
@luna215 By removing the `bottom: -12px` rule, we would have brought back the problem in #5007 (your original PR simply reversed what was done in PR #5502).

So, what I did was add a 5px border to the div containing the thumbnail and changed the `bottom` positioning of the progress bar so that it would lie on top of that border (and not on the thumbnail image).

This resolves the original problem of #5007 in a way that avoids what we saw in #5755, so there's no need to re-open this PR. Thanks!