Extend AppError page to show special messages and actions when GETting a 404
learningequality/kolibri pull request #5869
Opened 2019-08-12 20:20 UTC by jonboiser

### Summary

1. Adds a 404 page whenever the catch-all error handler `handleApiError` is used and the response shows it was a 404 resulting from a GET request.
1. Fix broken links on manage device permissions page

There are still a few places where the 404 page doesn't show because of something particular about how errors are handled. Here is the current list

1. Learn > Exam Report Viewer
1. Coach > most reports pages

### Reviewer guidance

You can get a 404 in most cases by modifying a UUID in a URL by a character. Make sure that the special 404 version of App Error shows up and that the default action button takes you to the root of the plugin you're in.

### References

Fixes #5666 

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2019-09-18 19:15 UTC, rtibbles commented
I think just rebasing to current develop should resolve this.

2019-10-14 17:25 UTC, jonboiser commented on kolibri/core/assets/src/views/AppError/index.vue
> +    } else if (url.includes(urls['kolibri:coach:coach']())) {
@rtibbles These URL names are probably wrong now. Can you share off the top of your head what they should be now?

2019-10-14 22:01 UTC, rtibbles requested changes
Looks good, have not tested.

One small tweak needed.

2019-10-14 22:01 UTC, rtibbles commented on kolibri/core/assets/src/views/AppError/index.vue
> +    if (url.includes(urls['kolibri:kolibri.plugins.learn:learn']())) {
These checks will break if any of these plugins is disabled. Should always do a check that the URL exists:
`urls['kolibri:kolibri.plugins.learn:learn'] && url.includes(urls['kolibri:kolibri.plugins.learn:learn']())`

2019-10-14 23:44 UTC, rtibbles approved these changes

2019-10-18 23:29 UTC, indirectlylit reviewed
awesome!

2019-10-18 23:29 UTC, indirectlylit commented on kolibri/core/assets/src/views/AppError/index.vue
> +      pageNotFoundMessage: "Sorry, we can't seem to find the page you're looking for.",
unnecessary trailing period. From the [writing guidelines](http://kolibribeta.learningequality.org/design/patterns/writing):

> Skip periods and unnecessary punctuation

2019-10-18 23:33 UTC, indirectlylit commented on kolibri/core/assets/src/views/AppError/index.vue
> +      pageNotFoundMessage: "Sorry, we can't seem to find the page you're looking for.",
Actually, looks like we forgot to incorporate the latest strings: https://docs.google.com/document/d/1B7E9RrxLatDF8R9a8JG8W8tEez6KrjrwPQPbE1biKsg/edit#

2019-10-21 22:04 UTC, merged