Responsively make room for info icon in demographic fields
learningequality/kolibri pull request #6915
Opened 2020-05-21 21:37 UTC by jonboiser

### Summary

Responsively applies different widths to controls when `windowIsSmall` computed prop is true.

When window is larger, the icons are unchanged relative to original positioning.

![CleanShot 2020-05-21 at 14 34 00](https://user-images.githubusercontent.com/10248067/82608812-35d4c380-9b70-11ea-9cee-5f1a35526673.gif)

### Reviewer guidance

1. Check out the fix on the other pages: Sign UP, Edit User, Profile Edit, etc.

### References

Fixes #6359
…

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2020-05-23 00:39 UTC, indirectlylit commented
this looks good!

My original intuition was that the behavior should not be conditional, and instead the icons would always be inside the margin. @jtamiace @khangmach is this something we have any precedent for one way or the other?

![image](https://user-images.githubusercontent.com/2367265/82717758-28dcd080-9c53-11ea-902d-9221221abd3a.png)

2020-05-26 23:32 UTC, jtamiace commented
I can't remember whether we've ever specified one way or the other, but it seems to be a better practice to have it inside the content area.

Once we have a chance to switch over to the outlined text fields, this looks like the case anyway https://v15.vuetifyjs.com/en/components/text-fields

2020-05-27 16:22 UTC, indirectlylit commented
true - this is how vuetify handles icons:

![image](https://user-images.githubusercontent.com/2367265/83046204-8c705080-9ffb-11ea-8fae-d9eb46bc8702.png)

2020-05-27 16:22 UTC, indirectlylit requested changes
let's remove the conditional behavior, and always have the icons inset within the content

2020-06-03 16:37 UTC, closed without merging