Migrate docs manual test a11y
learningequality/kolibri pull request #6921
Opened 2020-05-23 08:40 UTC by Lewiscowles1986

### Summary

Centralise documentation in repo

* Fixes #2362

### Reviewer guidance

This is an import of a Google doc, and Wiki-entry from it's HTML

* [ ] Check links
* [ ] Ensure images are correct
* [ ] Double-check formatting
* [ ] Good use of project resources

Spellings and grammar should be 1:1 as this has not been typed out, but rather copied verbatim.

### References

* https://docs.google.com/document/d/1CG4Z0hofN0ipsny9mDf1xr2C_eY5c-T2nUbhlz2eZjA
* https://github.com/learningequality/kolibri/wiki/Accessibility-Resources-(Tools)

### Contributor Checklist

PR process:

- [X] PR has the correct target branch and milestone
- [X] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] ~If this is an important user-facing change, PR or related issue has a 'changelog' label~
- [ ] ~If this includes an internal dependency change, a link to the diff is provided~

Testing:

- [ ] Contributor has fully tested the PR manually
       ***I would love to have some help with this***
- [ ] ~If there are any front-end changes, before/after screenshots are included~
- [ ] ~Critical user journeys are covered by Gherkin stories~
- [ ] ~Critical and brittle code paths are covered by unit tests~

### Reviewer Checklist

- [ ] Automated test coverage is satisfactory
- [ ] PR is fully functional
- [ ] PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- [ ] External dependency files were updated if necessary (`yarn` and `pip`)
- [ ] Documentation is updated
- [ ] Contributor is in AUTHORS.md

2020-05-23 08:41 UTC, Lewiscowles1986 commented
Currently just setup to track WiP

Windows (the largest manual testing section) is yet to be approached.

Hoping for some feedback / guidance on testing the docs.

2020-05-23 09:49 UTC, indirectlylit commented
cc @radinamatic

2020-05-23 10:44 UTC, Lewiscowles1986 commented
Once I get a green from the CI, I'll mark ready for review. I've clicked around a fair bit.

2020-05-23 10:56 UTC, Lewiscowles1986 commented
Should be good now.

2020-05-23 18:22 UTC, indirectlylit commented
Thanks! I know the build system and RST can both be a chore to wrangle with so your efforts are appreciated.

Running this locally ought to help clear up the remainder of the issues:

```bash
pre-commit run --all-files
```

LE is out through Tuesday, but when we resume I expect @radinamatic will have a chance to review.

FYI, feel free to add your info to authors.rst: https://github.com/learningequality/kolibri/blob/develop/AUTHORS.md

2020-05-27 22:54 UTC, indirectlylit commented
This is awesome, thanks! I'll still let @radinamatic weigh in when she's ready, because this is mostly her domain.

This overall seems fine and I'd be fine merging it as-is, because it is definitely an improvement.

However in #2362 you said:

> I sort of went a slight different way regarding structure to try to make docs as small (parts) as possible). Happy to revise on PR if needed

I do find this a little this structure a bit more deeply-nested than I would generally prefer, and in fact have in the past [intentionally flattened](https://github.com/learningequality/kolibri/pull/4536) the structure, following the rule-of-thumb that "flat is better than nested" in many situations.

Concretely, in cases like this it takes a high number of clicks to reach what ends up being a very tiny page:

![image](https://user-images.githubusercontent.com/2367265/83079282-56998f00-a030-11ea-92d0-aba73af7a4e3.png)

One other subtle issue is that combining page content with an inline table of contents leads to slightly inconsistent behaviors in the side-nav bar, with some links pointing at sub-pages, and other links pointing at anchor locations:

![image](https://user-images.githubusercontent.com/2367265/83080122-4c789000-a032-11ea-8954-3d4b6c86f323.png)

2020-05-28 05:53 UTC, Lewiscowles1986 commented
I understand and am open to moving on initial hot-takes, especially now I've got it built. The installation pages could for example be unified, or deferred upstream with a single link.

The reason I opted for the deeper structure, was so that updates to documents were not so interwoven that they would cause useless information, information overload / scroll fatigue on mobile, or merge / operational problems as well as data transfer (windows document). In particular the windows install guide was very detailed and long. The mac guide a stub to be expanded upon; the accessibility covering many a11y disciplines. This was intended as a first-step PR, rather than fix all the docs.

The general section is indeed a concern. I didn't really know what to do with it as it is useful, but not so much a part of the documentation other areas.

While I hear you on link depth, I think the prev / next with tiny fast-loading pages really helps there.

2020-05-28 05:57 UTC, Lewiscowles1986 commented
Would moving the trio of installing to the top of the setup for each OS be acceptable. I kind of want each OS partitioned as it's rare to find a maverick that wishes to be fantastic in all three.

2020-05-28 05:59 UTC, Lewiscowles1986 commented
Also, is there a way to include the documents within eachother so that instead of linking to a document I might combine sub-section and file links. This would resolve the git workflow issue of large docs files.

2020-05-28 21:43 UTC, indirectlylit commented
Agreed, doing some consolidation e.g. of the installation sounds like a balanced approach.

It's possible to include docs within each other with the [`.. include::`](https://docutils.sourceforge.io/docs/ref/rst/directives.html#including-an-external-document-fragment) directive if that would be helpful.

For the general section, perhaps just move those notes to a new file `docs/manual_testing/general_notes.rst` and put it as the first item in the TOC? e.g.

```rst
.. toctree::
   :maxdepth: 4
   :titlesonly:

   general_notes
   testing_with_vms/index
   a11y_resources/index
```

2020-05-29 11:51 UTC, Lewiscowles1986 commented
Combined and tested it works. I rather like this as it gives the logical separation I was after, with the presentation you were after. Now mac, linux, windows people can work independently on source files without merge conflicts, and there are fewer clicks.

I Hope @radinamatic agrees with our leanings 😀

2020-05-29 14:47 UTC, Lewiscowles1986 commented
I got a bit carried away as I had a lot of calls today, and this seemed a good thing to work on while on call.

The last commit might need to be removed. I like it, but it seems to mess with something done recently to change a bottom margin, which in my case was collapsing.

![Screenshot (1245)](https://user-images.githubusercontent.com/2605791/83273076-f5a2c000-a1c3-11ea-8332-24e4b25a38ff.png)
![Screenshot (1244)](https://user-images.githubusercontent.com/2605791/83273079-f63b5680-a1c3-11ea-9731-61040c9b961f.png)

I am happy to remove that commit. Unfortunately I have not got the UX or presentation using TOC or sidebar I'd like

2020-05-29 21:31 UTC, Lewiscowles1986 commented
Oh I also hid "Test Kolibri in Windows Guest" as it is redundant

2020-06-05 16:43 UTC, indirectlylit commented
these changes look very good to me, thank you. I think @radinamatic has been swamped with other work but we'll get this in soon

2020-06-05 16:44 UTC, indirectlylit approved these changes

2020-06-05 23:16 UTC, radinamatic requested changes
Thank you @Lewiscowles1986 for this contribution, and apologies for not reviewing earlier!
(:pray: to @indirectlylit for jumping in)

Everything in the structure looks good to me, just two small changes remain, and then we can merge.

The original VM testing doc is quite old, text is not outdated, but screenshots are from the KA Lite era (2016 :joy: )

2020-06-05 23:16 UTC, radinamatic commented on docs/manual_testing/testing_with_vms/windows/install_kolibri.rst
> +1. Download one of these small testing channels, or others :
These are old names, and we should reference tokens. I suggest deleting the second, and use just this instead:

* `nakav-mafak` - Kolibri QA Channel (~180MB)

2020-06-05 23:16 UTC, radinamatic commented on docs/manual_testing/a11y_resources/firefox.rst
> +`Opquast Desktop`_
Delete this one, it has not been maintained since FF50.

2020-06-05 23:16 UTC, radinamatic commented on docs/manual_testing/a11y_resources/bookmarklets.rst
> +`Jim Thatcher’s Favelets`_
Also really old, but I like keeping them as _in memoriam_ :slightly_smiling_face:

2020-06-07 05:08 UTC, Lewiscowles1986 commented on docs/manual_testing/a11y_resources/bookmarklets.rst
> +`Jim Thatcher’s Favelets`_
Would you like me to sub-heading this using the suggested _in memoriam_?

I'm fairly certain this was a comment that this is old, but you like keeping, so I don't know if I need to call out that it's old, or remove it.

2020-06-07 05:08 UTC, Lewiscowles1986 commented
@radinamatic @indirectlylit changes made, one question. Thanks so much and hope you are both well

2020-06-08 07:41 UTC, radinamatic commented on docs/manual_testing/testing_with_vms/windows/install_kolibri.rst
> +1. Download one of these small testing channels, or others :
Line break was missing and I wanted to edit the file directly to approve, but apparently I don't have the write permissions here :confused: 

![Selection_546](https://user-images.githubusercontent.com/1457929/84004644-2a550b00-a96c-11ea-8a88-f13e15ad6115.png)


I'm going to approve, but please put in the following change before we merge:

```suggestion
1. Download this small testing channel, or others:

   * ``nakav-mafak`` - Kolibri QA Channel (~250MB)

2. Use the following command to create Kolibri users for testing.

   .. code-block:: bash

      kolibri manage generateuserdata
```

2020-06-08 07:43 UTC, radinamatic approved these changes
Great job!
Fix the line break so the list item is displayed correctly, and we can merge :+1:

2020-06-08 10:52 UTC, Lewiscowles1986 commented
shall I squash all the changes before merge? (I cannot push the button)

2020-06-08 17:10 UTC, radinamatic commented on docs/manual_testing/testing_with_vms/windows/install_kolibri.rst
> +   * `nakav-mafak` - Kolibri QA Channel (~180MB)
@Lewiscowles1986 
My bad, I included too many lines in the suggestion, so now we have some repeated content.
Could you delete lines from 22-28? Thanks!

2020-06-09 01:25 UTC, indirectlylit commented
one error: 

```
Warning, treated as error:
manual_testing/testing_with_vms/windows/install_kolibri.rst:22:Explicit markup ends without a blank line; unexpected unindent.
```

2020-06-09 10:28 UTC, Lewiscowles1986 commented
@indirectlylit it's building locally when I remove the duplicate line. Part of a problem with this RST seems to be very poor IDE support for what seems to be quite a "hot-take" on whitespace. Latest push builds locally, if it passes I'll push the squashed version ready to be merged

2020-06-09 10:56 UTC, Lewiscowles1986 commented
Changes made, CI passing. Squished history rather than curate more cleanly

2020-06-09 16:22 UTC, merged

2020-06-09 18:16 UTC, indirectlylit commented
nice, it's in! https://kolibri-dev.readthedocs.io/en/develop/manual_testing/index.html

thanks for the hard work @Lewiscowles1986

2020-06-09 18:45 UTC, radinamatic commented
Looking great, thank you @Lewiscowles1986! :+1: