Do not bootstrap every user into sign in page
learningequality/kolibri pull request #7037
Opened 2020-06-11 21:57 UTC by nucleogenesis

### Summary

@rtibbles pointed out that my initial solution to get all facility users needed for the user listing flow on the Sign In page was a performance liability. What if a Facility had 10000+ users?!

So now - the facility config receives a new value `num_users_in_facility`

And there is a new `facilityusers` endpoint that gets all FacilityUsers in a given Facility.

### Reviewer guidance

- Does sign in work?
- When you are in app context and have a facility with <= 16 users do you see them listed?
- When you are in app context and have a facility > 16 users do you see the normal "Username" field?

Also:
- How about that Python code?

### References

Discussed on Slack

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2020-06-11 23:40 UTC, rtibbles requested changes
Still some performance concerns we should clean up.

2020-06-11 23:40 UTC, rtibbles commented on kolibri/core/auth/api.py
> +        facility_ids = dict(request.GET)["member_of"]
Shouldn't need to coerce `request.GET` to a dict, and this will give a 500 when `member_of` is undefined.

2020-06-11 23:40 UTC, rtibbles commented on kolibri/core/auth/api.py
> +        serialized = FacilityUsersForFacilitiesSerializer(users)
When I profiled this query on my local machine, it ran 900+ queries, and returned a JSON string (not an object) - no need to double render the data in the line below - the Response does that internally.

2020-06-11 23:40 UTC, rtibbles commented on kolibri/core/auth/serializers.py
> +class FacilityUsersForFacilitiesSerializer(serializers.Serializer):
Can probably just do this inline in the method above, no need to define a serializer here.

2020-06-11 23:40 UTC, rtibbles commented on kolibri/plugins/device/api_urls.py
> +    url(r"allowremoteaccess", RemoteAccess.as_view(), name="allowremoteaccess"),
Odd - I thought I had deleted this endpoint on `app-support`...

2020-06-12 15:02 UTC, rtibbles commented
Two small merge conflicts - auth api.py is just parallel addition of imports, device api_urls.py the code you linted has been deleted!

2020-06-15 21:08 UTC, rtibbles reviewed
A couple of things that will need to be removed for mr linter to be happy - and one question.

2020-06-15 21:08 UTC, rtibbles commented on kolibri/plugins/user/assets/src/modules/signIn/index.js
> +      console.log(payload);
Remove?

2020-06-15 21:08 UTC, rtibbles commented on kolibri/plugins/user/assets/src/modules/signIn/index.js
> +          console.error(e);
`handleApiError` action here?

2020-06-15 21:08 UTC, rtibbles commented on kolibri/plugins/user/assets/src/views/SignInPage.vue
> +      this.$store.dispatch('signIn/fetchUsersForFacilities', facilityIdsToFetch);
What happens if this is an empty list? Should either check for that here and not dispatch the action, or inside the action just instantly resolve without the request.

2020-06-15 21:43 UTC, rtibbles approved these changes

2020-06-17 01:43 UTC, indirectlylit commented
got a test failure:

```
=================================== FAILURES ===================================
__________ FacilityAPITestCase.test_device_admin_can_create_facility ___________
self = <django.db.backends.utils.CursorWrapper object at 0x7f8b0f8023c8>
sql = 'SELECT "kolibriauth_collection"."id", "kolibriauth_collection"."name", "kolibriauth_collection"."dataset_id", "kolibr...kolibriauth_facilitydataset"."id") WHERE ("kolibriauth_collection"."kind" = %s AND "kolibriauth_collection"."id" = %s)'
params = ('classroom', 'facility', '43ec85400423b1fbfefc6f75d32a7fc8')
    def execute(self, sql, params=None):
        self.db.validate_no_broken_transaction()
        with self.db.wrap_database_errors:
            if params is None:
                return self.cursor.execute(sql)
            else:
>               return self.cursor.execute(sql, params)
E               psycopg2.ProgrammingError: operator does not exist: text = uuid
E               LINE 1: ...OM "morango_transfersession" U0 WHERE U0."filter" = ("kolibr...
E                                                                            ^
E               HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
.tox/postgres/lib/python3.5/site-packages/django/db/backends/utils.py:64: ProgrammingError
The above exception was the direct cause of the following exception:
self = <kolibri.core.auth.test.test_api.FacilityAPITestCase testMethod=test_device_admin_can_create_facility>
    def test_device_admin_can_create_facility(self):
        new_facility_name = "New Facility"
        self.client.login(
            username=self.superuser.username,
            password=DUMMY_PASSWORD,
            facility=self.facility1,
        )
        self.assertEqual(
            models.Facility.objects.filter(name=new_facility_name).count(), 0
        )
        response = self.client.post(
            reverse("kolibri:core:facility-list"),
            {"name": new_facility_name},
>           format="json",
        )
kolibri/core/auth/test/test_api.py:329: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
.tox/postgres/lib/python3.5/site-packages/rest_framework/test.py:300: in post
    path, data=data, format=format, content_type=content_type, **extra)
.tox/postgres/lib/python3.5/site-packages/rest_framework/test.py:213: in post
    return self.generic('POST', path, data, content_type, **extra)
.tox/postgres/lib/python3.5/site-packages/rest_framework/test.py:238: in generic
    method, path, data, content_type, secure, **extra)
.tox/postgres/lib/python3.5/site-packages/django/test/client.py:416: in generic
    return self.request(**r)
.tox/postgres/lib/python3.5/site-packages/rest_framework/test.py:289: in request
    return super(APIClient, self).request(**kwargs)
.tox/postgres/lib/python3.5/site-packages/rest_framework/test.py:241: in request
    request = super(APIRequestFactory, self).request(**kwargs)
.tox/postgres/lib/python3.5/site-packages/django/test/client.py:501: in request
    six.reraise(*exc_info)
.tox/postgres/lib/python3.5/site-packages/django/utils/six.py:686: in reraise
    raise value
.tox/postgres/lib/python3.5/site-packages/django/core/handlers/exception.py:41: in inner
    response = get_response(request)
.tox/postgres/lib/python3.5/site-packages/django/core/handlers/base.py:187: in _get_response
    response = self.process_exception_by_middleware(e, request)
.tox/postgres/lib/python3.5/site-packages/django/core/handlers/base.py:185: in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
.tox/postgres/lib/python3.5/site-packages/django/views/decorators/csrf.py:58: in wrapped_view
    return view_func(*args, **kwargs)
.tox/postgres/lib/python3.5/site-packages/rest_framework/viewsets.py:116: in view
    return self.dispatch(request, *args, **kwargs)
.tox/postgres/lib/python3.5/site-packages/rest_framework/views.py:495: in dispatch
    response = self.handle_exception(exc)
.tox/postgres/lib/python3.5/site-packages/rest_framework/views.py:455: in handle_exception
    self.raise_uncaught_exception(exc)
.tox/postgres/lib/python3.5/site-packages/rest_framework/views.py:492: in dispatch
    response = handler(request, *args, **kwargs)
kolibri/core/api.py:133: in create
    self.serialize_object(instance.id), status=HTTP_201_CREATED, headers=headers
kolibri/core/api.py:115: in serialize_object
    return self.serialize(queryset.filter(pk=pk))[0]
kolibri/core/api.py:99: in serialize
    list(map(self._map_fields, self._serialize_queryset(queryset) or [])),
.tox/postgres/lib/python3.5/site-packages/django/db/models/query.py:254: in __bool__
    self._fetch_all()
.tox/postgres/lib/python3.5/site-packages/django/db/models/query.py:1121: in _fetch_all
    self._result_cache = list(self._iterable_class(self))
.tox/postgres/lib/python3.5/site-packages/django/db/models/query.py:106: in __iter__
    for row in compiler.results_iter(chunked_fetch=self.chunked_fetch):
.tox/postgres/lib/python3.5/site-packages/django/db/models/sql/compiler.py:841: in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch)
.tox/postgres/lib/python3.5/site-packages/django/db/models/sql/compiler.py:899: in execute_sql
    raise original_exception
.tox/postgres/lib/python3.5/site-packages/django/db/models/sql/compiler.py:889: in execute_sql
    cursor.execute(sql, params)
.tox/postgres/lib/python3.5/site-packages/django/db/backends/utils.py:64: in execute
    return self.cursor.execute(sql, params)
.tox/postgres/lib/python3.5/site-packages/django/db/utils.py:94: in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
.tox/postgres/lib/python3.5/site-packages/django/utils/six.py:685: in reraise
    raise value.with_traceback(tb)
```

2020-06-17 03:16 UTC, indirectlylit commented
also sorry, one more conflict to resolve. This should be the last of them because subsequent dev will not happen in `app-support`

2020-06-17 16:27 UTC, nucleogenesis commented
@rtibbles @indirectlylit I got started on this pay night but ended up spending most of it getting Postgres configured so I could run the tox. 

I’ll figure this out today but any guidance is appreciated. Seems I need to Cast the thing I’m giving TransferSession to filter by.

2020-06-19 16:19 UTC, merged