KDS Iconography updates
learningequality/kolibri pull request #7190
Opened 2020-06-25 21:29 UTC by nucleogenesis

### Summary

Implements new icon naming conventions and icons between KDS and Kolibri.

TODO: Use custom icons and non-package icons and update the names for those.

### Reviewer guidance

TBD

### References

…

----

### Contributor Checklist

PR process:

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2020-07-02 21:35 UTC, micahscopes commented
I was able to reproduce [this missing icon issue](https://github.com/learningequality/kolibri/issues/7241) while reviewing the PR.  Here are the two relevant stack traces I found:

```
vue.runtime.esm.js:619 [Vue warn]: Error in render: "TypeError: Cannot read property 'icon' of undefined"
found in
---> <KIcon> at node_modules/kolibri-design-system/lib/KIcon/index.vue
       <KButton> at node_modules/kolibri-design-system/lib/buttons-and-links/KButton.vue
         <KIconButton> at node_modules/kolibri-design-system/lib/buttons-and-links/KIconButton.vue
           <SearchBox> at kolibri/plugins/learn/assets/src/views/SearchBox.vue
             <ActionBarSearchBox> at kolibri/plugins/learn/assets/src/views/ActionBarSearchBox.vue
               <KeenUiToolbar> at kolibri/core/assets/src/views/KeenUiToolbar.vue
                 <AppBar> at kolibri/core/assets/src/views/AppBar.vue
                   <ScrollingHeader> at kolibri/core/assets/src/views/CoreBase/ScrollingHeader.vue
                     <CoreBase> at kolibri/core/assets/src/views/CoreBase/index.vue
                       <Root>
```
and 

```
vue.runtime.esm.js:619 [Vue warn]: Error in render: "TypeError: Cannot read property 'icon' of undefined"
found in
---> <KIcon> at node_modules/kolibri-design-system/lib/KIcon/index.vue
       <UiIcon> at node_modules/kolibri-design-system/lib/keen/UiIcon.vue
         <ContentIcon> at kolibri/core/assets/src/views/ContentIcon.vue
           <CardThumbnail> at kolibri/plugins/learn/assets/src/views/ContentCard/CardThumbnail.vue
             <RouterLink>
               <ContentCard> at kolibri/plugins/learn/assets/src/views/ContentCard/index.vue
                 <AssignedExamsCards> at kolibri/plugins/learn/assets/src/views/classes/AssignedExamsCards.vue
                   <ClassAssignmentsPage> at kolibri/plugins/learn/assets/src/views/classes/ClassAssignmentsPage.vue
                     <CoreBase> at kolibri/core/assets/src/views/CoreBase/index.vue
                       <Root>
```

2020-07-02 21:49 UTC, micahscopes requested changes
First the good news.  The dreaded `<h1>hi</h1>` appears to be gone!  :partying_face: 

To review this PR, I first ran `yarn unlink kolibri-design-system` and `yarn install --force`.  I also stopped and started devserver-hot.  For the most part, everything looked right, apart for a few small things.

One is the alignment on these forward/back buttons... To me, it looked a little off relative to the page number info.  I wasn't sure if that's how it's designed (or if it's relevant to these changes), but figured it'd be worth it to share:
![image](https://user-images.githubusercontent.com/389782/86411868-66397280-bc83-11ea-928b-947963086701.png)

Another similar thing I noticed was with the "verified" icon in the facility list:
![image](https://user-images.githubusercontent.com/389782/86411974-a26cd300-bc83-11ea-9c97-7ea634805d42.png)

I also was able to reproduce the missing icon issue reported in #7241, and pasted some relevant console output in a separate comment.

2020-07-02 21:49 UTC, micahscopes commented on kolibri/plugins/coach/assets/src/views/reports/ReportsLessonResourceLearnerListPage.vue
>          return this.contentMap[this.$route.params.resourceId];
Is this `console.log` statement intentional?

2020-07-08 00:07 UTC, indirectlylit commented
bumped to beta5 - ref: https://github.com/learningequality/kolibri-design-system/pull/65

2020-07-08 00:23 UTC, indirectlylit approved these changes
looking good!

![image](https://user-images.githubusercontent.com/2367265/86858911-703de580-c076-11ea-9253-2f374e2a1e10.png)

![image](https://user-images.githubusercontent.com/2367265/86858980-8cda1d80-c076-11ea-86e0-4fa0aea377f7.png)

2020-07-08 13:38 UTC, indirectlylit commented
one final build failure:

```
kolibri/plugins/coach/assets/src/views/common/notifications/__test__/NotificationCard.spec.js
  ● NotificationCard component › shows the correct content icon if the assignment is a Quiz

    expect(received).toEqual(expected) // deep equality

    Expected: "quiz"
    Received: "exam"

      114 |       });
      115 |       const contentIcon = wrapper.find({ name: 'ContentIcon' });
    > 116 |       expect(contentIcon.props().kind).toEqual(iconKind);
          |                                        ^
      117 |     }
      118 |   );
      119 | 

      at kolibri/plugins/coach/assets/src/views/common/notifications/__test__/NotificationCard.spec.js:116:40
```

2020-07-08 16:17 UTC, micahscopes approved these changes
I checked for the remaining issues and they were gone :astonished: 

(Leaving only a couple of `console.log` statements in their wake :ocean:)

2020-07-08 16:17 UTC, micahscopes commented on kolibri/core/assets/src/views/ContentIcon.vue
> +          console.log(typeof value);
a couple of console.log statements here!

2020-07-09 11:29 UTC, merged