Update language about delete tasks
learningequality/kolibri pull request #8065
Opened 2021-05-07 17:23 UTC by marcellamaki

## Summary

This PR updates the modals for deletion tasks to include a warning that tasks cannot be cancelled or undone, as applicable. 
Fixes #6727 

Example of before/after from one of the modals

Before: 
<img width="940" alt="Screen Shot 2021-05-07 at 12 44 43 PM" src="https://user-images.githubusercontent.com/17235236/117482178-01e5e000-af32-11eb-8369-7719759a8007.png">

After: 
<img width="874" alt="Screen Shot 2021-05-07 at 12 43 07 PM" src="https://user-images.githubusercontent.com/17235236/117482133-f397c400-af31-11eb-993d-c219e1a1cca2.png">

## Reviewer guidance

You can confirm the new strings do not have any typos :) and manually QA by checking the modals that pop up when deleting: 
- Channel(s)
- Resource(s)
- Group
- Lesson
- Exam
- Class
- User

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2021-05-11 00:46 UTC, radinamatic commented
Thank you, Marcella! 👍🏽 
I know I was the one who initially reported the inability to cancel as problematic, but I'm somewhat unsure about the necessity to alert about it, **if the warning about inability to undo is already in place**.

In the first place, to increase the visibility of the warning, the phrase `This action cannot be undone/cancelled` should be at the bottom of the modal, as close as possible to the (actionable) button <kbd>Delete</kbd>. This is especially valid for modals with several phrases, as it probably happened to all of us to skip reading all in a hurry, disregard the warnings, and 😱 afterwards.

![Selection_024](https://user-images.githubusercontent.com/1457929/117737896-1c9eaa00-b1fb-11eb-8123-1b9cb4a48c51.png)

If that last warning can be in **bold** font, even better.

On the other hand, having the warning `This action cannot be cancelled` so close to the <kbd>Cancel</kbd> button seems counterintuitive and could be confusing. For that reason, since the end result is identical for the user (who cannot neither cancel nor revert), I think it would be best just to keep the same `This action cannot be undone` warning in all the confirmation modals for deleting tasks. 

`This action cannot be undone` alert should be in the new line at the end.

Lesson ❌  | Quiz ❌ | Group ✔️ 
--- | --- | ---
![Selection_027](https://user-images.githubusercontent.com/1457929/117739384-8bc9cd80-b1fe-11eb-9829-c2cc944bd478.png) | ![Selection_028](https://user-images.githubusercontent.com/1457929/117739402-93897200-b1fe-11eb-9be2-2daaf1c7b300.png) | ![Selection_029](https://user-images.githubusercontent.com/1457929/117740023-cda74380-b1ff-11eb-92a8-e5bcbcae0e78.png)

---
**Anti-MG-rant** not specific to this PR (I should open the discussion in the KDS).

Is it just my eyes that bleed when I see full phrases without the proper full stop at the end? 😕 

Looking at a question phrase ending with a proper `?`, followed by a full phrase ending without a proper `.`, followed by another phrase with a proper `.` as above, just makes me cringe.

I know that is what the MG recommends, but since not even Google follows them consistently in their flagship product, seems like we are trying to be bigger Catholics than the pope.

Gmail Settings | Gmail Settings 2 
--- | ---
![Selection_025](https://user-images.githubusercontent.com/1457929/117741147-03e5c280-b202-11eb-9843-bb742e5adba3.png) | ![Selection_026](https://user-images.githubusercontent.com/1457929/117741156-0b0cd080-b202-11eb-8678-c15ba54355b1.png)

2021-05-11 16:18 UTC, marcellamaki commented
Thanks so much for your detailed feedback @radinamatic! This is really helpful both for this PR and for me as I continue to learn about UI - so many ideas to keep for future reference 😊 

I'll work on implementing these updates today. And, aside, I totally agree with finding the lack of a "." at the end of complete sentences to be _extremely_ weird, even though I know it's in the material guidelines. Maybe something to raise at a KDS meeting? 😉

2021-05-13 14:09 UTC, nucleogenesis requested changes
One thing to note is that since these strings are the exact same in all cases and used across the whole coach and device, we should add the string to the [commonCoreStrings.js](https://github.com/learningequality/kolibri/blob/06e0ab0b7efef866da30e29256190173518328c7/kolibri/core/assets/src/mixins/commonCoreStrings.js) file and then use them in the components using the `coreString` method on that mixin like it already is being used in `DeleteResourcesModal`

https://github.com/learningequality/kolibri/blob/8f8eb3d6851027b5b427d7ab8b79e4fecb251897/kolibri/plugins/device/assets/src/views/SelectContentPage/DeleteResourcesModal.vue#L5

https://github.com/learningequality/kolibri/blob/8f8eb3d6851027b5b427d7ab8b79e4fecb251897/kolibri/plugins/device/assets/src/views/SelectContentPage/DeleteResourcesModal.vue#L32-L36

So if you add that string to the common module, it'll be available to any component mixing in that `commonCoreStrings` module. 

I also suggest maybe changing the `noUndo` key to something a bit clearer about the purpose of the string. `cannotUndoActionWarning` or something similar might make it a bit clearer to the team what the purpose of that string is. It also helps avoid ambiguity when strings might have similar literal English text, but the translation might differ depending on context. 

Additionally, when you create the string, you can add some context to it as well like the snippet below. I don't think it's necessary in this situation, especially if the key is renamed to something more descriptive, but just wanted to share:

https://github.com/learningequality/kolibri/blob/aada2189da3b789e845bcb8c337dc7ef2d99abdb/kolibri/core/assets/src/mixins/commonCoreStrings.js#L19-L22

2021-05-13 14:09 UTC, nucleogenesis commented on kolibri/plugins/coach/assets/src/views/plan/QuizSummaryPage/ManageExamModals.vue
> +      noUndo: ' This action cannot be undone',
There is a space between the opening `'` and `This` here.

2021-05-13 14:09 UTC, nucleogenesis commented on kolibri/plugins/facility/assets/src/views/ManageClassPage/ClassDeleteModal.vue
> +      noUndo: ' This action cannot be undone',
Space here as well

2021-05-13 15:20 UTC, radinamatic commented
➕ ➕ ➕ to all 3 suggestions by @nucleogenesis :

* include `This action cannot be undone` in `commonCoreStrings`
* make the purpose of that string clearer when naming it
* add the **context** with every new string

2021-05-20 15:50 UTC, nucleogenesis approved these changes
Changes look great! Thanks Marcella!

2021-05-20 16:17 UTC, merged