Backdrop visibilty
learningequality/kolibri pull request #8069
Opened 2021-05-10 10:57 UTC by Priyaraj17

## Summary

The search bar backdrop in ActionSearchBox was not visible. We just have to test which height would have been perfect. Earlier, the backdrop was acting as zero-height div element.

…

## References

Issue: #8007
…

## Reviewer guidance

I have tested for all the available screen sizes using the chrome dev-tools and I am also providing the screenshots.

## Screenshots
![WhatsApp Image 2021-05-10 at 4 19 01 PM (1)](https://user-images.githubusercontent.com/40101776/117648857-62805180-b1ac-11eb-8329-cfdb81518fb7.jpeg)
![WhatsApp Image 2021-05-10 at 4 19 01 PM (2)](https://user-images.githubusercontent.com/40101776/117648868-66ac6f00-b1ac-11eb-8674-1d9c2758ebc8.jpeg)
![WhatsApp Image 2021-05-10 at 4 19 01 PM](https://user-images.githubusercontent.com/40101776/117648881-6b712300-b1ac-11eb-83b4-6af75309bfc7.jpeg)

…

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2021-05-11 21:57 UTC, Priyaraj17 commented
@rtibbles @jonboiser is this PR okay?

2021-05-13 17:52 UTC, jonboiser commented
Could you squash your two commits into 1?

Also, like you mentioned, the backdrop does not prevent the user from scrolling. You will need to add some code like this that disables scrolling when the backdrop is visible, then re-enables it when the backdrop is removed.

https://github.com/learningequality/kolibri-design-system/blob/v0.2.x/lib/KModal.vue#L216

2021-05-13 19:05 UTC, Priyaraj17 commented
Sure, I will work on it...Thanks!

2021-05-14 16:16 UTC, Priyaraj17 commented
Hey @jonboiser I have updated the changes...Hope it's okay. Thanks!

2021-05-19 17:41 UTC, jonboiser requested changes

2021-05-19 17:41 UTC, jonboiser commented on kolibri/plugins/learn/assets/src/views/ActionBarSearchBox.vue
> +        window.document.documentElement.style['overflow'] = 'visible';
```suggestion
        window.document.documentElement.style['overflow'] = '';
```

2021-05-19 17:41 UTC, jonboiser commented on kolibri/plugins/learn/assets/src/views/ActionBarSearchBox.vue
> +    height: 90vh;
```suggestion
    height: 100vh;
```

2021-05-19 17:41 UTC, jonboiser commented on kolibri/plugins/learn/assets/src/views/ActionBarSearchBox.vue
> +    top: 116px;
```suggestion
    top: 117px; // 66px (search bar) + 55px (dropdown)
```

2021-05-19 17:42 UTC, jonboiser approved these changes
Looks good, thanks!

2021-05-19 17:44 UTC, merged