Integration of Morango 0.6.0 changes
learningequality/kolibri pull request #8183
Opened 2021-07-01 17:23 UTC by bjester

## Summary

…

## References

…

## Reviewer guidance

…

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2021-09-13 15:40 UTC, bjester commented
Unmarked this as ready for review as it seems I need to refactor the restarting of the Zerconf service in order to trigger those events

2021-09-13 15:42 UTC, rtibbles commented
> Unmarked this as ready for review as it seems I need to refactor the restarting of the Zerconf service in order to trigger those events

Possible that we could also modify the zeroconf interface a little, if we want to make the way we do the restart a little less blunt - if that would help.

2021-09-13 16:22 UTC, bjester commented
> > Unmarked this as ready for review as it seems I need to refactor the restarting of the Zerconf service in order to trigger those events
> 
> Possible that we could also modify the zeroconf interface a little, if we want to make the way we do the restart a little less blunt - if that would help.

@rtibbles Yeah should be fairly straightforward

2021-10-06 16:31 UTC, jredrejo reviewed
I have tested it and hadn't found any problem with these changes.
Only the warning messages appearing multiple times on a not SoUD server that has been used to sync several SoUD:
```
INFO     Kolibri instance 'd34fa0e29c06817d732e4f7b81f3e2aa' joined zeroconf network; device info: {'application': 'kolibri', 'kolibri_version': '0.15.0a5.dev0+git.18.g94c233af', 'instance_id': 'd34fa0e29c06817d732e4f7b81f3e2aa', 'device_name': 'jose-xps', 'operating_system': 'Linux', 'subset_of_users_device': False}
WARNING  Only Subsets of Users Devices can do automated SoUD syncing.
WARNING  Only Subsets of Users Devices can do automated SoUD syncing.
WARNING  Only Subsets of Users Devices can do automated SoUD syncing.
WARNING  Only Subsets of Users Devices can do automated SoUD syncing.
WARNING  Only Subsets of Users Devices can do automated SoUD syncing.
WARNING  Only Subsets of Users Devices can do automated SoUD syncing.
WARNING  Only Subsets of Users Devices can do automated SoUD syncing.
WARNING  Only Subsets of Users Devices can do automated SoUD syncing.
WARNING  Only Subsets of Users Devices can do automated SoUD syncing.
WARNING  Only Subsets of Users Devices can do automated SoUD syncing.
WARNING  Only Subsets of Users Devices can do automated SoUD syncing.
WARNING  Only Subsets of Users Devices can do automated SoUD syncing.
WARNING  Only Subsets of Users Devices can do automated SoUD syncing.
WARNING  Only Subsets of Users Devices can do automated SoUD syncing.
WARNING  Only Subsets of Users Devices can do automated SoUD syncing.
WARNING  Only Subsets of Users Devices can do automated SoUD syncing.
WARNING  Only Subsets of Users Devices can do automated SoUD syncing.
WARNING  Only Subsets of Users Devices can do automated SoUD syncing.
WARNING  Only Subsets of Users Devices can do automated SoUD syncing.
WARNING  Only Subsets of Users Devices can do automated SoUD syncing.
WARNING  Only Subsets of Users Devices can do automated SoUD syncing.
WARNING  Only Subsets of Users Devices can do this
WARNING  Only Subsets of Users Devices can do this
WARNING  Only Subsets of Users Devices can do this
WARNING  Only Subsets of Users Devices can do this
WARNING  Only Subsets of Users Devices can do this
WARNING  Only Subsets of Users Devices can do this
WARNING  Only Subsets of Users Devices can do this
WARNING  Only Subsets of Users Devices can do this
WARNING  Only Subsets of Users Devices can do this
WARNING  Only Subsets of Users Devices can do this
WARNING  Only Subsets of Users Devices can do this
WARNING  Only Subsets of Users Devices can do this
WARNING  Only Subsets of Users Devices can do this
WARNING  Only Subsets of Users Devices can do this
WARNING  Only Subsets of Users Devices can do this
WARNING  Only Subsets of Users Devices can do this
WARNING  Only Subsets of Users Devices can do this
WARNING  Only Subsets of Users Devices can do this
WARNING  Only Subsets of Users Devices can do this
WARNING  Only Subsets of Users Devices can do this
WARNING  Only Subsets of Users Devices can do this
INFO     Kolibri running on: http://172.17.0.1:10000/
```

2021-10-06 16:31 UTC, jredrejo commented on kolibri/core/public/utils.py
> +        logger.warn("Only Subsets of Users Devices can do this")
In a server used by an external SoUD this appears repeated several times every time the server starts and stops.
This is the list of calls taking the server to this point:
```

[20]   /datos/le/mio/kolibri/kolibri/core/discovery/utils/network/search.py(111)partial_unsubscribe()
-> self.remove_instance(other_instance)
[21]   /datos/le/mio/kolibri/kolibri/core/discovery/utils/network/search.py(153)remove_instance()
-> stop_request_soud_sync(server=instance.base_url, user=user_id)
[22] > /datos/le/mio/kolibri/kolibri/core/public/utils.py(299)stop_request_soud_sync()
-> info = get_device_info()

```

2021-10-06 17:56 UTC, bjester commented
Thanks @jredrejo! That does seem to be a small regression, which I'll look into

2021-10-11 23:19 UTC, jamalex requested changes
Took a peek at one specific piece, per a request, and added a comment there.

2021-10-11 23:19 UTC, jamalex commented on kolibri/core/auth/management/utils.py
> +                )
A couple potential consequences (depending on whether I'm missing some other pieces of this) of pulling the filters directly from the client certificate:
- This prevents the (otherwise valid and previously allowed) option of doing a single-user sync between two full-facility devices. While our current use cases/UI don't facilitate this option, it could be good to keep as an option for initiating via CLI.
- More importantly, I think this will also prevent doing a single-user sync the other direction (syncing a full-facility device as the "client" against a single-user device), which was something we explicitly aimed to allow (and is covered in the [ecosystem/integration tests](https://github.com/learningequality/kolibri/blob/release-v0.15.x/kolibri/core/auth/test/test_morango_integration.py#L585), which could be good to test locally with this PR as well -- they don't get run in the automatic tests, currently, as they're too slow; need to toggle on the `INTEGRATION_TEST` envvar).

2021-10-12 14:50 UTC, bjester commented on kolibri/core/auth/management/utils.py
> +                )
Thanks @jamalex! I didn't realize that was a use case. I will fix it.

2021-10-12 21:06 UTC, rtibbles reviewed
Code read through makes sense to me!

2021-10-12 21:06 UTC, rtibbles commented on kolibri/core/discovery/utils/network/broadcast.py
> +            port=self.port or DEFAULT_PORT,
When would we not have the port information here? (If this is just copy pasted from the previous implementation, feel free to ignore).

2021-10-14 14:43 UTC, bjester commented on kolibri/core/discovery/utils/network/broadcast.py
> +            port=self.port or DEFAULT_PORT,
This does originate from the existing code, but I think you're right that we really don't need it

2021-10-14 14:43 UTC, bjester commented on kolibri/core/auth/management/utils.py
> +                )
I have made the changes and all of the morango integration tests pass

2021-10-14 14:48 UTC, bjester commented on kolibri/core/public/utils.py
> +        logger.warn("Only Subsets of Users Devices can do this")
I have resolved this issue. Thanks @jredrejo

2021-10-14 15:02 UTC, pcenov commented
Hi @bjester, today I had a look at this [build](https://buildkite.com/learningequality/kolibri-python-package/builds/3864) on Windows, Ubuntu and Android and noticed that the auto sync is not functioning at all for the learner-only devices that I've setup on both Windows and Android using Ubuntu as a server.
Here are the logs and DB files in case you are not aware of that issue:
[WindowsLogsAndDB.zip](https://github.com/learningequality/kolibri/files/7347237/WindowsLogsAndDB.zip)
[UbuntuServerLogsAndDB.zip](https://github.com/learningequality/kolibri/files/7347238/UbuntuServerLogsAndDB.zip)
The other main scenario about syncing a full facility is functioning correctly. Let me know if you need any additional info.

2021-10-14 15:04 UTC, bjester commented
Thanks @pcenov, I'm aware of that and have been debugging that issue, but the cause is still unclear

2021-10-15 15:56 UTC, pcenov commented
Tested again today on the latest [Windows 10, Ubuntu and Android builds](https://buildkite.com/learningequality/kolibri-python-package/builds/3868) and can confirm that the sync functions correctly now.
I tried the scenarios listed in the description plus deleting the saved data on a learner-only device and restoring it to check whether it will sync back; disconnecting and reconnecting, deleting and adding resources and various other scenarios and didn't find any other issues.
I noticed that when I attempt to import a Facility or a channel from my local network I do see the Android learner-only device's URL as localhost (6b16) which seems incorrect but I don't know whether it's displayed intentionally or is a regression issue so bringing that to your attention as well.
@bjester @radinamatic

2021-10-22 15:22 UTC, rtibbles approved these changes
Nice - the cleanup of SoUD syncing jobs on unregistering is a nice addition too!

2021-10-22 15:22 UTC, merged

2021-10-22 15:22 UTC, rtibbles commented
Force merging as linting issue is resolved in https://github.com/learningequality/kolibri/pull/8513