'basic link' button and inline with number in Coach
learningequality/kolibri pull request #8720
Opened 2021-11-17 12:28 UTC by abhimnc

## Summary
Fixes #8629 

view learners' button in Coach has incorrect styling
Button is a 'basic link' and inline with number, not on next line
![image](https://user-images.githubusercontent.com/10187395/142198367-4c9b2075-e3cc-494a-9994-6d742396fd19.png)

## References

https://github.com/learningequality/kolibri/issues/8629

## Reviewer guidance

is it okay? Do I need modify more?
![image](https://user-images.githubusercontent.com/10187395/142198676-816970af-040f-465d-a0db-7242562529c0.png)

----

## Testing checklist

- [-] Contributor has fully tested the PR manually
- [-] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [-] PR has the correct target branch and milestone
- [-] PR has 'needs review' or 'work-in-progress'   ##label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2021-11-17 15:06 UTC, rtibbles commented
You have based your work here off the develop branch, which includes commits not in the release-v0.15.x branch.

To fix this, I'd recommend making sure your local copy of release-v0.15.x is up to date, and then do the following:
```
git checkout my-awesome-changes
git rebase -i release-v0.15.x
```
The second command here will open a text editor and prompt you with a list of commits. You should mark all the commits as 'drop' except your `added alignment space` commit.

Once that is done, you should force push to the remote `my-awesome-changes` branch, which will update this PR.

2021-11-18 13:54 UTC, indirectlylit requested changes
Thank you!

A couple small changes requested

2021-11-18 13:54 UTC, indirectlylit commented on package.json
> +  }
Please revert the changes to package.json and yarn.lock as they are not directly related to this fix.

I've opened a follow-up issue related to the warnings you were seeing here: https://github.com/learningequality/kolibri/issues/8728

2021-11-18 13:54 UTC, indirectlylit commented on kolibri/plugins/coach/assets/src/views/home/HomePage/OverviewBlock.vue
> +          </template>
please add a `margin-left: 24px` for balanced spacing:

| current | intended |
|--|--|
| ![image](https://user-images.githubusercontent.com/2367265/142428280-1bb63bc0-9ba5-4384-98b7-8f6a33a8ada6.png) | ![image](https://user-images.githubusercontent.com/2367265/142428153-c6de98a8-6408-4eda-b3df-2856ecf2227b.png) |

2021-11-18 20:12 UTC, abhimnc commented on kolibri/plugins/coach/assets/src/views/home/HomePage/OverviewBlock.vue
> +          </template>
added in next commit.

2021-11-18 20:13 UTC, abhimnc commented on package.json
> +  }
I am not able to revert changes to package.json and yarn.lock by git commands. should i delete this branch and create a new one with applied changes.

2021-11-18 20:37 UTC, indirectlylit commented on package.json
> +  }
Hi – I force-pushed an update to your branch which keeps only the relevant files.

For future reference, it's possible to break a previous commit in pieces and choose only portions of that commit using an interactive rebase.

See for example: https://stackoverflow.com/questions/6217156/break-a-previous-commit-into-multiple-commits

2021-11-18 20:37 UTC, indirectlylit approved these changes
looks good!

2021-11-18 21:25 UTC, merged