Make display of attempts parallel between mobile and non-mobile display
learningequality/kolibri pull request #8890
Opened 2021-12-10 02:37 UTC by rtibbles

## Summary
* Follow up from #8802 to use the same iconography and display for mobile and non-mobile attempt log list display
* Allows KSelect to take slots for option and display customization
* Uses this customization to display the dropdown and the selected value with styling consistent with the non-dropdown display
* Displays using a `<span>` in mobile and `<p>` in non-mobile view to use space more efficiently.

## References
Fixes #8888

## Reviewer guidance
Any UI weirdness as a result?
Non-mobile:
![nonmobile](https://user-images.githubusercontent.com/1680573/145507824-87e7df53-5098-4a13-acf9-9846bcfbb722.gif)

Mobile:
![mobile](https://user-images.githubusercontent.com/1680573/145507830-a63ebc38-c4ee-45b3-9401-b09a876d66a7.gif)

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2021-12-10 04:59 UTC, nucleogenesis requested changes, later dismissed
The code looks good to me but I ran into a couple spots with some UI weirdness:

1) The coach content icon items at ~tablet width have a different width than the rest:

https://user-images.githubusercontent.com/6356129/145519633-5d71f378-3980-4816-a1f1-6b0dcf2cccbe.mp4

2) (I think this is unrelated to your work so not a blocker)  "In progress". The icon centers as if there would be a "N minute ago" string under the label like when it is Complete making it off center in this case: 

![image](https://user-images.githubusercontent.com/6356129/145519774-699c27ee-d0e9-4fe1-afd8-e59b2b6cad3d.png)

2021-12-11 01:46 UTC, radinamatic commented
Nice, I'm seeing the coach icons on the mobile phone, same as on desktop! 👍🏽 

![Selection_027](https://user-images.githubusercontent.com/1457929/145659687-a1425261-f3ea-4fd8-b257-4fb9d8d5b9c3.png)

2021-12-11 01:51 UTC, radinamatic approved these changes
Didn't do the super deep dive, but interacting with the lessons/quizzes and syncing seem to be working without issues.

2021-12-14 18:22 UTC, rtibbles commented
I'll fix up the issues that @nucleogenesis identified here.

2021-12-14 19:31 UTC, rtibbles commented
Updated to make sure that the coach content icon never causes odd styling, and that it never gets wrapped:

![responsivecoachcontet](https://user-images.githubusercontent.com/1680573/146066571-e644f36d-e923-4d28-9aba-18624be6a3d0.gif)

2021-12-17 16:32 UTC, marcellamaki approved these changes
Coach icon styling weirdness addressed

2021-12-17 16:33 UTC, merged