API: Add query context to the pagination object
learningequality/kolibri pull request #8933
Opened 2021-12-15 10:17 UTC by danigm

## Summary
This patch adds the getParams to the pagination object so any call to the getContentPage has the same filter parameters than the initial query call, making the pagination consistent and simpler.

2021-12-15 16:06 UTC, rtibbles requested changes
Can simplify further to just pass back the `more` object rather than attempting to deconstruct and reconstruct it.

2021-12-15 16:06 UTC, rtibbles commented on kolibri/plugins/learn/assets/src/views/ChannelRenderer/CustomContentRenderer.vue
> +              more.query = getParams;
This is the format of an example `more` object returned by the API:
```
{"include_coach_content":"true","max_results":"25","learning_activities":"wA01urpi","contentCacheKey":"1637348017","format":"json","cursor":"cD0yZTA3YTllYWU3NDc1YWQ0YjA1Y2VhODQ0Y2RlODcwNg=="}
```
It includes all the parameters needed to make the subsequent query, so this additional encoding is unnecessary.

All that is needed is for it to be passed back as the parameters for the next request.

I'd suggest instead just having an `options.more` on the options object to this parameter and then just having `fetchMore` take one option `options.more` that is just this entire object.

2021-12-15 16:06 UTC, rtibbles commented on kolibri/plugins/learn/assets/src/views/ChannelRenderer/CustomContentRenderer.vue
> +            ...options.query,
See above - can just set getParams to `options.more` and not explicitly encode anything here.

This also has the advantage of not being brittle to changes in the naming of the cursor, for example.

2021-12-16 08:43 UTC, danigm commented on kolibri/plugins/learn/assets/src/views/ChannelRenderer/CustomContentRenderer.vue
> +              more.query = getParams;
Ups, I misunderstood the more object, it's simpler than what I was thinking, I've updated the commit to remove the `query` attribute, just pass the full `options` as `getParams` in the `fetchMore` method.

2021-12-16 17:09 UTC, rtibbles approved these changes

2021-12-16 17:09 UTC, merged