Add copies link on hybrid learning content cards
learningequality/kolibri pull request #8936
Opened 2021-12-15 23:44 UTC by marcellamaki

## Summary
Ensures copies count appears on the content card, not just on list/bookmarks view and resources card

## References
Fixes #8913

<img width="1425" alt="Screen Shot 2021-12-15 at 6 40 12 PM" src="https://user-images.githubusercontent.com/17235236/146282126-65ad8214-38ff-43b2-8d64-3c527e06d1e6.png">

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2021-12-15 23:52 UTC, radinamatic commented
Yesssss!!!! I was frantically searching for this to take screenshot for the user docs... 🎉

2021-12-16 00:11 UTC, rtibbles requested changes
Ironically, not a wide array of changes (note because copies is conditionally annotated, this probably works, but these guards seem safer).

2021-12-16 00:11 UTC, rtibbles commented on kolibri/plugins/learn/assets/src/views/HybridLearningContentCard/index.vue
> +          (this.content.copies > 1) +
`content.copies` is an array.
```suggestion
          (this.content.copies && this.content.copies.length > 1) +
```

2021-12-16 00:11 UTC, rtibbles commented on kolibri/plugins/learn/assets/src/views/HybridLearningContentCardListView.vue
> +          v-if="!isMobile && content.copies"
Array!
```suggestion
          v-if="!isMobile && content.copies.length"
```

2021-12-16 00:11 UTC, rtibbles commented on kolibri/plugins/learn/assets/src/views/HybridLearningContentCard/index.vue
> +          v-if="content.copies"
```suggestion
          v-if="content.copies && content.copies.length"
```

2021-12-16 17:01 UTC, rtibbles approved these changes

2021-12-16 17:06 UTC, rtibbles requested changes
Sorry, discovered some issues in manual testing on mobile.

2021-12-16 17:06 UTC, rtibbles commented
In mobile layout, clicking on the copies button doesn't do anything:

![nocopiesonmobile](https://user-images.githubusercontent.com/1680573/146416620-b46d0bd2-d097-45f5-bc36-781764ce76c9.gif)

Works fine on a tablet layout though:
![tabletok](https://user-images.githubusercontent.com/1680573/146416676-4bee1964-201f-440f-b7c8-941f1d8f8191.gif)

2021-12-16 20:41 UTC, rtibbles approved these changes
It works!

2021-12-16 20:41 UTC, merged