Webpack 5 upgrade
learningequality/kolibri pull request #9014
Opened 2022-01-20 18:59 UTC by rtibbles

## Summary
* Upgrades NodeJS to 16.x LTS
* Changes all references to NodeJS in CI flows and documentation to v16.13.2
* Upgrades Webpack and all associated plugins, loaders to latest compatible with our stack.
* Switches our plugin building pipeline to a Webpack multicompiler setup to reduce overhead and improve build times.
* Adds build caching by default in development builds to reduce cold restart times.
* Removes complex bundle stats analyzer code and replaces with simple webpack JSON stats export

## References
Fixes #9005 
Fixes #9006 
Fixes #9007

## Reviewer guidance
Check that the frontend builds and runs as expected.

Check that all imported SVGs are properly rendering.

Check that hot devserver mode functions as expected.

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2022-01-21 02:09 UTC, nucleogenesis commented
C

2022-01-21 02:09 UTC, nucleogenesis commented
lol

2022-02-18 17:29 UTC, nucleogenesis requested changes
The only thing I noticed about hot reload was that it feels a little slower to reflect my changes than it did previously. Not the hugest deal in any case.

:heart: :heart_eyes: :heart:
It takes a minute for the server to start down from 2-3 mins - then restarts take 10-15 seconds.
:heart: :heart_eyes: :heart:

Otherwise - the only issues I noted were related to the CSS processor converting rgba colors to solid colors.

2022-02-18 17:29 UTC, nucleogenesis commented on kolibri/core/assets/src/views/Backdrop.vue
> +    background: rgba(0, 0, 0, 70%);
I think maybe there is something off w/ the CSS processing. This `rgba` value is processed into `black` .

In this particular case, this results in the semi-opaque mask under the side nav to be fully black (and the line under the Kolibri title there is black too when it shouldn't be):

![image](https://user-images.githubusercontent.com/6356129/154726190-f1af9a0d-d43b-406f-ba14-f0d4146e3929.png)

It also affects FullScreenSidePanel but that's all I've found. KModal uses the same style and is not affected during the processing likely because it's in KDS.

I did try reverting the change locally just in case and it doesn't fix the issue.

2022-02-18 17:29 UTC, nucleogenesis commented on kolibri/core/assets/src/views/Backdrop.vue
> +    background: rgba(0, 0, 0, 70%);
Found another on Profile dropdown and another on the "resource completed" modal (not screenshotted, the background is black)
![image](https://user-images.githubusercontent.com/6356129/154727062-bf53f020-803f-4eb5-9e15-a8764bc6fd30.png)

2022-02-18 17:33 UTC, rtibbles commented on kolibri/core/assets/src/views/Backdrop.vue
> +    background: rgba(0, 0, 0, 70%);
Hrm, this is probably Stylelint applying SCSS function styling to CSS functions - will revert these changes and try to exclude the linting rule that is making this happen.

2022-02-22 00:14 UTC, nucleogenesis approved these changes
LGTM! I look forward to setting my Node to version 16 by default from now on after I rebase :)

2022-02-22 00:28 UTC, merged

2022-02-22 15:51 UTC, indirectlylit commented
exciting!