Update content import flow for channel upgrades
learningequality/kolibri pull request #9086
Opened 2022-02-08 20:47 UTC by marcellamaki

## Summary

This is a PR with very few code changes but some significant differences to the UX. It adjusts the channel upgrade flow when importing additional resources. We had tagged this on `0.15.1` as Devon thought it may have been a regression (thus, more important to fix promptly) but after some [investigating](https://learningequality.slack.com/archives/CB37UM23A/p1643988582256619), it seems as though this is just an improvement, rather than a bug fix. So, I am open to suggestions about if this should go into 15 or into develop.

1. The content tree view is now always visible, even if there is an upgrade available
2. After upgrade, the user is returned to the page they were on ("Import More") rather than being returned to the main channel page

## References

Fixes #8826 

| Description | Before  |  After |
|---|---|---|
| Content tree view  | ![old-version-import (1)](https://user-images.githubusercontent.com/17235236/153067822-d8fafbc9-b376-4ba7-ba46-b510f0098469.gif)  | ![new-content-tree-view](https://user-images.githubusercontent.com/17235236/153068107-b9ed04f9-0aa3-4fa0-b22c-c0b73df62453.gif) |
| Redirecting after upgrade |  ![old-redirect-import-flow](https://user-images.githubusercontent.com/17235236/153072449-363b2947-49bc-454c-a46f-7444d13bd567.gif)  | ![new-upgrade-channel-redirect](https://user-images.githubusercontent.com/17235236/153067839-33a3388a-9e2d-40ed-98c1-c1368377cee2.gif) |

## Reviewer guidance
- Does this sufficiently address the issue? 
- Would adding some kind of "feedback" or loading state between the "upgrade channel" and being returned back to the original page be helpful (cc @jtamiace) 

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2022-02-09 23:55 UTC, jtamiace commented
Yeah, I think this could do with a loading state. Option 1 here could be a smooth experience since it keeps them on the content selection page. 

Others: option 2 is simpler, used indeterminate state assuming that updates seem to be smaller and quicker to load? Although I'm not sure this would always be true. Option 3 could help to avoid any jarring experience of seeing the channel structure suddenly change, but also creates an extra step for the user. 

![update](https://user-images.githubusercontent.com/6668144/153308756-e8808269-5dc8-481a-8c17-7566393855ba.jpg)

2022-02-10 03:46 UTC, nucleogenesis approved these changes
Code LGTM - I cannot test manually due to issues I'm having with connecting Kolibri to Studio :-/

2022-02-10 17:09 UTC, rtibbles requested changes
I think the main issue here is that the redirect to the select content page happens immediately, while the upgrade might still be happening in the background. We need to have some sort of interstitial state that waits for the upgrade task to complete before we do the redirect.

2022-02-11 16:21 UTC, marcellamaki commented
I've made the following changed based on Jessica's options above (thank you for the help!!), since it was easily available and doesn't require any new strings. Let me know what you think @rtibbles @jtamiace 

![task-status-bar](https://user-images.githubusercontent.com/17235236/153628529-23a71359-ac00-4c32-a111-25959505d630.gif)

2022-02-11 16:41 UTC, rtibbles commented
Yes, I think best to wait for the task to complete before doing the redirect (the issue is that the loaded channel tree on that page could now be out of date after the upgrade has happened).

2022-02-14 06:05 UTC, radinamatic commented
Running this from source on Firefox/Ubuntu, and I see 2 issues:

1. Once the channel is updated, all the recent update tasks on that channel appear listed (instead of just the most recent one), which puts the topic tree completely below the fold (~800px height at 80% zoom), which leaves the user wondering _Wth now...?_ 😕 

   https://user-images.githubusercontent.com/1457929/153808407-8fa83aaf-d733-432e-871e-9ec19c9135f5.mp4

2. On the second test I could still see the _Version 102 of the channel available_ in between all the tasks and the topic tree, which was also confusing (_Didn't I just updated the channel...?_)

   https://user-images.githubusercontent.com/1457929/153808404-6eadef46-e3c6-4d7d-8a42-314030fbed49.mp4 

Separate question is that there was nothing actionable in the topic tree after updating the channel... Shouldn't there be an action for the user to confirm that one resource that needed to be deleted? 🤔

2022-02-14 23:23 UTC, rtibbles commented
I think this still needs updates, as the current flow will not be loading the upgraded channel data on the topic tree. @marcellamaki and I have discussed this for a next step forward, but it hasn't been implemented yet.

2022-03-28 13:57 UTC, marcellamaki commented
@rtibbles @radinamatic this is ready for re-review

2022-03-29 11:50 UTC, pcenov commented
@marcellamaki this seemed to work fine for a while but after updating several of my channels it became impossible to update a channel.
Here's a video with the correct flow captured for a channel called MTest:
https://user-images.githubusercontent.com/79847249/160603359-b729dae8-427e-4918-9806-f8f4096cde42.mp4

Here's a video with an incorrect flow where after clicking "View changes" I don't see the changes for the selected MTest channel but instead I see a notification for another of  my channels which I had updated previously. Clicking Continue results in an attempt to list the changes for version 12 of the  MTest channel which never finishes. If I click the Back arrow I can no longer get into the content import flow:
https://user-images.githubusercontent.com/79847249/160604409-3d8e9141-6210-4499-b4e5-f60a59a43093.mp4

Tested with the following build: https://buildkite.com/learningequality/kolibri-debian/builds/3988

2022-03-29 13:39 UTC, marcellamaki commented
Thank you for the notes @pcenov - very helpful! I will look into this

2022-04-06 20:30 UTC, marcellamaki commented
@pcenov -- I've created a new PR #9252 (using a very different coding approach) for this issue. I hope the changes I have made will address the issues you ran into. If you could take a look at that and let me know your feedback, I would appreciate it! I have added a (not very official 😄 ) gherkin scenario to try to explain the workflow also, which hopefully will be helpful. Thank you! Let me know if you have questions

2022-04-07 16:50 UTC, marcellamaki commented
Superseded by #9252

2022-04-07 16:50 UTC, closed without merging