Side panel uses full width
learningequality/kolibri pull request #9144
Opened 2022-03-01 00:45 UTC by nucleogenesis

## Summary

The TopicsPage side panel was cut off due to hard-coded px width. With that removed, it fills out the space as expected.

![image](https://user-images.githubusercontent.com/6356129/156083099-39bc5e95-6a7e-4d05-9094-00c14ff73015.png)
 

## References

Fixes #8993 

## Reviewer guidance

Is there anywhere this might be a problem?

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2022-03-01 15:57 UTC, marcellamaki reviewed
Hi @nucleogenesis -- when I run this, I don't actually see any changes, although the removal of the width makes sense to me code-wise...I'm testing with regular `yarn run devserver` in Chrome....

2022-03-01 23:07 UTC, nucleogenesis commented
@marcellamaki I didn't realize this was on both the LibraryPage and TopicsPage - should be good on both now.

2022-03-02 14:48 UTC, marcellamaki requested changes
Thanks @nucleogenesis -- I was indeed looking at the Library page 😄 This looks great, thank you for fixing this

Two _small_ details that I think would be quick updates:

1. (should fix) 
`<EmbeddedSidePanel />` has a `width` prop which was used in the line you removed. Since it isn't used anymore, that can be removed from the component so there isn't a missing required prop error 

2. (a nitpick and _not_ a blocker) 
There is a tinyyy bit of overlap with the "x" close button and some of the content of the side panel. A small adjustment to the spacing maybe with some padding would make it prettier
<img width="570" alt="Screen Shot 2022-03-02 at 9 42 59 AM" src="https://user-images.githubusercontent.com/17235236/156384402-1bc8e663-1df8-465f-95e5-91fa15b25f0b.png">

2022-03-03 18:41 UTC, nucleogenesis commented
The `width` prop is used in LibraryPage's use of EmbeddedSidePanel so I left it.

Also, I'm not seeing the same overlap issue you are on Chrome or Firefox at any width (I tried super small and regular small).

![image](https://user-images.githubusercontent.com/6356129/156630934-7f33af89-9175-4694-a794-c2f8d08102bb.png)

2022-03-04 21:55 UTC, marcellamaki approved these changes

2022-03-04 21:55 UTC, merged