Mark RUNNING jobs as failed on startup
learningequality/kolibri pull request #9352
Opened 2022-04-25 10:47 UTC by danigm

Fix https://github.com/learningequality/kolibri/issues/9351

2022-04-25 15:06 UTC, rtibbles requested changes
Better if instead we do the behaviour described in: https://github.com/learningequality/kolibri/issues/9280

For best results, I think we should be cancelling tasks during shutdown, waiting for them to finish cancelling, and then setting them to `QUEUED` again, so that upon restart they automatically resume.

Also, I think this change is small enough that we can target it to 0.15.x.

2022-04-26 08:51 UTC, danigm commented
> Better if instead we do the behaviour described in: #9280
> 
> For best results, I think we should be cancelling tasks during shutdown, waiting for them to finish cancelling, and then setting them to `QUEUED` again, so that upon restart they automatically resume.
> 
> Also, I think this change is small enough that we can target it to 0.15.x.

As far as I know, right now there's code to "cancel" running jobs [during normal shutdown](https://github.com/learningequality/kolibri/blob/develop/kolibri/core/tasks/worker.py#L36). The problem that I can see is because the OS is killing other threads, or the main server process, and there's no a controlled shutdown, so jobs are not updated and they are forever `RUNNING`.

That's why I'm trying to detect that stalled jobs at startup time. I've updated this PR to "requeue" `RUNNING` jobs at startup, so jobs will continue running if something of this happens.

Thinking about possible problems, it's possible that the `RUNNING` jobs are really running in a different thread during startup? But as far as I know if this happens it's not possible to detect at startup.

2022-04-26 16:20 UTC, rtibbles commented
> As far as I know, right now there's code to "cancel" running jobs [during normal shutdown](https://github.com/learningequality/kolibri/blob/develop/kolibri/core/tasks/worker.py#L36).

The issue is that we're not waiting for the cancellation to complete before issuing the shutdown to the PoolExecutor class. We should wait for all active tasks to be in a cancelled state before we shut down the workers.

Noting that this strategy will only work when `shutdown_workers` is called in the context of the overall `shutdown` method, as otherwise the job checker thread is still running, so new items will be sent to the workers.

2022-05-17 15:50 UTC, rtibbles approved these changes

2022-05-17 15:51 UTC, merged