Allow internationalization of text before Django initialization.
learningequality/kolibri pull request #9370
Opened 2022-04-28 00:16 UTC by rtibbles

## Summary
* #9343 broke `kolibri plugins list` by relying on Django machinery for translating plugin names
* This fixes that by adding a pre-Django initialization proxy for accessing core Kolibri translations

## Reviewer guidance
Run `kolibri plugins list`

Before:
```
Traceback (most recent call last):
  File "/home/richard/github/kolibri/kolibri/dist/django/utils/translation/trans_real.py", line 168, in _add_installed_apps_translations
    app_configs = reversed(list(apps.get_app_configs()))
  File "/home/richard/github/kolibri/kolibri/dist/django/apps/registry.py", line 138, in get_app_configs
    self.check_apps_ready()
  File "/home/richard/github/kolibri/kolibri/dist/django/apps/registry.py", line 125, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/richard/.virtualenvs/kolibripy3/bin/kolibri", line 33, in <module>
    sys.exit(load_entry_point('kolibri', 'console_scripts', 'kolibri')())
  File "/home/richard/github/kolibri/kolibri/dist/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/richard/github/kolibri/kolibri/dist/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/richard/github/kolibri/kolibri/dist/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/richard/github/kolibri/kolibri/utils/cli.py", line 172, in invoke
    return super(KolibriGroupCommand, self).invoke(ctx)
  File "/home/richard/github/kolibri/kolibri/dist/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/richard/github/kolibri/kolibri/dist/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/richard/github/kolibri/kolibri/dist/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/richard/github/kolibri/kolibri/utils/cli.py", line 453, in list
    max_name_len = max((len(plugin.name(lang)) for plugin in plugins))
  File "/home/richard/github/kolibri/kolibri/utils/cli.py", line 453, in <genexpr>
    max_name_len = max((len(plugin.name(lang)) for plugin in plugins))
  File "/home/richard/github/kolibri/kolibri/plugins/coach/kolibri_plugin.py", line 30, in name
    with translation.override(lang):
  File "/home/richard/github/kolibri/kolibri/dist/django/utils/translation/__init__.py", line 181, in __enter__
    activate(self.language)
  File "/home/richard/github/kolibri/kolibri/dist/django/utils/translation/__init__.py", line 166, in activate
    return _trans.activate(language)
  File "/home/richard/github/kolibri/kolibri/dist/django/utils/translation/trans_real.py", line 239, in activate
    _active.value = translation(language)
  File "/home/richard/github/kolibri/kolibri/dist/django/utils/translation/trans_real.py", line 228, in translation
    _translations[language] = DjangoTranslation(language)
  File "/home/richard/github/kolibri/kolibri/dist/django/utils/translation/trans_real.py", line 129, in __init__
    self._add_installed_apps_translations()
  File "/home/richard/github/kolibri/kolibri/dist/django/utils/translation/trans_real.py", line 171, in _add_installed_apps_translations
    "The translation infrastructure cannot be initialized before the "
django.core.exceptions.AppRegistryNotReady: The translation infrastructure cannot be initialized before the apps registry is ready. Check that you don't make non-lazy gettext calls at import time.
```

After:
```
Available plugins           Plugin identifier                   Status
App                         kolibri.plugins.app                 DISABLED
Coach                       kolibri.plugins.coach               DISABLED
DefaultThemePlugin          kolibri.plugins.default_theme       ENABLED
DemoServer                  kolibri.plugins.demo_server         DISABLED
DeviceManagementPlugin      kolibri.plugins.device              ENABLED
DocumentEPUBRenderPlugin    kolibri.plugins.epub_viewer         ENABLED
Facility                    kolibri.plugins.facility            ENABLED
HTML5AppPlugin              kolibri.plugins.html5_viewer        ENABLED
Learn                       kolibri.plugins.learn               ENABLED
MediaPlayerPlugin           kolibri.plugins.media_player        ENABLED
DocumentPDFRenderPlugin     kolibri.plugins.pdf_viewer          ENABLED
Setup Wizard                kolibri.plugins.setup_wizard        ENABLED
SlideshowRenderPlugin       kolibri.plugins.slideshow_viewer    ENABLED
UserAuth                    kolibri.plugins.user_auth           ENABLED
User Profile                kolibri.plugins.user_profile        ENABLED
```

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2022-04-29 18:21 UTC, nucleogenesis requested changes
I checked it out and when I run the devserver or `kolibri plugins list` I get this error - seems likely related but not sure where.

The code generally looks alright - how much did you tweak of the code you vendored? 

```
Traceback (most recent call last):
  File "/home/jacob/Code/LE/kolibri/kolibri-develop/venv/bin/kolibri", line 11, in <module>
    load_entry_point('kolibri', 'console_scripts', 'kolibri')()
  File "/home/jacob/Code/LE/kolibri/kolibri-develop/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/jacob/Code/LE/kolibri/kolibri-develop/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/home/jacob/Code/LE/kolibri/kolibri-develop/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/home/jacob/Code/LE/kolibri/kolibri-develop/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/jacob/Code/LE/kolibri/kolibri-develop/kolibri/utils/cli.py", line 28, in <module>
    from kolibri.utils.main import initialize
  File "/home/jacob/Code/LE/kolibri/kolibri-develop/kolibri/utils/main.py", line 38, in <module>
    from kolibri.utils.sanity_checks import check_content_directory_exists_and_writable
  File "/home/jacob/Code/LE/kolibri/kolibri-develop/kolibri/utils/sanity_checks.py", line 12, in <module>
    from .options import generate_empty_options_file
  File "/home/jacob/Code/LE/kolibri/kolibri-develop/kolibri/utils/options.py", line 31, in <module>
    from kolibri.utils.i18n import KOLIBRI_LANGUAGE_INFO
  File "/home/jacob/Code/LE/kolibri/kolibri-develop/kolibri/utils/i18n.py", line 8, in <module>
    from django.utils.translation import to_language
ImportError: cannot import name 'to_language'
```

2022-04-29 22:35 UTC, rtibbles commented
> The code generally looks alright - how much did you tweak of the code you vendored?

Not much, mostly just removing references to Django settings, or anything else that would require the Django stack to have been initialized.

2022-04-29 22:35 UTC, rtibbles commented
I am confused by the error though - that function definitely exists.

2022-04-29 22:42 UTC, rtibbles commented
Oh, I think the error might have actually come from running this similarly themed PR: https://github.com/learningequality/kolibri/pull/9374

2022-05-02 21:01 UTC, nucleogenesis approved these changes
Confirming that the error I got was from @rtibbles `system_language` branch - rather than this `mind_your_language` branch - LGTM

2022-05-03 15:46 UTC, merged

2022-05-03 15:46 UTC, rtibbles commented
The `system_language` branch has also been updated to fix this error.