Remove profile dropdown
learningequality/kolibri pull request #9404
Opened 2022-05-04 21:08 UTC by marcellamaki

TO DO: Fix tests

## Summary
This PR moves the data previously in the user profile dropdown menu into the side navigation as part of the 0.16 update. 

Fixes #9275 

## References

Relevant [Figma file](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=868%3A14889)

## Reviewer guidance
Most of these changes can be reviewed visually in the front end for proper layout. 

Accessibility has also been tested for the addition of the "change language" option (which is not actually a link, but rather a button that opens the language switcher modal), but should be re-checked.

The section I see as potentially where things went awry would be with the SyncStatus display and the transfer of information from where it was previously to where it is now... while it was mostly a copy and paste, something might have gotten lost in the shuffle. This should probably get properly mocked with QA. 

Screenshots 

| Description  |  Screenshot |
|---|---|
| Main browser view with dropdown menu now removed (additional changes to the points display out of scope)  | <img width="939" alt="Screen Shot 2022-05-04 at 4 38 50 PM" src="https://user-images.githubusercontent.com/17235236/166823477-1b9ed1f5-dce2-421a-b756-dd1d15d61d19.png"> |
| Default Learner Display  | <img width="934" alt="Screen Shot 2022-05-04 at 4 52 48 PM" src="https://user-images.githubusercontent.com/17235236/166824079-b88b6b68-d8fa-458d-8f35-17a6fa3a5538.png"> |
| Learn Only Device display | <img width="938" alt="Screen Shot 2022-05-04 at 4 40 40 PM" src="https://user-images.githubusercontent.com/17235236/166823863-b9326889-f904-4064-b9bd-681566eeff6e.png"> |
| Overflow points/username display | <img width="544" alt="Screen Shot 2022-05-04 at 4 41 44 PM" src="https://user-images.githubusercontent.com/17235236/166824111-57250fb6-5ff8-4e5c-8b91-1ae0c90e2dfe.png"> |

 
----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2022-05-09 15:29 UTC, rtibbles requested changes
I think there are a couple of places where doing a more direct port of the original implementation might be beneficial.

2022-05-09 15:29 UTC, rtibbles commented on kolibri/core/assets/src/views/SideNav.vue
> +                  @openLanguageModal="handleShowLanguageModal()"
Rather than adding this listener to every nav component, maybe we should just move the handling of the LanguageSwitcherModal into the ChangeLanguageSideNavEntry instead? Can instantiate it in there just as easily, as it's a modal, so it should bust out of its container.

Alternatively, can do what was done in the original implementation, and just add an extra component after the `v-for` components. If you do that, you can get away without defining a new component at all and just copy the relevant string into here.

2022-05-09 15:29 UTC, rtibbles commented on kolibri/core/assets/src/views/SideNav.vue
> +      pollUserSyncStatusTask() {
In the original impementation, the polling behaviour was conditional on the dropdown being shown - this seems to have been removed in this refactor, even though we have the `navShown` prop that we could conditionalize on in the same way.

2022-05-09 15:29 UTC, rtibbles commented on kolibri/core/assets/test/views/app-bar.spec.js
> -    describe('SoUD sync status and learn-only device indicators', () => {
I feel like a couple more of these tests might withstand the great migration.

2022-05-23 19:29 UTC, marcellamaki commented on kolibri/core/assets/test/views/app-bar.spec.js
> -    describe('SoUD sync status and learn-only device indicators', () => {
I think aside from the user menu dropdown, many of these were redundant to existing code in `side-nav.spec.js` (and, I moved a few there). Do you have a suggestion of specific tests that should be added back (and/or moved?)

2022-05-23 19:44 UTC, rtibbles commented on kolibri/core/assets/test/views/app-bar.spec.js
> -    describe('SoUD sync status and learn-only device indicators', () => {
Yeah, expanding the existing tests out they do seem to be redundant. Disgregard!

2022-05-30 17:31 UTC, nucleogenesis reviewed
This adds a lot of new code to the SideNav component to add a new self-contained section. I'm wondering if it might be worth breaking that stuff into its own separate component to separate the concerns around sync status, user kind, username, fullname, etc. 

This isn't a blocking change request, but this feels like it makes SideNav do and care about more than it probably ought to. Curious about your and others' thoughts in any case.

Overall, the PR looks good. I've not browser tested it, but if QA passes on it should be good to go.

2022-05-30 17:31 UTC, nucleogenesis commented on kolibri/core/assets/src/views/AppBar.vue
> +          <span v-if="isUserLoggedIn" class="username" tabindex="-1">{{ dropdownName }}</span>
Since it isn't a dropdown anymore, maybe `dropdown` name should be renamed to avoid future confusion?

2022-05-30 17:31 UTC, nucleogenesis commented on kolibri/core/assets/src/views/SideNav.vue
> +        console.log('is polling');
Lingering console.log

2022-06-23 15:09 UTC, rtibbles approved these changes

2022-06-27 15:10 UTC, radinamatic commented
This looks much less disruptive to me, thank you! 🙂 

![remove-profile](https://user-images.githubusercontent.com/1457929/175973298-c9c6d49f-15fb-44da-92b5-4f3d14c99607.gif)

Not a blocker, just noticing that since the string context changed, it's not picking up the translations for the ``Change language`` string anymore...

2022-06-27 15:11 UTC, radinamatic approved these changes
LGTM 👍🏽 :shipit:!

2022-06-27 15:15 UTC, merged