[WIP] More granular facility sync status information
learningequality/kolibri pull request #9541
Opened 2022-06-28 11:25 UTC by MisRob

## Summary

…

## References

…

## Reviewer guidance

…

----

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2022-06-29 14:09 UTC, bjester commented on kolibri/core/auth/test/test_api.py
> +        )
If you recall from our discussion yesterday, the `transfer_session.filter` field is what will match the `dataset`'s ID. The `filter` isn't always that simple, but for a facility sync, it usually is so you can put `filter=facility.dataset_id`

2022-06-30 10:43 UTC, MisRob commented on kolibri/core/auth/test/test_api.py
> +        )
Yes, I recall but then struggled a bit to figure out what to use as a value anyways. Thank you for all your help.

2022-07-07 09:20 UTC, jredrejo commented on kolibri/core/auth/api.py
> +                        filter=transfer_session_dataset_filter,
if you're annotating with the facility queryset, why do you need this filter?

2022-07-07 09:20 UTC, jredrejo commented on kolibri/core/auth/api.py
> +                        filter=transfer_session_dataset_filter,
same as above, I don't understand why this filter is needed when using in the annotation

2022-07-07 09:22 UTC, jredrejo requested changes
Look good to me, great work. I only have left a couple of comments with the same doubt about a filter, if we can clarify it, it'd be ready from my pov

2022-07-07 13:40 UTC, MisRob commented on kolibri/core/auth/api.py
> +                        filter=transfer_session_dataset_filter,
I don't understand this in great detail and worked on this together with @bjester so he can confirm or formulate it better if needed. In my understanding, the `filter` field keeps the information about what facility a transfer session is related to. We use `dataset_id` for that purpose. An example can be seen in tests here https://github.com/learningequality/kolibri/pull/9541/files#diff-bd3440b7bfeda2f7b570e2cbacdfd560a03abff346bd3a788314f4f51e8f792bR450. I think that if `filter` wasn't specified in this way, then the query would return all transfer sessions rather than transfer sessions that have a relationship to this facility and that would be a problem because I need to know the last successful/failed sync status for this particular facility.

2022-07-07 13:43 UTC, MisRob commented
Thank you @jredrejo, I've just replied

2022-07-07 14:43 UTC, bjester commented on kolibri/core/auth/api.py
> +                        filter=transfer_session_dataset_filter,
What @MisRob said!

2022-07-08 17:14 UTC, bjester approved these changes
:100:

2022-07-08 17:14 UTC, MisRob commented
We've just tested syncing failure and success with @bjester and looks to be good

2022-07-08 17:16 UTC, jredrejo approved these changes

2022-07-08 17:16 UTC, jredrejo commented on kolibri/core/auth/api.py
> +                        filter=transfer_session_dataset_filter,
Thanks for the explanation, makes sense to  me now.

2022-07-09 07:17 UTC, merged