SetupWizard - Partial provisioning, On My Own Flow
learningequality/kolibri pull request #9730
Opened 2022-09-20 20:03 UTC by nucleogenesis

## Summary

- Prepares SetupWizard flow so that it can be partially provisioned (ie, a Facility can have been created/imported without the DeviceSettings.is_provisioned flag being set to True) -- this covers the edge case of a user not completing the process of importing users one by one and returning to it without ever saying "Okay I'm done onboarding"
- The FacilityImportResource / FacilityImportViewSet were both set to use the new `is_provisioned` flag when given in a request - it defaults to `False` **honestly not sure what default to use, as is evidenced by it defaulting to True in device settings**
- The same two were also changed so that `createsuperuser` will create a facility with a given `facility_name`.

**Outstanding issues (follow-up things)**

The following is what, at a high level, remains for the Setup Wizard. I will create a new set of issues and add them to the backlog following up on this when approved and before merging.

- Only the "On My Own" flow is setup to work properly here, other flows need work still (high effort)
- The "Step X of Y" logic is not yet implemented (medium effort)
- Wiring up bits around the user's device name and such needs to be implemented when creating facilities and devices (medium effort)
- The Interstitial needs to be designed (low effort)

## Reviewer guidance

- Can you go from start to finish through the On My Own flow?
- Thoughts on what the sane default for "is_provisioned" should be end to end?
- Any concerns with creating the facility inside the "createsuperuser" method?
- Does your language selection during Onboarding get reflected properly? (refresh on the page that says "-- INTERSTITIAL --")

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2022-10-03 23:59 UTC, rtibbles reviewed
Not completely sure, but I think the slight changes to the provision device endpoint might be responsible for the test failures here.

2022-10-03 23:59 UTC, rtibbles commented on kolibri/core/device/utils.py
> +def provision_device(device_name=None, is_provisioned=True, **kwargs):
If `is_provisioned` is not set on the request to the serializer, then `is_provisioned` here will be `None`, not `True` - the default value is only used in the case that the value is not passed to the function at all.

2022-10-03 23:59 UTC, rtibbles commented on kolibri/core/device/serializers.py
> +    is_provisioned = serializers.BooleanField(allow_null=True)
To retain the previous behaviour, this would need to default to `True` rather than allowing `None`.

2022-10-07 17:27 UTC, jredrejo requested changes
The 'on my own' flow requires to add that info to the extra_fields in the db: https://github.com/learningequality/kolibri/pull/9577
Probably, this is a lack of communication between the devs, but this is being used in the "Merge user into a facility".

OTOH, after refreshing the 'Intersitial' screen, the login screen appears, but the Sign into '' is quite odd. In my opinion, there should be a facility name or we should remove that phrase. 
![image](https://user-images.githubusercontent.com/1008178/194615545-4df56795-1c17-4bbb-b27e-27bc6689b665.png)

2022-10-13 15:35 UTC, nucleogenesis commented
@jredrejo I'll address that in a follow-up issue if that is alright -- if you're okay with that we can merge this and I'll draw up some new issues today for the follow-up on the finishing up the setup wizard altogether

2022-10-13 15:43 UTC, jredrejo commented
> @jredrejo I'll address that in a follow-up issue if that is alright -- if you're okay with that we can merge this and I'll draw up some new issues today for the follow-up on the finishing up the setup wizard altogether

The thing is that without that setting, there are features that can be tested. It's fine if people testing them know that it will require some shell work to do it to test the "Change facility" flow, as it is only meant to be working in devices having that setting.

2022-10-18 18:07 UTC, radinamatic commented
From the QA team point of view, we can only answer to these 2 questions in the Review guidance:

1. **Can you go from start to finish through the On My Own flow?**

    Not sure if I could call it _from-start-to-finish_ with the `-- INTERSTITIAL --` hickup in between, but if it's going to be addressed soon OK... 🤔

    The bigger concern is that, once we sign in again with the user created in this _On My Own_ flow, what we see is still the full admin user with access to Coach, Facility and the rest of Device page options. We chatted with @marcellamaki to confirm that the way we understood the Figma design for this flow aligns: this onboarding should end up with the user with the same type of permissions as on the current **Learn-only** devices, irregardless they are installing on the app or doing the onboarding in the browser.

    ![on-my-own2](https://user-images.githubusercontent.com/1457929/196509424-f1274327-59e8-47ab-af8d-0b647e4364ee.gif)

    Is this also something that will be addressed in the follow-up PRs, or are we misunderstanding something?

2. **Does your language selection during Onboarding get reflected properly?**

    It seems OK, some strings are missing translations at this point, but otherwise the experience is correct.

2022-10-25 14:10 UTC, radinamatic commented
Apologies for late reply @nucleogenesis 

There seems to be some progress, but the main concern exposed above still stands: user created with this flow is has full superadmin device permissions.

1. No  `-- INTERSTITIAL --` just the spinner which does not get to lead anywhere (I waited for 5 minutes and stopped the recording)

    ![on-my-own-second-take](https://user-images.githubusercontent.com/1457929/197795174-797ac42f-3514-4cc9-9a18-a32846954445.gif)

2.  After manually going to the sign in page I can still see the normal superadmin UI
   
   https://user-images.githubusercontent.com/1457929/197795862-fd0c96a0-40e7-49db-8251-51ab7a556b02.mp4

I can approve this PR if working off it will make your next task easier, but this is not the state we were expecting the **on-my-own** flow to be, nor we can use it for testing other features like **Merge accounts** and similar.

2022-10-26 17:21 UTC, nucleogenesis commented
@radinamatic let's merge this one and I'll follow up on all of the above in a separate PR

2022-10-26 17:24 UTC, merged