fix too much empty space
learningequality/kolibri pull request #9883
Opened 2022-11-30 17:50 UTC by AllanOXDi

## Summary
This PR fixes too much space on the mobile view when browsing through the channel.

## References
#9500
Before
![image](https://user-images.githubusercontent.com/103313919/204870897-01c0d55b-9b35-482b-83f5-3ef02114147d.png)
After

![Screenshot 2022-11-30 at 20 23 37](https://user-images.githubusercontent.com/103313919/204871061-416615cc-a7e4-4b53-a66d-c55077142baa.png)

## Reviewer guidance

1. Go to the Library > Browse channel.
2. Reduce your screen size to mobile view and observe

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2022-12-06 12:57 UTC, AlexVelezLl commented
I think that with this change the paddings in PC browsers worsens a bit. I think media queries could be used to avoid unexpected changes on other parts.

Before: 
![image](https://user-images.githubusercontent.com/51239030/205917603-c8993822-67da-41dd-86b3-3fdb4a864b2a.png)
After:
![image](https://user-images.githubusercontent.com/51239030/205917202-dfb00cd1-5d34-4357-824a-f44cef83b350.png)

2022-12-06 17:07 UTC, AllanOXDi commented
I think this could be a different issue the we could open. I am not sure if this fix is the one breaking it. cc @marcellamaki

2022-12-07 16:35 UTC, marcellamaki requested changes
Hi @AllanOXDi. @AlexVelezLl makes a correct point, and his suggestion about making sure your adjustments don't affect other window sizes is a good idea. 

The `$toolbar-height` variable you change is used in several places and for some other calculations, so there will likely be unintended consequences of changing it - like in the desktop view of the topics page. Rather than using media queries, which is a common strategy that Alex suggests, you can use our `responsiveWindowMixin` which you can see used in this file already. It accomplishes the same thing, by using KDS. The `windowIsLarge`, `windowIsMedium`, and `windowIsSmall` values that you may have seen referenced throughout the Kolibri frontend come from this mixin (which is imported as [part of KDS](https://kolibri-design-system.netlify.app/layout/#responsiveness)). These are designated "breakpoints" which we use across the app for consistency. `windowIsLarge`, `windowIsMedium`, and `windowIsSmall` return a Boolean. This bug is a great way to learn more about how KDS helps with managing responsive design, as we use this extensively in the Kolibri front-end.

One way you could incorporate this mixin into your fix might be to set a condition if `windowIsSmall` is true. You can use a [ternary operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator) pattern of [setting the class based on if a particular condition is true that follows this example](https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/views/ExamReport/index.vue#L95), and then in your styles, define two different classes - one to be used for small windows, and one to be used otherwise. That way, you don't need to change the variable at all, and can specify the spacing specifically for small/mobile views. Let me know what questions you might have!

2022-12-20 08:01 UTC, AllanOXDi commented
Hi @AlexVelezLl and @marcellamaki, I have added more changes to fix the edge case.

2022-12-20 10:40 UTC, pcenov commented
Hi @AllanOXDi I confirm that the mobile view is fixed as specified above. The issue mentioned by @AlexVelezLl though is still present in the channel details modal, especially when viewing the contents of a folder:

![2022-12-20_12-24-36](https://user-images.githubusercontent.com/79847249/208646492-7ae75836-8e32-41cb-90b2-e2770cf4bf16.png)

2022-12-21 14:09 UTC, AllanOXDi commented
Hi @pcenov, please let me know if this is the right spacing.

<img width="1431" alt="Screenshot 2022-12-21 at 17 04 38" src="https://user-images.githubusercontent.com/103313919/208924052-864f335c-8c8a-4ea6-8b6a-69216e518193.png">

2022-12-21 16:06 UTC, pcenov commented
Hi @AllanOXDi it seems that you should add 5 pixels more but I am just roughly comparing it to the latest develop build so it would be best if you install that yourself and measure the spacing in all locations where your code changes are making an impact:

![2022-12-21_17-36-57](https://user-images.githubusercontent.com/79847249/208948890-11031c1b-0109-4eb5-bf66-f710bec3183c.png)

![2022-12-21_17-28-42](https://user-images.githubusercontent.com/79847249/208949375-d5ce75b7-a48c-4bfa-b403-4860f21153be.png)

2023-01-04 15:38 UTC, pcenov commented
Hi @marcellamaki adding here a screenshot for comparison between the 0.15 version of the mobile view and the latest build from this PR so that it can be decided how we're going to proceed:
![2023-01-04_16-58-05](https://user-images.githubusercontent.com/79847249/210590819-4ab7ffb1-2ab3-4816-a517-6ff4b97e1f0b.png)

2023-01-04 15:59 UTC, marcellamaki commented
Thank you @pcenov! @AllanOXDi - I am sorry to say that the work you have done here, in this case isn't the thing that needs to be fixed, now. I will message you on slack about what we can do instead, and we can open a new PR for it. So, we will be fixing the bug that is causing the "banner" to be hidden, not actually the spacing. So sorry that I missed this earlier with the issue!

2023-01-10 15:13 UTC, closed without merging