[Pdf_Viewer] Fix page height and width
learningequality/kolibri pull request #9888
Opened 2022-12-02 10:22 UTC by AlexVelezLl

## Summary

Fix page height and width calculation. We used `page.view` array to get view and height of the page `view[2]` as width and `view[3]` as height. But investigating by the pdfjs code, the `page.view` object seems to be a viewBox array, that means that its values describe a slice value for the box that the page has. So `view[2]` and `view[3]` only worked for non-sliced pages as they describe the end of the width and height, but with sliced we need to consider the start of the slices which are in `view[0]` and `view[1]`.

Before:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/51239030/205269914-30a852c9-d545-43dc-aeb0-f0bdae2303b9.png">

After:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/51239030/205270159-79051997-bbb3-418f-acef-a46ec348b70b.png">

## References

Solves #5917  

## Reviewer guidance

Go to http://localhost:8000/en/learn/#/topics/c/6f7bd64fc9655bbf99122bc5df22fb9c which has cropped pages and check that all its pages are rendering with the proper width and height.

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

2022-12-02 23:17 UTC, rtibbles requested changes
Fix confirm - code changes make sense, just want some additional comments in the code to explain the update.

2022-12-02 23:17 UTC, rtibbles commented on kolibri/plugins/pdf_viewer/assets/src/views/PdfPage.vue
> +        return this.pdfPage.view[3] - this.pdfPage.view[1];
Could you add code comments here to add your explanation from the PR description into the code for the benefit of future readers?

2022-12-02 23:17 UTC, rtibbles commented on kolibri/plugins/pdf_viewer/assets/src/views/PdfPage.vue
> +        return this.pdfPage.view[2] - this.pdfPage.view[0];
And here.

2022-12-02 23:17 UTC, rtibbles commented on kolibri/plugins/pdf_viewer/assets/src/views/PdfRendererIndex.vue
> +          this.firstPageHeight = firstPage.view[3] - firstPage.view[1];
And here!

2022-12-04 23:35 UTC, AlexVelezLl commented
Comment added! :) @rtibbles

2022-12-07 17:17 UTC, rtibbles approved these changes

2022-12-07 17:17 UTC, merged